Contenido PEA: Contenido_Plugin_GUI_Table Class Reference
Contenido_Plugin_GUI_Table Class Reference
Public Member Functions
__construct ($options=array())
__init ($options=array())
initialize default table configurations and object options
_con ($varname, $varvalue=NULL)
return/set a given contenido global parameter -> it is NOT recommended to set/override a global contenido parameter!
_getAllParams ($asObject=false)
get all '$_REQUEST' parameters
_getTable ()
_getTableDataError ()
_html ($text, $domain=NULL, $quote_style=null, $charset=null, $double_encode=null, $mode=0)
get translated string converting special characters to html entities
_setTable ($_oTable)
_setting ($type, $name=null, $default="")
get Contenido effective CMS setting(s)
_text ($text, $domain=NULL)
get translated string
configTable ()
overridable method to initialize user's table configurations and object options
generate ($bReturn=TRUE)
generateTable ($bReturn=TRUE)
generateTableAction ($oAction, $bReturn=TRUE)
generateTableBottomPanel ($bReturn=TRUE)
generateTableJS ($sJSTemplate="", $bReturn=TRUE)
generateTableTools ($sTemplate="", $bReturn=TRUE)
generateTableToolsActions ($bReturn=TRUE)
generateTableToolsFilter ($sFilterCol="", $sFilterData="", $bReturn=TRUE)
generateTableToolsNotification ($sMessage="", $bReturn=TRUE)
generateTableToolsOnlyActive ($sOnlyActive="", $bReturn=TRUE)
generateTableToolsPageCount ($sRowsPerPage="", $aOptionsRowsPerPage=array(), $bReturn=TRUE)
generateTableToolsPagination ($sPageStart="", $sRowsPerPage=15, $bReturn=TRUE)
generateTableToolsSort ($sOrderField="", $sSortOrder="asc", $bReturn=TRUE)
generateTableTopPanel ($bReturn=TRUE)
getAuth ()
return Contenido authorization object
getAuthId ()
return Contenido authorized user id
getCfg ()
return Contenido configuration
getCfgClient ()
return Contenido client configuration
getColumns ()
getConfig ()
return configuration settings array
getDb ($db=null)
get (current) instance of DB_Contenido
getFooter ()
getNoRenderActions ()
getOptions ()
get object options array
getQuery ()
getRowActions ($asObject=FALSE)
getRows ($forceDbReload=FALSE)
getSession ()
get session
getTableActions ($asObject=FALSE)
getTableConfig ($asObject=FALSE)
getTableName ()
getTableTemplates ($asObject=FALSE)
getTableTools ($asObject=FALSE)
getTableToolsURL ()
getTpl ($tplName=NULL, $reset=FALSE)
generate and get template objects
isAuthNobody ()
determine if current Contenido user is not an authorized user
isDebug ()
determine if debug mode is set to true
setColumns ($_aColumns=array())
setFooter ($_aFooterCells=array())
setNoRenderActions ($aNoRenderActions)
setOptions ($options)
set object options array
setQuery ($_sQuery)
setRowActions ($_oRowActions)
setRows ($_aRows=array())
setTableActions ($_oTableActions)
setTableConfig ($_oTableConfig)
setTableDataError ($_oTableDataError)
setTableName ($_sTableName)
setTableTemplates ($_oTableTools)
setTableTools ($_oTableTools)
setTplVars ($tplName, $config, $reset=FALSE)
set template variables (static and dynamic) array
Static Public Member Functions
static getInstance ($options=array())
get singelton instance object
Public Attributes
$_aColumns = array()
collection of table columns
$_aFooterCells = array()
collection of table footer cells
$_aRows = array()
collection of table rows
$_oTable = null
table db object container
$_oTableConfig
$_oTableDataError = null
table data error container object
$_oTableSession = null
table session container
$_oTableTools
$_sQuery = ""
db table SQL query string
$_sTableHashId = null
$_sTableId = null
table object container id
$_sTableIdPrefix = 'table_'
table object container id prefix string
$_tpls
$aNoRenderActions
Protected Member Functions
_buildEqualLikeWhere ($aFields, $searchData="", $conjunction="OR")
_buildTableQuery ()
apply tavle tools filter/sort parameter
_getDbTableColumns ($full=FALSE, $prependTableName=FALSE)
retrieve db table's column definitions
_loadDbData ()
_parseToolsParams ($aParams=NULL)
parse request's table tools parameters
_setTableHashId ($sTableHashId="")
create or set panel hash id
_setTableId ($sTableId="")
set table's element id
_setTableSession ($sTableHashId="", $bReset=TRUE)
create panel session object
getHash ()
get panel hash id
getId ()
get panel's element id
Protected Attributes
$_sTableName = ""
db table name string
Detailed Description
Definition at line 14 of file Table.php.
Constructor & Destructor Documentation
__construct ($options = array())
Definition at line 283 of file Table.php.
References __init().
{
         parent::__construct($options);
         $this->__init($options);
         return ($this);
     }
Member Function Documentation
__init ($options = array())
initialize default table configurations and object options
See Also
Contenido_Object::init()
Definition at line 240 of file Table.php.
References Contenido_Object_Abstract\_con(), Contenido_Object_Abstract\_getAllParams(), _parseToolsParams(), _setTableHashId(), configTable(), Contenido_Object_Abstract\getDb(), getHash(), getId(), getSession(), getTableConfig(), getTableTools(), setColumns(), setRowActions(), setTableConfig(), setTableName(), setTableTemplates(), and setTableTools().
Referenced by __construct().
{
         parent::__init();
         $aRequest                       = $this->_getAllParams();
         $this->_oTable                  = $this->getDb();
         if ( !isset($aRequest["PHPSESSID"]) || empty($aRequest["PHPSESSID"]) ) {
             unset( $aRequest["PHPSESSID"] );
         }
         if ( !isset($aRequest["hash"]) || empty($aRequest["hash"]) ) {
             $aRequest["hash"]           = $this->getHash();
         } else {
             $this->_setTableHashId($aRequest["hash"]);
         }
         $this->_oTableConfig["hash"]    = $aRequest["hash"]; // $this->getHash();
         $this->_oTableConfig["id"]      = $this->getId();
         $aNonTableToolsParams = $aRequest;
         foreach ((array)$this->getTableTools() as $key => $value) {
             if (array_key_exists( $key, $aRequest) ) {
                 unset($aNonTableToolsParams[$key]);
             }
         }
         $this->_oTableConfig["url"]     = $this->_con('sess')->url( 'main.php?'.http_build_query($aNonTableToolsParams) );
         $defaults = $this->getTableConfig();
         //$mergedOptions = array_merge_recursive( $defaults, $options );
         $mergedOptions = array_merge( $defaults, $options );
         $this->setTableConfig( $mergedOptions );
         $this->setTableTools( $options["oTableTools"] );
         $this->setColumns( $options["oColumnSets"] );
         $this->setTableTemplates($options["oTemplates"]);
         $this->setRowActions($options["oRowActions"]);
         $this->_parseToolsParams();
         if (isset($options["dbTableName"])) { $this->setTableName( trim($options["dbTableName"]) ); }
         $this->getSession();
         $this->configTable();
     }
_buildEqualLikeWhere ($aFields, $searchData = "", $conjunction = "OR") protected
Definition at line 738 of file Table.php.
References Contenido_Object_Abstract\getDb().
Referenced by _buildTableQuery().
{
         $searchData = trim($searchData);
         if ( empty($searchData) ) {
             return "";
         }
         $oDB            = $this->getDb();
         $aWheres        = array();
         $conjunction    = ($conjunction == "OR") ? "OR" : "AND";
         foreach ((array)$aFields as $key => $aField) {
             if ( !empty($aField["Collation"]) || ($aField["Type"] == 'timestamp') ) {
                 $op = "LIKE";
             } else {
                 $op = "=";
             }
             array_push(
                 $aWheres,
                 ("`".$aField["Field"]."`") .
                     (" ".$op." ") .
                 ("'".(($op == "LIKE") ? "%" : "").Contenido_Security::escapeDB($searchData, $oDB).(($op == "LIKE") ? "%" : "")."'")
             );
         }
         $glue = " ) ".$conjunction." ( ";
         $sWhere =  "( ".implode($glue, $aWheres)." )" . " " ;
         return $sWhere;
     }
_buildTableQuery () protected
apply tavle tools filter/sort parameter
Returns
Contenido_Plugin_GUI_Table
Definition at line 768 of file Table.php.
References _buildEqualLikeWhere(), _getDbTableColumns(), _parseToolsParams(), Contenido_Object_Abstract\getDb(), getTableName(), getTableTools(), and setQuery().
Referenced by getQuery().
{
         $this->_parseToolsParams();
         $sTableName = $this->getTableName();
         $sQuery     = "";
         if (!empty($sTableName)) {
             $oDB        = $this->getDb();
             $sQuery     = "SELECT * FROM `".Contenido_Security::escapeDB($sTableName, $oDB)."` ";
             $oTools     = $this->getTableTools(TRUE);
             $aFields    = $this->_getDbTableColumns(TRUE);
             if ( !empty($oTools->searchData) && empty($oTools->filterData) ) {
                 $oTools->filterCol = '*'; $oTools->filterData = trim($oTools->searchData);
             }
             if ( !empty($oTools->filterCol) && !empty($oTools->filterData) && array_key_exists($oTools->filterCol, $aFields) ) {
                 if ( ($oTools->filterCol != '*') ) {
                     if ( !empty($aFields[$oTools->filterCol]["Collation"]) || ($aFields[$oTools->filterCol]["Type"] == 'timestamp') ) {
                         $op = "LIKE";
                     } else {
                         $op = "=";
                     }
                     $sQuery     .= "WHERE" ." (".
                                         ("`".Contenido_Security::escapeDB($oTools->filterCol, $oDB)."`") ."".
                                    (" ".$op." ").
                                         ("'"."%".Contenido_Security::escapeDB($oTools->filterData, $oDB)."%"."'") .") " ;
                 } else {
                 }
             } else if ( ($oTools->filterCol == '*') && !empty($oTools->filterData) ) {
                     $sQuery     .= "WHERE" ." (". $this->_buildEqualLikeWhere($aFields, $oTools->filterData) . ") ";
             } else {
                 $sQuery     .= "WHERE" ." " ."1" ." ";
             }
             if ( ($oTools->onlyActive == 'true') ) {
                 $sQuery     .= "AND (`active`='1') ";
             }
             if ( !empty($oTools->orderField) && !empty($oTools->sortOrder) ) {
                 $sQuery     .= "ORDER BY ".
                                     ("`".Contenido_Security::escapeDB($oTools->orderField, $oDB)."`") . " " .
                                     (($oTools->sortOrder == 'asc') ? "ASC" : "DESC") . " ";
             }
             if ( !empty($oTools->page) && !empty($oTools->pageCount) && ($oTools->pageCount != 'all') ) {
                 $sCountQuery = str_replace("SELECT *", "SELECT count(`active`) AS `numRows`", $sQuery);
                 $oDB->query($sCountQuery);
                 while ( $oDB->next_record() ) {
                     $iRows = $oDB->f('numRows');
                 }
                 $oTools->pages = (int)($iRows / $oTools->pageCount) + ( (($iRows % $oTools->pageCount) > 0) ? 1 : 0);
                 $lStart = ( (int)$oTools->page - 1 ) * (int)$oTools->pageCount;
                 if ($oTools->page > $oTools->pageCount) {
                     $lStart = 0;
                 }
                 $sQuery     .= "LIMIT " . $lStart . ", " . (int)$oTools->pageCount;
             }
         }
         $this->setQuery($sQuery);
         return $this;
     }
_con ($varname, $varvalue = NULL) inherited
return/set a given contenido global parameter -> it is NOT recommended to set/override a global contenido parameter!
Parameters
string $varname
mixed $varvalue
Returns
mixed
Definition at line 238 of file Abstract.php.
References Contenido_Object_Abstract\__setConVar(), and Contenido_Object_Abstract\getConVars().
Referenced by Contenido_Plugin_GUI_Form\__init(), __init(), Contenido_Object_Abstract\_text(), Contenido_Plugin_GUI_Form\generateForm(), Contenido_Plugin_GUI_Form\generateFormAction(), Contenido_Plugin_GUI_Form\generateFormElementAction(), Contenido_Plugin_GUI_Form\generateFormToolsActions(), Contenido_Plugin_GUI\generateNavigationList(), generateTable(), generateTableAction(), generateTableToolsActions(), Contenido_Plugin_GUI\getFrameTemplate(), Contenido_Plugin_GUI\page_close(), and Contenido_Plugin_GUI\page_open().
{
         $aConVars = $this->getConVars();
         if ( $varvalue === NULL ) {
             return ((isset($aConVars[$varname])) ? $aConVars[$varname] : NULL);
         } else {
             $this->__setConVar($varname, $varvalue);
             return $this->_con($varname);
         }
     }
_getAllParams ($asObject = false) inherited
get all '$_REQUEST' parameters
Returns
array|stdClass
Definition at line 395 of file Abstract.php.
Referenced by Contenido_Plugin_GUI_Form\__init(), __init(), _parseToolsParams(), and Contenido_Plugin_GUI_Form\_parseToolsParams().
{
         return ($asObject) ? (object)$_REQUEST : (array)$_REQUEST;
     }
_getDbTableColumns ($full = FALSE, $prependTableName = FALSE) protected
retrieve db table's column definitions
Returns
Contenido_Plugin_GUI_Table
Definition at line 710 of file Table.php.
References Contenido_Object_Abstract\getDb(), and getTableName().
Referenced by _buildTableQuery().
{
         $sTableName = $this->getTableName();
         $aFields    = array();
         if (!empty($sTableName)) {
             $oDB = $this->getDb();
             $sQuery = "SHOW FULL COLUMNS FROM `".Contenido_Security::escapeDB($sTableName, $oDB)."`;";
             $oDB->query($sQuery);
             while ($oDB->next_record()) {
                 if ( $full ) {
                     $aFields[$oDB->f('Field')] = array(
                         "Field"         => (($prependTableName) ? $sTableName."." : "" ) .$oDB->f('Field'),
                         "Type"          => $oDB->f('Type'),
                         "Collation"     => $oDB->f('Collation'),
                         "Null"          => ($oDB->f('Null') == 'NO') ? FALSE : !!$oDB->f('Null'),
                         "Key"           => $oDB->f('Key'),
                         "Default"       => $oDB->f('Default'),
                         "Extra"         => $oDB->f('Extra'),
                         "Privileges"    => $oDB->f('Privileges'),
                         "Comment"       => $oDB->f('Comment'),
                     );
                 } else {
                     array_push($aFields, $oDB->f('Field'));
                 }
             }
         }
         return $aFields;
     }
_getTable ()
Returns
DB_Contenido $_oTable
Definition at line 1058 of file Table.php.
References $_oTable, and _setTable().
{
         if ( !($this->_oTable instanceof DB_Contenido) ) {
             $this->_setTable();
         }
         return $this->_oTable;
     }
_getTableDataError ()
Returns
Exception $_oTableDataError
Definition at line 1078 of file Table.php.
References $_oTableDataError.
{
         return $this->_oTableDataError;
     }
_html ($text, $domain = NULL, $quote_style = null, $charset = null, $double_encode = null, $mode = 0) inherited
get translated string converting special characters to html entities
string $text string $domain integer $quote_style [optional] Like htmlspecialchars, the optional second quote_style parameter lets you define what will be done with 'single' and "double" quotes. It takes on one of three constants with the default being ENT_COMPAT:
quote_style constants
Constant Name
Description
ENT_COMPAT
Will convert double-quotes and leave single-quotes alone.
ENT_QUOTES
Will convert both double and single quotes.
ENT_NOQUOTES
Will leave both double and single quotes unconverted.
Parameters
string $charset [optional]
Like htmlspecialchars, it takes an optional third argument charset which defines character set used in conversion. Presently, the ISO-8859-1 character set is used as the default.
&reference.strings.charsets;
Parameters
boolean $double_encode [optional]
When double_encode is turned off PHP will not encode existing html entities. The default is to convert everything.
Parameters
integer $mode [optional]
0 = using htmlentities() (default), 1 = using htmlspecialchars()
Returns
string
Definition at line 187 of file Abstract.php.
{
         return ($mode == 1) ? htmlspecialchars( i18n($text, $domain), $quote_style, $charsetl, $double_encode ) : htmlentities( i18n($text, $domain), $quote_style, $charsetl, $double_encode );
     }
_loadDbData () protected
Returns
ARRAY $aRows
Definition at line 990 of file Table.php.
References Contenido_Object_Abstract\getDb(), and getQuery().
Referenced by getRows().
{
         $aRows          = array();
         $oDB            = $this->getDb();
         $sSQLGetRows    = $this->getQuery();
         if ($sSQLGetRows) {
             $oDB->query($sSQLGetRows);
             while ( $oDB->next_record() ) {
                 if ( $asObject ) {
                     array_push($aRows, (object)$oDB->Record);
                 } else {
                     array_push($aRows, $oDB->Record);
                 }
             }
         }
         return ($aRows);
     }
_parseToolsParams ($aParams = NULL) protected
parse request's table tools parameters
Parameters
ARRAY $aParams
Returns
Contenido_Plugin_GUI_Table
Definition at line 832 of file Table.php.
References Contenido_Object_Abstract\_getAllParams(), getTableTools(), and setTableTools().
Referenced by __init(), and _buildTableQuery().
{
         $aParams    = ($aParams) ? $aParams : $this->_getAllParams();
         $aTools     = (array)$this->getTableTools();
         foreach ($aTools as $key => $value) {
             if ( array_key_exists($key, $aParams) && !empty($aParams[$key]) ) {
                 $aTools[$key] = trim($aParams[$key]);
             } else if ( array_key_exists($key, $aParams) ) {
                 $aTools[$key] = NULL;
             }
         }
         $this->setTableTools((object)$aTools);
         return $this;
     }
_setTable ($_oTable)
Parameters
DB_Contenido $_oTable
Returns
Contenido_Plugin_GUI_Table
Definition at line 1069 of file Table.php.
References _setTableSession(), and Contenido_Object_Abstract\getDb().
Referenced by _getTable().
{
         $this->_oTable = $this->getDb();
         $this->_setTableSession(NULL, FALSE);
         return $this;
     }
_setTableHashId ($sTableHashId = "") protected
create or set panel hash id
Parameters
STRING $sTableHashId
Returns
self
Definition at line 887 of file Table.php.
References $_sTableHashId.
Referenced by __init(), and getHash().
{
         if ( empty($sTableHashId) && empty($this->_sTableHashId) ) {
             // create new panel hash id
             $sHash = md5( uniqid(NULL, FALSE)."_".uniqid(NULL, TRUE) );
         } else if ( empty($sTableHashId) && !empty($this->_sTableHashId) ) {
             // apply previously set hash id
             $sHash = $this->_sTableHashId;
         } else {
             // set given hash id
             $sHash = $sTableHashId;
         }
         $this->_sTableHashId = $sHash;
         $this->_oTableConfig["hash"]  = $this->_sTableHashId;
         //$this->getSession();
         return $this;
     }
_setTableId ($sTableId = "") protected
set table's element id
Parameters
STRING $sTableId
Returns
Contenido_Plugin_GUI_Table
Definition at line 862 of file Table.php.
Referenced by getId().
{
         if (empty($sTableId)) {
             $sTableId = uniqid($this->_sTableIdPrefix, TRUE);
         }
         $this->_sTableId = str_replace(".", "_", $sTableId);
         return $this;
     }
_setTableSession ($sTableHashId = "", $bReset = TRUE) protected
create panel session object
Parameters
STRING $sTableHashId
BOOLEAN $bReset
Returns
void
Definition at line 921 of file Table.php.
References $_oTableSession, getHash(), getId(), getTableConfig(), and getTableTools().
Referenced by _setTable(), getSession(), setColumns(), setFooter(), setNoRenderActions(), setQuery(), setRowActions(), setRows(), setTableActions(), setTableConfig(), setTableDataError(), setTableName(), setTableTemplates(), and setTableTools().
{
         if (empty($sTableHashId)) {
             $sTableHashId = $this->getHash();
         }
         if ( (($this->_oTableSession === NULL) ) || $bReset) {
             $sNamespace = $this->_sTableIdPrefix . $sTableHashId;
             if ( !isset($_SESSION[$sNamespace]) ) {
                 $_SESSION[$sNamespace] = array();
             }
             $this->_oTableSession = $_SESSION[$sNamespace]; //new Zend_Session_Namespace($sNamespace);
             // $this->_oTableSession->setExpirationSeconds(300, 'accept_request');
             if ( !$this->_oTableSession["initialized"] ) {
                 $this->_oTableSession["sId"]                = $this->getId();
                 $this->_oTableSession["iRequestCount"]      = 0;
                 $this->_oTableSession["accept_request"]     = TRUE;
                 $this->_oTableSession["initialized"]        = TRUE;
             }
             if (!$bReset) {
                 //$this->_oTableSession["iRequestCount"]++;
             }
         }
         $this->_oTableSession["iRequestCount"]++;
         $this->_oTableSession["aTableConfig"]       = $this->getTableConfig();
         $this->_oTableSession["aTableTools"]        = $this->getTableTools();
         $_SESSION[$sNamespace] = $this->_oTableSession;
         return $this;
     }
_setting ($type, $name = null, $default = "") inherited
get Contenido effective CMS setting(s)
Parameters
string $type
string $name
string $default
Returns
string|array
Definition at line 223 of file Abstract.php.
{
         if ( empty($name) ) {
             return getEffectiveSettingsByType($type);
         }
         return getEffectiveSetting($type, $name, $default);
     }
_text ($text, $domain = NULL) inherited
get translated string
Parameters
string $text
string $domain
Returns
string
Definition at line 198 of file Abstract.php.
References Contenido_Object_Abstract\_con().
{
         $_mi18n = $this->_con("MI18N");
         $_string = $text;
         if ( is_array($_mi18n) && isset($_mi18n[$text]) ) {
             $_string = (string)$_mi18n[$text];
         } else
         if ( is_array($_mi18n) && is_array($_mi18n[$domain]) && isset($_mi18n[$domain][$text]) ) {
             $_string = (string)$_mi18n[$domain][$text];
         } else
         if ( ($this->_con("cnumber") !== NULL) && ( $this->_con("mi18nTranslator") !== NULL ) ) {
             $_string =  mi18n($text, $domain);
         } else {
             $_string = i18n($text, $domain);
         }
         return $_string;
     }
configTable ()
overridable method to initialize user's table configurations and object options
Definition at line 233 of file Table.php.
Referenced by __init().
{
     }
generate ($bReturn = TRUE)
Definition at line 688 of file Table.php.
References generateTable(), generateTableBottomPanel(), generateTableJS(), generateTableTopPanel(), and getTableConfig().
{
         $options = (object)$this->getTableConfig();
         $sHTML =
             (($options->showTopPanel) ? $this->generateTableTopPanel() : "").
             $this->generateTable() .
             (($options->showBottomPanel) ? $this->generateTableBottomPanel() : "") .
             (($options->generateJS) ? $this->generateTableJS($this->getTableConfig(TRUE)->oTemplates["javascript"]) : "");
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateTable ($bReturn = TRUE)
Definition at line 289 of file Table.php.
References $cfg, Contenido_Object_Abstract\_con(), generateTableAction(), Contenido_Object_Abstract\getCfg(), getColumns(), getFooter(), getRowActions(), getRows(), getTableConfig(), and Contenido_Object_Abstract\getTpl().
Referenced by generate().
{
         $sHTML              = "";
         $aRows              = array();
         $aData              = $this->getRows(TRUE);
         $aHTMLTableColumns  = $this->getColumns();
         $aHTMLTableFooter   = array();
         $oTpl               = $this->getTpl('basetable', TRUE);
         $cfg                = $this->getCfg();
         $sHTMLTableHeader = "";
         $sHTMLTableFooter = "";
         $sHTMLTableColumnGroup = "";
         if ($this->getTableConfig(TRUE)->showHeaderRow) {
             $aColumns = array();
             $hasPredefinedActionColumn  = FALSE;
             $sActionCell                = "<td class=\"_rowaction_ headerbordercell\">".i18n("actions")."</td>";
             $sActionColumn              = "<column class=\"_rowaction_\" />";
             $showTableAction            = $this->getTableConfig(TRUE)->showRowActions;
             $actionPos                  = $this->getTableConfig(TRUE)->rowactions;
             foreach ($aHTMLTableColumns as $iColumn => $aColumn) {
                 if ($aColumn["field"]) {
                     $aColumns[] = $aColumn["field"];
                     $sHTMLTableHeader .= "<td class=\"".$aColumn["field"]." headerbordercell\">".$aColumn["title"]."</td>";
                     $sHTMLTableColumnGroup .= "<column class=\"".$aColumn["field"]."\" />";
                 } else {
                     $sHTMLTableHeader .= "<td class=\"col_".$iColumn." headerbordercell\">".$aColumn["title"]."</td>";
                     $sHTMLTableColumnGroup .= "<column class=\"col_".$iColumn."\" />";
                 }
             }
             if (!$hasPredefinedActionColumn && $showTableAction) {
                 $sHTMLTableHeader = ( (($actionPos == 'left') ||  ($actionPos == 'both')) ? $sActionCell : "" ) .
                     $sHTMLTableHeader . ( (($actionPos == 'right') ||  ($actionPos == 'both')) ? $sActionCell : "" );
                 $sHTMLTableColumnGroup = ( (($actionPos == 'left') ||  ($actionPos == 'both')) ? $sActionColumn : "" ) .
                     $sHTMLTableColumnGroup . ( (($actionPos == 'right') ||  ($actionPos == 'both')) ? $sActionColumn : "" );
             }
         }
         if ($this->getTableConfig(TRUE)->showFooterRow) {
             $aHTMLTableFooter   = $this->getFooter();
         }
         $oTpl->template->set('s', 'php_session_id',         $this->_con('sess')->id);
         $oTpl->template->set('s', 'URLBASE',                $this->getCfg()->path['contenido_fullhtml']);
         $oTpl->template->set('s', 'NOTIFICATION',           $sPageOutput);
         $oTpl->template->set('s', 'BROWSE',                 $sPageOutput);
         $oTpl->template->set('s', 'CLICK_ROW_NOTIFICATION', $sPageOutput);
         $oTpl->template->set('s', 'HEADERS',                $sHTMLTableHeader);
         $oTpl->template->set('s', 'FOOTERS',                $sHTMLTableFooter);
         $oTpl->template->set('s', 'COLUMNGROUP',            "<columns>".$sHTMLTableColumnGroup."</columns>");
         foreach ( $aData as $iData => $oRowData ) {
             $sCells                     = "";
             $hasPredefinedActionColumn  = FALSE;
             $sActionCell                = "<td class=\"actions bordercell\">" . "!ACTIONS_".$oRowData["id"]."!";
             $showTableAction            = $this->getTableConfig(TRUE)->showRowActions;
             $actionPos                  = $this->getTableConfig(TRUE)->rowactions;
             foreach ($aHTMLTableColumns as $iColumn => $aColumn) {
                 if ( $aColumn["field"] && ($aColumn["field"] != "_rowaction_") ) {
                     if ($aColumn["field"] == "lastchange") {
                         if ( !empty($oRowData[$aColumn["field"]]) ) {
                             $sCells .= "<td class=\"".$aColumn["field"]." bordercell\">".$oRowData[$aColumn["field"]]."</td>";
                         } else if ( !empty($oRowData["created"]) ) {
                             $sCells .= "<td class=\"".$aColumn["field"]." bordercell\">".$oRowData["created"]."</td>";
                         } else {
                             $sCells .= "<td class=\"".$aColumn["field"]." bordercell\"> - </td>";
                         }
                     } else if ($aColumn["field"] == "deadline") {
                         if ( !empty($oRowData[$aColumn["field"]]) ) {
                             $sCells .= "<td class=\"".$aColumn["field"]." bordercell\">".$oRowData[$aColumn["field"]]."</td>";
                         } else {
                             $sCells .= "<td class=\"".$aColumn["field"]." bordercell\"> - </td>";
                         }
                     } else {
                         $sCells .= "<td class=\"".$aColumn["field"]." bordercell\">".$oRowData[$aColumn["field"]]."</td>";
                     }
                 } else {
                     if ($aColumn["field"] == "_rowaction_") {
                         $sCells .= $sActionCell;
                         $hasPredefinedActionColumn = TRUE;
                     } else {
                         $sCells .= "<td class=\"col_".$iColumn." bordercell\">";
                     }
                     $sCells .= "</td>";
                 }
             }
             if (!$hasPredefinedActionColumn && $showTableAction) {
                 $sCells = ( (($actionPos == 'left') ||  ($actionPos == 'both')) ? $sActionCell."</td>" : "" ) .
                     $sCells . ( (($actionPos == 'right') ||  ($actionPos == 'both')) ? $sActionCell."</td>" : "" );
             }
             $aRows[] = $sCells;
         }
         foreach ($aRows as $iRow => $sRow) {
             $sActions = "";
             $sFormTitle = $aData[$iRow]["name"];
             $aActions = $this->getRowActions();
             foreach ($aActions as $key => $aAction) {
                 if ( !isset($aAction["static"]) ) { $aAction["static"] = array(); }
                 $aAction["static"]["ACTIONNAME"] = $key;
                 $aAction["static"]["ACTIONCLASS"] = "con_tableaction" . (($aData[$iRow]["active"] != 1) ? " inactive" : "") ;
                 $aAction["static"]["ROWID"] = $aData[$iRow]["id"];
                 $aAction["static"]["IDX"] = $iRow;
                 /*if ($aData[$iRow]["active"] == 1) {
                     $sActions .= "<a class=\"deactivate\" href=\"#deactivate\"><img src=\"images/online.gif\" border=\"0\" alt=\"[deactivate -".$sFormTitle."-]\" title=\"deactivate\" /></a> ";
                 } else {
                     $sActions .= "<a class=\"activate\" href=\"#activate\"><img src=\"images/offline.gif\" border=\"0\" alt=\"[activate -".$sFormTitle."-]\" title=\"activate\" /></a> ";
                 }*/
                 $sActions .= $this->generateTableAction($aAction);
             }
             //$sActions .= "<input type=\"hidden\" name=\"rowid[]\" value=\"".$aForms[$iRow]["id"]."\" />";
             $sRow = str_replace("!ACTIONS_".$aData[$iRow]["id"]."!", $sActions, $sRow);
             $oTpl->template->set('d', 'ROWID', "row_".$aData[$iRow]["id"]);
             $oTpl->template->set('d', 'CELLS', $sRow);
             if (($iRow % 2) == 0) {
                 $oTpl->template->set('d', 'CSS_CLASS', 'even');
             } else {
                 $oTpl->template->set('d', 'CSS_CLASS', 'odd');
             }
             $oTpl->template->next();
         }
         $sHTML .= $oTpl->template->generate( $this->getTableConfig(TRUE)->oTemplates["base"], TRUE );
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateTableAction ($oAction, $bReturn = TRUE)
Definition at line 420 of file Table.php.
References $action, $area, Contenido_Object_Abstract\_con(), Contenido_Object_Abstract\getTpl(), and Contenido_Object_Abstract\setTplVars().
Referenced by generateTable().
{
         if (is_array($oAction)) { $oAction = (object)$oAction; }
         $sHTML  = "";
         if ( !empty($oAction->template) ) {
             $accessGranted  = true;
             $area           = $this->_con('area');
             $action         = $this->_con('action');
             $plugin_name    = $this->_con('plugin_name');
             if ( defined('CON_FRAMEWORK') && !empty($plugin_name) && !empty($area) && !empty($action) ) {
                 // if we are in a plugin context, check for access permission...
                 $accessGranted = $this->_con('perm')->have_perm_area_action($area, $action);
             }
             $oActionTpl = $this->getTpl('rowaction', TRUE);
             $this->setTplVars('rowaction', $oAction);
             if ( !$accessGranted && !empty($oAction->_template) ) {
                 $sHTML .= $oActionTpl->template->generate($oAction->_template, TRUE);
             } else {
                 $sHTML .= $oActionTpl->template->generate($oAction->template, TRUE);
             }
         }
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateTableBottomPanel ($bReturn = TRUE)
Definition at line 663 of file Table.php.
References generateTableTools(), and getTableConfig().
Referenced by generate().
{
         $sHTML  = "";
         $sHTML .= $this->generateTableTools( $this->getTableConfig(TRUE)->oTemplates["bottom"] );
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateTableJS ($sJSTemplate = "", $bReturn = TRUE)
Definition at line 673 of file Table.php.
References getTableConfig(), Contenido_Object_Abstract\getTpl(), and Contenido_Object_Abstract\setTplVars().
Referenced by generate().
{
         $this->getTpl("tableJS", TRUE);
         $this->setTplVars("tableJS", array(
             "static" => array(
                 "TABLE_CONFIG_JSON" => json_encode($this->getTableConfig(TRUE)),
             )
         ));
         $sJS = $this->getTpl("tableJS")->template->generate($sJSTemplate, TRUE);
         if ($bReturn) {
             return ($sJS);
         }
         echo ($sJS);
         return ($this);
     }
generateTableTools ($sTemplate = "", $bReturn = TRUE)
Definition at line 448 of file Table.php.
References generateTableToolsActions(), generateTableToolsFilter(), generateTableToolsOnlyActive(), generateTableToolsPageCount(), generateTableToolsPagination(), generateTableToolsSort(), getTableConfig(), getTableTools(), and Contenido_Object_Abstract\getTpl().
Referenced by generateTableBottomPanel(), and generateTableTopPanel().
{
         $sHTML  = "";
         if ( !empty($sTemplate) ) {
             $config     = $this->getTableConfig(TRUE);
             $tools      = $this->getTableTools(TRUE);
             $oToolTpl   = $this->getTpl('tabletools', TRUE);
             $seperator  = " || ";
             $sFilterOutput      = (!$config->filter)        ? null : $this->generateTableToolsFilter($tools->filterCol, $tools->filterData);
             $sOnlyActiveOutput  = (!$config->onlyActive)    ? null : $this->generateTableToolsOnlyActive($tools->onlyActive);
             $sRowsPerPageOutput = (!$config->pageCount)     ? null : $this->generateTableToolsPageCount($tools->pageCount, $tools->pageCountOptions);
             $sPaginationOutput  = (!$config->pagination)    ? null : $this->generateTableToolsPagination($tools->page, $tools->pageCount);
             $sSortOptionsOutput = (!$config->sort)          ? null : $this->generateTableToolsSort($tools->orderField, $tools->sortOrder);
             $sSearchOutput      = (!$config->search)        ? null : null; // ""; // $this->generateTableToolsSearch($tools->searchData);
             $sTableActions      = (!$config->tableActions)  ? null : $this->generateTableToolsActions();
             $oToolTpl->template->set('s', 'TABLE_TOOLS_CLASSNAMES',     "tableTools");
             $oToolTpl->template->set('s', 'TABLE_TOOLS_PAGINATION',     trim(implode($seperator, array(
                 $sPaginationOutput, $sRowsPerPageOutput,
             )) , " |"));
             $oToolTpl->template->set('s', 'TABLE_TOOLS_PAGEBROWSER',    $sPaginationOutput);
             $oToolTpl->template->set('s', 'TABLE_TOOLS_PAGECOUNT',      $sRowsPerPageOutput);
             $oToolTpl->template->set('s', 'TABLE_TOOLS_FILTER',         trim(implode($seperator, array(
                 $sOnlyActiveOutput, $sFilterOutput, $sSearchOutput,
             )) , " |"));
             $oToolTpl->template->set('s', 'TABLE_TOOLS_SEARCH',         $sSearchOutput);
             $oToolTpl->template->set('s', 'TABLE_TOOLS_COLUMNFILTER',   $sFilterOutput);
             $oToolTpl->template->set('s', 'TABLE_TOOLS_ONLYACTIVE',     $sOnlyActiveOutput);
             $oToolTpl->template->set('s', 'TABLE_TOOLS_ACTIONS',        $sTableActions);
             $oToolTpl->template->set('s', 'TABLE_TOOLS_SORT',           trim(implode(" || ", array(
                 $sSortOptionsOutput,
             )) , " |"));
             $oToolTpl->template->set('s', 'NOTIFICATION',               ""); //$sToolNotificationOutput);
             $sHTML .= $oToolTpl->template->generate( $sTemplate,    true );
         }
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateTableToolsActions ($bReturn = TRUE)
Definition at line 618 of file Table.php.
References Contenido_Object_Abstract\_con(), and Contenido_Object_Abstract\getCfg().
Referenced by generateTableTools().
{
         $sHTML  = "";
         $sTableActions                  = '<ul class="tableActionList">'.
             ( ( $this->_con('perm')->have_perm_area_action($this->_con('plugin_name'), "createform") ) ? '<li class="tableActionItem">'. sprintf(
                 $this->getCfg()->templates[$this->_con('plugin_name').'_multilink_3Frames'],
                 "con_link_icon createfunction",
                 "left_bottom",
                 $this->_con('sess')->url("main.php?". "area=".$this->_con('plugin_name') ."&". "frame="."2" ."&". "actionarea="."forms" ."&". "action="."createform"),
                 "right_top",
                 $this->_con('sess')->url("main.php?". "area=".$this->_con('plugin_name') ."&". "frame="."3" ."&". "actionarea="."forms" ."&". "action="."createform"),
                 "right_bottom",
                 $this->_con('sess')->url("main.php?". "area=".$this->_con('plugin_name') ."&". "frame="."4" ."&". "actionarea="."forms" ."&". "action="."createform"),
                 i18n("create new form")
             ) ."</li>" : "" ) .
         /*( ( $perm->have_perm_area_action($plugin_name, "reportoverview") ) ? '<li class="tableActionItem">'. sprintf(
                 $cfg['templates'][$plugin_name.'_multilink_3Frames'],
                 "con_link_icon openoverview",
                 "left_bottom",
                 $sess->url("main.php?". "area=".$oPlugin->_con('plugin_name') ."&". "frame="."2" ."&". "actionarea="."reports" ."&". "action="."reportoverview"),
                 "right_top",
                 $sess->url("main.php?". "area=".$oPlugin->_con('plugin_name') ."&". "frame="."3" ."&". "actionarea="."reports" ."&". "action="."reportoverview"),
                 "right_bottom",
                 $sess->url("main.php?". "area=".$oPlugin->_con('plugin_name') ."&". "frame="."4" ."&". "actionarea="."reports" ."&". "action="."reportoverview"),
                 i18n("form reports")
             ) ."</li>" : "" ) .*/
         "</ul>";
         $sHTML .= $sTableActions;
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateTableToolsFilter ($sFilterCol = "", $sFilterData = "", $bReturn = TRUE)
Definition at line 575 of file Table.php.
References getTableConfig().
Referenced by generateTableTools().
{
         $sHTML  = "";
         $aHTMLTableColumns = $this->getTableConfig(TRUE)->oColumnSets;
         $sSearchOutput  = i18n("filter column") . ': ' . '<span class="input">'.
             '<select id="eFilterCol" name="filterCol" class="text_medium" onchange="/*artSort(this)*/">'.
                 '<option value="*"'.( ($sFilterCol == '*') ? ' selected="selected"' : '' ).'>' . i18n("any") . "</option>";
                 foreach ((array)$aHTMLTableColumns as $key => $aColumn) {
                     if ( !isset($aColumn['filter']) || ($aColumn['filter'] === TRUE) ) {
                         $sSearchOutput  .= '<option value="'.$aColumn['field'].'"'.
                             ( ($sFilterCol == $aColumn['field']) ? ' selected="selected"' : '' ) .
                         '>'.$aColumn['title'].'</option>';
                     }
                 }
                 $sSearchOutput  .= '</select>'.
             '</span>' . ' &nbsp; ';
             $sSearchOutput  .= i18n("query") . ': ' . '<span class="input">'.
                 '<input type="text" id="eFilterData" name="filterData" class="text_medium" onchange="/*artSort(this)*/" value="'.$sFilterData.'">'.
             '</span>' .
             //(' ' . Contenido_Plugin_GUI::submitImage('filter', 'images/but_preview.gif') ) . ( (empty($sFilterData)) ? "" :
             //(' ' . Contenido_Plugin_GUI::submitImage('filtercancel', 'images/but_cancel.gif') ) ) .
         "";
         $sHTML .= $sSearchOutput;
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateTableToolsNotification ($sMessage = "", $bReturn = TRUE)
Definition at line 604 of file Table.php.
{
         $sHTML  = "";
         if ( !empty($sTemplate) ) {
             $sToolNotificationOutput        = '';
             //...
             $sHTML .= $sToolNotificationOutput;
         }
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateTableToolsOnlyActive ($sOnlyActive = "", $bReturn = TRUE)
Definition at line 538 of file Table.php.
Referenced by generateTableTools().
{
         $sHTML  = "";
         $sOnlyActiveOutput  = i18n("show only active forms").' '. '<span class="input">'.
             '<input type="checkbox" value="true" id="eOnlyActive" name="onlyActive" class="text_medium" onchange="/*artSort(this)*/"'.( ($sOnlyActive == 'true') ? ' checked="checked"' : '' ).'>';
         '</span>';
         $sHTML .= $sOnlyActiveOutput;
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateTableToolsPageCount ($sRowsPerPage = "", $aOptionsRowsPerPage = array(), $bReturn = TRUE)
Definition at line 519 of file Table.php.
Referenced by generateTableTools().
{
         $sHTML  = "";
         $sRowsPerPageOutput = i18n("show").' '. '<span class="input">'.
             '<select id="eRowsPerPage" name="pageCount" class="text_medium text_right" onchange="/*artSort(this)*/">';
             foreach ((array)$aOptionsRowsPerPage as $key => $value) {
                 $sRowsPerPageOutput .= '<option style="text-align: right;" value="'.$value.'"'.
                     ( ($sRowsPerPage == $value) ? ' selected="selected"' : '' ) .
                 '>'.$value.'</option>';
             }
             $sRowsPerPageOutput .= '</select>'. i18n("rows per page") .
         '</span>';
         $sHTML .= $sRowsPerPageOutput;
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateTableToolsPagination ($sPageStart = "", $sRowsPerPage = 15, $bReturn = TRUE)
Definition at line 551 of file Table.php.
References getRows().
Referenced by generateTableTools().
{
         $sHTML  = "";
         $iRows  = count($this->getRows(TRUE));
         $sPageBrowserOutput = i18n("go to page").' '. '<span class="input">'.
             '<select id="ePageStart" name="page" class="text_medium text_right" onchange="/*artSort(this)*/">';
             if ( !is_numeric($sRowsPerPage) ) {
                 $pages = 1;
             } else {
                 $pages = (int)(($iRows) / (int)$sRowsPerPage)    +   ( ( ($iRows % (int)$sRowsPerPage) > 0) ? 1 : 0 );
             }
             for ($i = 1; $i <= $pages; $i++) {
                 $sPageBrowserOutput .= '<option value="'.($i).'"'.
                     ( ($sPageStart == ($i-1)) ? ' selected="selected"' : '' ) .
                 '>'.$i.'</option>';
             }
         $sPageBrowserOutput .= '</select> '; // . Contenido_Plugin_GUI::submitImage('browse', 'images/submit.gif');
         $sHTML .= $sPageBrowserOutput;
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateTableToolsSort ($sOrderField = "", $sSortOrder = "asc", $bReturn = TRUE)
Definition at line 493 of file Table.php.
References getTableConfig().
Referenced by generateTableTools().
{
         $sHTML  = "";
         $aHTMLTableColumns = $this->getTableConfig(TRUE)->oColumnSets;
         $sSortOptionsOutput = i18n("sort").' '. '<span class="input">'.
             '<select id="eSortOrder" name="sortOrder" class="text_medium" onchange="/*artSort(this)*/">'.
                 '<option value="asc"'.  ( ($sSortOrder == 'asc') ? ' selected="selected"' : '' ) .'>'.i18n("ascending"). '</option>'.
                 '<option value="desc"'. ( ($sSortOrder != 'asc') ? ' selected="selected"' : '' ) .'>'.i18n("descending").'</option>'.
             '</select> '.i18n("by"). ' '.
             '<select id="eOrderField" name="orderField" class="text_medium" onchange="/*artSort(this)*/">';
             foreach ((array)$aHTMLTableColumns as $key => $aColumn) {
                 if ( !isset($aColumn['sort']) || ($aColumn['sort'] === TRUE) ) {
                     $sSortOptionsOutput .= '<option value="'.$aColumn['field'].'"'.
                         ( ($sOrderField == $aColumn['field']) ? ' selected="selected"' : '' ) .
                     '>'.$aColumn['title'].'</option>';
                 }
             }
             $sSortOptionsOutput .= '</select>'.
         '</span>';
         $sHTML .= $sSortOptionsOutput;
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateTableTopPanel ($bReturn = TRUE)
Definition at line 653 of file Table.php.
References generateTableTools(), and getTableConfig().
Referenced by generate().
{
         $sHTML  = "";
         $sHTML .= $this->generateTableTools( $this->getTableConfig(TRUE)->oTemplates["top"] );
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
getAuth () inherited
return Contenido authorization object
Returns
stdClass|array
Definition at line 458 of file Abstract.php.
References Contenido_Object_Abstract\getConfig().
Referenced by Contenido_Object_Abstract\getAuthId().
{
         return (object)$this->getConfig()->auth->auth;
     }
getAuthId () inherited
return Contenido authorized user id
Returns
string
Definition at line 466 of file Abstract.php.
References Contenido_Object_Abstract\getAuth().
Referenced by Contenido_Object_Abstract\isAuthNobody().
{
         return $this->getAuth()->uid;
     }
getCfg () inherited
return Contenido configuration
Returns
stdClass|array
Definition at line 442 of file Abstract.php.
References Contenido_Object_Abstract\getConfig().
Referenced by Contenido_Plugin_GUI_Form\generateForm(), Contenido_Plugin_GUI_Form\generateFormToolsActions(), generateTable(), generateTableToolsActions(), Contenido_Plugin_GUI\page_close(), and Contenido_Plugin_GUI\page_open().
{
         return (object)$this->getConfig()->cfg;
     }
getCfgClient () inherited
return Contenido client configuration
Returns
stdClass|array
Definition at line 450 of file Abstract.php.
References Contenido_Object_Abstract\getConfig().
{
         return (object)$this->getConfig()->cfgClient;
     }
getColumns ()
Returns
ARRAY $_aColumns
Definition at line 954 of file Table.php.
References $_aColumns.
Referenced by generateTable().
{
         return (array)$this->_aColumns;
     }
getConfig () inherited
return configuration settings array
Returns
stdClass|array
Definition at line 253 of file Abstract.php.
References Contenido_Object_Abstract\$_config.
Referenced by Contenido_Plugin_GUI\generateNavigationList(), Contenido_Object_Abstract\getAuth(), Contenido_Object_Abstract\getCfg(), Contenido_Object_Abstract\getCfgClient(), Contenido_Plugin_GUI\getFrameTemplate(), Contenido_Object_Abstract\isDebug(), and Contenido_Plugin_GUI_Form\validateFormElements().
{
         return (object)$this->_config;
     }
getDb ($db = null) inherited
get (current) instance of DB_Contenido
Parameters
DB_Contenido $db
Returns
DB_Contenido
Definition at line 357 of file Abstract.php.
Referenced by Contenido_Plugin_GUI_Form\__init(), __init(), _buildEqualLikeWhere(), Contenido_Plugin_GUI_Form\_buildEqualLikeWhere(), Contenido_Plugin_GUI_Form\_buildQuery(), _buildTableQuery(), Contenido_Plugin_GUI_Form\_getDbFormColumns(), _getDbTableColumns(), _loadDbData(), Contenido_Plugin_GUI_Form\_loadDbData(), Contenido_Plugin_GUI_Form\_setForm(), and _setTable().
{
         if ( $this->_db instanceof DB_Contenido ) {
             return ($this->_db);
         }
         if ($db instanceof DB_Contenido) {
             $this->_db = $db;
         } else {
             $this->_db = new DB_Contenido;
         }
         return ($this->_db);
     }
getFooter ()
Returns
ARRAY $_aFooterCells
Definition at line 972 of file Table.php.
References $_aFooterCells.
Referenced by generateTable().
{
         return (array)$this->_aFooterCells;
     }
getHash () protected
get panel hash id
Returns
STRING
Definition at line 874 of file Table.php.
References $_sTableHashId, and _setTableHashId().
Referenced by __init(), and _setTableSession().
{
         if (empty($this->_sTableHashId)) {
             $this->_setTableHashId();
         }
         return $this->_sTableHashId;
     }
getId () protected
get panel's element id
Returns
STRING
Definition at line 850 of file Table.php.
References $_sTableId, and _setTableId().
Referenced by __init(), and _setTableSession().
{
         if (empty($this->_sTableId)) {
             $this->_setTableId();
         }
         return $this->_sTableId;
     }
static getInstance ($options = array()) static inherited
get singelton instance object
Parameters
array | stdClass $config
Returns
Contenido_Object_Abstract
Definition at line 102 of file Abstract.php.
{
         if ( self::$_instance === NULL ) {
             self::$_instance = new self( $options );
         }
         return self::$_instance;
     }
getNoRenderActions ()
Returns
ARRAY $aNoRenderActions
Definition at line 1189 of file Table.php.
References $aNoRenderActions.
{
         return $this->aNoRenderActions;
     }
getOptions () inherited
get object options array
Returns
array|stdClass
Definition at line 374 of file Abstract.php.
References Contenido_Object_Abstract\$_options.
Referenced by Contenido_Object_Abstract\setOptions().
{
         return (array)$this->_options;
     }
getQuery ()
Returns
STRING $_sQuery
Definition at line 1035 of file Table.php.
References $_sQuery, _buildTableQuery(), and getTableName().
Referenced by _loadDbData().
{
         $tableName = trim($this->getTableName());
         if ( !empty( $tableName ) ) {
             $this->_buildTableQuery();
         } else {
             return (FALSE);
         }
         return $this->_sQuery;
     }
getRowActions ($asObject = FALSE)
Returns
OBJECT $_oTableConfig["oRowActions"]
Definition at line 1206 of file Table.php.
Referenced by generateTable().
{
         return ($asObject) ? (object)$this->_oTableConfig["oRowActions"] : (array)$this->_oTableConfig["oRowActions"];
     }
getRows ($forceDbReload = FALSE)
Returns
ARRAY $_aRows
Definition at line 1010 of file Table.php.
References $_aRows, _loadDbData(), getTableName(), and setRows().
Referenced by generateTable(), and generateTableToolsPagination().
{
         if ( !is_array($this->_aRows) || (count($this->_aRows) == 0) || $forceDbReload ) {
             $tableName = trim($this->getTableName());
             if ( !empty($tableName) ) {
                 $aRows = $this->_loadDbData();
                 $this->setRows($aRows);
             }
         }
         return (array)$this->_aRows;
     }
getSession ()
get session
Returns
Zend_Session_Namespace
Definition at line 908 of file Table.php.
References $_oTableSession, and _setTableSession().
Referenced by __init().
{
         if ($this->_oTableSession === NULL) {
             $this->_setTableSession(NULL, FALSE);
         }
         return $this->_oTableSession;
     }
getTableActions ($asObject = FALSE)
Returns
OBJECT $_oTableConfig["oRowActions"]
Definition at line 1129 of file Table.php.
{
         return ($asObject) ? (object)$this->_oTableConfig["oTableActions"] : (array)$this->_oTableConfig["oTableActions"] ;
     }
getTableConfig ($asObject = FALSE)
Returns
ARRAY $_oTableConfig
Definition at line 1112 of file Table.php.
References $_oTableConfig.
Referenced by __init(), _setTableSession(), generate(), generateTable(), generateTableBottomPanel(), generateTableJS(), generateTableTools(), generateTableToolsFilter(), generateTableToolsSort(), generateTableTopPanel(), and getTableToolsURL().
{
         return ($asObject) ? (object)$this->_oTableConfig : (array)$this->_oTableConfig;
     }
getTableName ()
Returns
the $_sTableName
Definition at line 1095 of file Table.php.
References $_sTableName.
Referenced by _buildTableQuery(), _getDbTableColumns(), getQuery(), and getRows().
{
         return $this->_sTableName;
     }
getTableTemplates ($asObject = FALSE)
Returns
OBJECT $_oTableTools
Definition at line 1146 of file Table.php.
{
         return ($asObject) ? (object)$this->_oTableConfig["oTemplates"] : (array)$this->_oTableConfig["oTemplates"];
     }
getTableTools ($asObject = FALSE)
Returns
OBJECT $_oTableTools
Definition at line 1163 of file Table.php.
References $_oTableTools.
Referenced by __init(), _buildTableQuery(), _parseToolsParams(), _setTableSession(), and generateTableTools().
{
         return ($asObject) ? (object)$this->_oTableTools : (array)$this->_oTableTools;
     }
getTableToolsURL ()
Returns
STRING $_oTableToolsURL
Definition at line 1181 of file Table.php.
References $cfg, and getTableConfig().
{
         $cfg = $this->getTableConfig();
         return $cfg["url"];
     }
getTpl ($tplName = NULL, $reset = FALSE) inherited
generate and get template objects
Parameters
string $tplName
boolean $reset
Returns
Template
Definition at line 275 of file Abstract.php.
Referenced by Contenido_Plugin_GUI_Form\generateForm(), Contenido_Plugin_GUI_Form\generateFormAction(), Contenido_Plugin_GUI_Form\generateFormElementAction(), Contenido_Plugin_GUI_Form\generateFormElements(), Contenido_Plugin_GUI_Form\generateFormJS(), Contenido_Plugin_GUI_Form\generateFormTools(), Contenido_Plugin_GUI\generateNavigationList(), generateTable(), generateTableAction(), generateTableJS(), generateTableTools(), Contenido_Plugin_GUI\getFrameTemplate(), Contenido_Plugin_GUI\page_close(), Contenido_Plugin_GUI\page_open(), Contenido_Object_Abstract\setTpl(), and Contenido_Object_Abstract\setTplVars().
{
         if ( empty($tplName) ) {
             $tplName = 'default';
         }
         if ( ( !isset($this->_tpls[$tplName]) || !isset($this->_tpls[$tplName]->template) || !($this->_tpls[$tplName]->template instanceof Template) ) || $reset) {
             $oTemplate = new Template();
             $oTemplate->reset();
             $this->_tpls[$tplName] = (object)array(
                 "name"      =>  $tplName,
                 "template"  =>  $oTemplate,
                 "content"   =>  '',
                 "static"    =>  array(),
                 "dynamic"   =>  array(),
             );
         }
         if ($reset) {
             $this->_tpls[$tplName]->template->reset();
         }
         return $this->_tpls[$tplName];
     }
isAuthNobody () inherited
determine if current Contenido user is not an authorized user
Returns
boolean
Definition at line 474 of file Abstract.php.
References Contenido_Object_Abstract\getAuthId().
{
         return $this->getAuthId() == "nobody";
     }
isDebug () inherited
determine if debug mode is set to true
Returns
boolean
Definition at line 482 of file Abstract.php.
References Contenido_Object_Abstract\getConfig().
{
         return $this->getConfig()->debug === true;
     }
setColumns ($_aColumns = array())
Parameters
ARRAY $_aColumns
Returns
Contenido_Plugin_GUI_Table
Definition at line 962 of file Table.php.
References $_aColumns, and _setTableSession().
Referenced by __init().
{
         $this->_aColumns = $_aColumns;
         $this->_oTableConfig["oColumnSets"] =& $this->_aColumns;
         $this->_setTableSession(NULL, FALSE);
         return $this;
     }
setFooter ($_aFooterCells = array())
Parameters
ARRAY $_aFooterCells
Returns
Contenido_Plugin_GUI_Table
Definition at line 980 of file Table.php.
References $_aFooterCells, and _setTableSession().
{
         $this->_aFooterCells = $_aFooterCells;
         $this->_oTableConfig["oFooterCells"] =& $this->_aFooterCells;
         $this->_setTableSession(NULL, FALSE);
         return $this;
     }
setNoRenderActions ($aNoRenderActions)
Parameters
ARRAY $aNoRenderActions
Returns
Contenido_Plugin_GUI_Table
Definition at line 1197 of file Table.php.
References $aNoRenderActions, and _setTableSession().
{
         $this->aNoRenderActions = $aNoRenderActions;
         $this->_setTableSession(NULL, FALSE);
         return $this;
     }
setOptions ($options) inherited
set object options array
Parameters
array | stdClass $options
Returns
Contenido_Object_Abstract
Definition at line 384 of file Abstract.php.
References Contenido_Object_Abstract\getOptions().
Referenced by Contenido_Object_Abstract\__init().
{
         $aOptions = $this->getOptions();
         $this->_options = array_merge_recursive($aOptions, (array)$options);
         return ($this);
     }
setQuery ($_sQuery)
Parameters
STRING $_sQuery
Returns
Contenido_Plugin_GUI_Table
Definition at line 1049 of file Table.php.
References $_sQuery, and _setTableSession().
Referenced by _buildTableQuery().
{
         $this->_sQuery = $_sQuery;
         $this->_setTableSession(NULL, FALSE);
         return $this;
     }
setRowActions ($_oRowActions)
Parameters
ARRAY $_oRowActions
Returns
Contenido_Plugin_GUI_Table
Definition at line 1214 of file Table.php.
References _setTableSession().
Referenced by __init().
{
         $this->_oTableConfig["oRowActions"] = $_oRowActions;
         $this->_setTableSession(NULL, FALSE);
         return $this;
     }
setRows ($_aRows = array())
Parameters
ARRAY $_aRows
Returns
Contenido_Plugin_GUI_Table
Definition at line 1025 of file Table.php.
References $_aRows, and _setTableSession().
Referenced by getRows().
{
         $this->_aRows = $_aRows;
         $this->_oTableConfig["data"] =& $this->_aRows;
         $this->_setTableSession(NULL, FALSE);
         return $this;
     }
setTableActions ($_oTableActions)
Parameters
ARRAY $_oTableActions
Returns
Contenido_Plugin_GUI_Table
Definition at line 1137 of file Table.php.
References _setTableSession().
{
         $this->_oTableConfig["oTableActions"] = $_oTableActions;
         $this->_setTableSession(NULL, FALSE);
         return $this;
     }
setTableConfig ($_oTableConfig)
Parameters
ARRAY $_oTableConfig
Returns
Contenido_Plugin_GUI_Table
Definition at line 1120 of file Table.php.
References $_oTableConfig, and _setTableSession().
Referenced by __init().
{
         $this->_oTableConfig = $_oTableConfig;
         $this->_setTableSession(NULL, FALSE);
         return $this;
     }
setTableDataError ($_oTableDataError)
Parameters
Exception $_oTableDataError
Returns
Contenido_Plugin_GUI_Table
Definition at line 1086 of file Table.php.
References $_oTableDataError, and _setTableSession().
{
         $this->_oTableDataError = $_oTableDataError;
         $this->_setTableSession(NULL, FALSE);
         return $this;
     }
setTableName ($_sTableName)
Parameters
STRING $_sTableName
Returns
Contenido_Plugin_GUI_Table
Definition at line 1103 of file Table.php.
References $_sTableName, and _setTableSession().
Referenced by __init().
{
         $this->_sTableName = $_sTableName;
         $this->_setTableSession(NULL, FALSE);
         return $this;
     }
setTableTemplates ($_oTableTools)
Parameters
ARRAY $_oTableTools
Returns
Contenido_Plugin_GUI_Table
Definition at line 1154 of file Table.php.
References $_oTableTools, and _setTableSession().
Referenced by __init().
{
         $this->_oTableConfig["oTemplates"] = $_oTableTools;
         $this->_setTableSession(NULL, FALSE);
         return $this;
     }
setTableTools ($_oTableTools)
Parameters
ARRAY $_oTableTools
Returns
Contenido_Plugin_GUI_Table
Definition at line 1171 of file Table.php.
References $_oTableTools, and _setTableSession().
Referenced by __init(), and _parseToolsParams().
{
         $this->_oTableTools = $_oTableTools;
         $this->_oTableConfig["oTableTools"] =& $this->_oTableTools;
         $this->_setTableSession(NULL, FALSE);
         return $this;
     }
setTplVars ($tplName, $config, $reset = FALSE) inherited
set template variables (static and dynamic) array
Parameters
string $tplName
array | stdClass $config
boolean $reset
Returns
Template
Definition at line 328 of file Abstract.php.
References Contenido_Object_Abstract\getTpl().
Referenced by Contenido_Plugin_GUI_Form\generateFormAction(), Contenido_Plugin_GUI_Form\generateFormJS(), Contenido_Plugin_GUI\generateNavigationList(), generateTableAction(), generateTableJS(), Contenido_Plugin_GUI\page_close(), Contenido_Plugin_GUI\page_open(), and Contenido_Object_Abstract\setTpl().
{
         if ( empty($tplName) ) {
             $tplName = 'default';
         }
         if ( is_array($config) ) { $config = (object)$config; }
         $oTemplate = $this->getTpl( $tplName, $reset );
         if ( is_array($config->static) || is_object($config->static) ) {
             foreach ((array)$config->static as $needle => $replacement) {
                 $oTemplate->template->set("s", $needle, $replacement);
             }
         }
         if ( is_array($config->dynamic) || is_object($config->dynamic) ) {
             foreach ((array)$config->dynamic as $idx => $vars) {
                 $oTemplate->template->set("d", "BLOCKINDEX", $replacement);
                 foreach ((array)$vars as $needle => $replacement) {
                     $oTemplate->template->set("d", $needle, $replacement);
                 }
                 $oTemplate->template->next();
             }
         }
         return ($oTemplate->template);
     }
Member Data Documentation
ARRAY $_aColumns = array()
collection of table columns
Definition at line 38 of file Table.php.
Referenced by getColumns(), and setColumns().
ARRAY $_aFooterCells = array()
collection of table footer cells
Definition at line 44 of file Table.php.
Referenced by getFooter(), and setFooter().
ARRAY $_aRows = array()
collection of table rows
Definition at line 50 of file Table.php.
Referenced by getRows(), and setRows().
DB_Contenido $_oTable = null
table db object container
Definition at line 68 of file Table.php.
Referenced by _getTable().
$_oTableConfig
Definition at line 87 of file Table.php.
Referenced by getTableConfig(), and setTableConfig().
Exception $_oTableDataError = null
table data error container object
Definition at line 74 of file Table.php.
Referenced by _getTableDataError(), and setTableDataError().
ARRAY $_oTableSession = null
table session container
Definition at line 80 of file Table.php.
Referenced by _setTableSession(), and getSession().
$_oTableTools
Initial value:
= array(
        "filterCol"         => '',
        "filterData"        => '',
        "page"              => 1,
        "pages"             => 1,
        "pageCount"         => 25,
        "searchData"        => '',
        "orderField"        => '',
        "sortOrder"         => '',
        "onlyActive"        => 0,
    )
Definition at line 201 of file Table.php.
Referenced by getTableTools(), setTableTemplates(), and setTableTools().
STRING $_sQuery = ""
db table SQL query string
Definition at line 56 of file Table.php.
Referenced by getQuery(), and setQuery().
$_sTableHashId = null
Definition at line 32 of file Table.php.
Referenced by _setTableHashId(), and getHash().
STRING $_sTableId = null
table object container id
Definition at line 20 of file Table.php.
Referenced by getId().
STRING $_sTableIdPrefix = 'table_'
table object container id prefix string
Definition at line 26 of file Table.php.
STRING $_sTableName = "" protected
db table name string
Definition at line 62 of file Table.php.
Referenced by getTableName(), and setTableName().
$_tpls inherited
Initial value:
= array(
    )
Definition at line 56 of file Abstract.php.
$aNoRenderActions
Initial value:
= array(
        "reset",
        "update",
        "config",
        "prepare",
        "get",
        "put",
        "delete",
        "getsessionhash",
        "getsessiondata",
        "gettabledata"
    )
Definition at line 217 of file Table.php.
Referenced by getNoRenderActions(), and setNoRenderActions().
The documentation for this class was generated from the following file:
/Users/bba/resources/php/contenido/Plugin_and_Extension_API__PEA/branches/4.8/classes/Contenido/Plugin/GUI/Table.php