Contenido PEA: Contenido_Plugin_GUI Class Reference
Contenido_Plugin_GUI Class Reference
Public Member Functions
__construct ($options=array())
contructor
_con ($varname, $varvalue=NULL)
return/set a given contenido global parameter -> it is NOT recommended to set/override a global contenido parameter!
_getAllParams ($asObject=false)
get all '$_REQUEST' parameters
_html ($text, $domain=NULL, $quote_style=null, $charset=null, $double_encode=null, $mode=0)
get translated string converting special characters to html entities
_setting ($type, $name=null, $default="")
get Contenido effective CMS setting(s)
_text ($text, $domain=NULL)
get translated string
generateNavigationList ($navitems=array(), $navname="navlist", $navitemname="navitem", $level=0)
getAuth ()
return Contenido authorization object
getAuthId ()
return Contenido authorized user id
getCfg ()
return Contenido configuration
getCfgClient ()
return Contenido client configuration
getConfig ()
return configuration settings array
getDb ($db=null)
get (current) instance of DB_Contenido
getFrame ($tplName, $reset=FALSE)
get frame specific template object
getFrameTemplate ($tplName, $reset=FALSE)
create plugin specific template object
getOptions ()
get object options array
getTpl ($tplName=NULL, $reset=FALSE)
generate and get template objects
isAuthNobody ()
determine if current Contenido user is not an authorized user
isDebug ()
determine if debug mode is set to true
page_close ($html="")
generate page closing HTML depending on configuarion in plugin's config file
page_open ($param)
generate page opening HTML depending on configuarion in plugin's config file
setOptions ($options)
set object options array
setTplVars ($tplName, $config, $reset=FALSE)
set template variables (static and dynamic) array
Static Public Member Functions
static button ($inputName, $type, $value="", $onclick="", $inputId="", $inputClass="", $bReturn=true, $style=0, $imgSrc=NULL)
create <input type="button,submit,reset,image"> (style=0) or respectivly <button></button> (style=1, $type!='image') tag
static getInstance ($options=array())
get singelton instance object
static messageBox ($level, $message, $bReturn=true, $style=0)
New message style without tables - please use this.
static submitImage ($inputName, $imgSrc, $inputId="", $inputClass="", $value=1, $bReturn=true, $style=0)
create image <input> tag
Public Attributes
$_tpls
Protected Member Functions
__init ($params=null)
init (Contenido) object global parameters
Private Attributes
$_frames
Static Private Attributes
static $_instance = null
Detailed Description
Definition at line 13 of file GUI.php.
Constructor & Destructor Documentation
__construct ($options = array())
contructor
Parameters
mixed $options
Returns
Contenido_Plugin_GUI
Definition at line 38 of file GUI.php.
{
         parent::__construct( $options );
         return ($this);
     }
Member Function Documentation
__init ($params = null) protected inherited
init (Contenido) object global parameters
Parameters
mixed $params
Returns
Contenido_Object_Abstract
Definition at line 115 of file Abstract.php.
References Contenido_Object_Abstract\__initOptions(), Contenido_Object_Abstract\getConVars(), Contenido_Object_Abstract\setConfig(), and Contenido_Object_Abstract\setOptions().
Referenced by Contenido_Object_Abstract\__construct().
{
         // basic object setup
         $oGlobals = (object)$this->getConVars( true );
         $this->setConfig( $oGlobals );
         $this->_config->tmplPath    =   getEffectiveSetting('global', 'templatepath', 'templates/');
         $this->_config->debug       =   (getEffectiveSetting('global', 'debug', 'false') == 'false') ? false : true;
         if ($this->_config->db instanceof DB_Contenido) {
             $this->_db =& $this->_config->db;
         }
         $this->setOptions($params);
         if (method_exists($this, "__initOptions")) {
             $this->__initOptions( $params );
         }
         return ($this);
     }
_con ($varname, $varvalue = NULL) inherited
return/set a given contenido global parameter -> it is NOT recommended to set/override a global contenido parameter!
Parameters
string $varname
mixed $varvalue
Returns
mixed
Definition at line 238 of file Abstract.php.
References Contenido_Object_Abstract\__setConVar(), and Contenido_Object_Abstract\getConVars().
Referenced by Contenido_Plugin_GUI_Form\__init(), Contenido_Plugin_GUI_Table\__init(), Contenido_Object_Abstract\_text(), Contenido_Plugin_GUI_Form\generateForm(), Contenido_Plugin_GUI_Form\generateFormAction(), Contenido_Plugin_GUI_Form\generateFormElementAction(), Contenido_Plugin_GUI_Form\generateFormToolsActions(), generateNavigationList(), Contenido_Plugin_GUI_Table\generateTable(), Contenido_Plugin_GUI_Table\generateTableAction(), Contenido_Plugin_GUI_Table\generateTableToolsActions(), getFrameTemplate(), page_close(), and page_open().
{
         $aConVars = $this->getConVars();
         if ( $varvalue === NULL ) {
             return ((isset($aConVars[$varname])) ? $aConVars[$varname] : NULL);
         } else {
             $this->__setConVar($varname, $varvalue);
             return $this->_con($varname);
         }
     }
_getAllParams ($asObject = false) inherited
get all '$_REQUEST' parameters
Returns
array|stdClass
Definition at line 395 of file Abstract.php.
Referenced by Contenido_Plugin_GUI_Form\__init(), Contenido_Plugin_GUI_Table\__init(), Contenido_Plugin_GUI_Table\_parseToolsParams(), and Contenido_Plugin_GUI_Form\_parseToolsParams().
{
         return ($asObject) ? (object)$_REQUEST : (array)$_REQUEST;
     }
_html ($text, $domain = NULL, $quote_style = null, $charset = null, $double_encode = null, $mode = 0) inherited
get translated string converting special characters to html entities
string $text string $domain integer $quote_style [optional] Like htmlspecialchars, the optional second quote_style parameter lets you define what will be done with 'single' and "double" quotes. It takes on one of three constants with the default being ENT_COMPAT:
quote_style constants
Constant Name
Description
ENT_COMPAT
Will convert double-quotes and leave single-quotes alone.
ENT_QUOTES
Will convert both double and single quotes.
ENT_NOQUOTES
Will leave both double and single quotes unconverted.
Parameters
string $charset [optional]
Like htmlspecialchars, it takes an optional third argument charset which defines character set used in conversion. Presently, the ISO-8859-1 character set is used as the default.
&reference.strings.charsets;
Parameters
boolean $double_encode [optional]
When double_encode is turned off PHP will not encode existing html entities. The default is to convert everything.
Parameters
integer $mode [optional]
0 = using htmlentities() (default), 1 = using htmlspecialchars()
Returns
string
Definition at line 187 of file Abstract.php.
{
         return ($mode == 1) ? htmlspecialchars( i18n($text, $domain), $quote_style, $charsetl, $double_encode ) : htmlentities( i18n($text, $domain), $quote_style, $charsetl, $double_encode );
     }
_setting ($type, $name = null, $default = "") inherited
get Contenido effective CMS setting(s)
Parameters
string $type
string $name
string $default
Returns
string|array
Definition at line 223 of file Abstract.php.
{
         if ( empty($name) ) {
             return getEffectiveSettingsByType($type);
         }
         return getEffectiveSetting($type, $name, $default);
     }
_text ($text, $domain = NULL) inherited
get translated string
Parameters
string $text
string $domain
Returns
string
Definition at line 198 of file Abstract.php.
References Contenido_Object_Abstract\_con().
{
         $_mi18n = $this->_con("MI18N");
         $_string = $text;
         if ( is_array($_mi18n) && isset($_mi18n[$text]) ) {
             $_string = (string)$_mi18n[$text];
         } else
         if ( is_array($_mi18n) && is_array($_mi18n[$domain]) && isset($_mi18n[$domain][$text]) ) {
             $_string = (string)$_mi18n[$domain][$text];
         } else
         if ( ($this->_con("cnumber") !== NULL) && ( $this->_con("mi18nTranslator") !== NULL ) ) {
             $_string =  mi18n($text, $domain);
         } else {
             $_string = i18n($text, $domain);
         }
         return $_string;
     }
static button ($inputName, $type, $value = "", $onclick = "", $inputId = "", $inputClass = "", $bReturn = true, $style = 0, $imgSrc = NULL) static
create <input type="button,submit,reset,image"> (style=0) or respectivly <button></button> (style=1, $type!='image') tag
Definition at line 322 of file GUI.php.
{
         $sHTML = "";
         $types = array('button', 'submit', 'reset', 'image');
         $type = (in_array(strtolower($type), $types)) ? strtolower($type) : "button";
         if ( ($style == 1) && ($type != 'image') ) {
             $sHTML .= sprintf(
                 '<button id="%s" class="%s" name="%s" />%s</button>',
                 $inputId,
                 $inputClass,
                 $inputName,
                 $value
             );
         } else {
             $sHTML .= sprintf(
                 '<input type="%s" id="%s" class="%s" name="%s" value="%s" %s />',
                 $type,
                 $inputId,
                 $inputClass,
                 $inputName,
                 (($type == 'image') ? 'src="'.$imgSrc.'"' : ''),
                 $value
             );
         }
         if ($bReturn) {
             return $sHTML;
         }
         echo $sHTML;
     }
generateNavigationList ($navitems = array(), $navname = "navlist", $navitemname = "navitem", $level = 0)
Definition at line 221 of file GUI.php.
References $sess, Contenido_Object_Abstract\_con(), Contenido_Object_Abstract\getConfig(), Contenido_Object_Abstract\getTpl(), and Contenido_Object_Abstract\setTplVars().
{
         $nav_name       = (empty($navname)) ? "navlist" : $navname;
         $navitem_name   = (empty($navitemname)) ? "navitem" : $navitemname;
         $level          = ($level) ? (int)$level : 0;
         $sess           = $this->_con('sess');
         $plugin_name    = $this->_con('plugin_name');
         $template_name  = $nav_name.'_level_'.$level;
         $oTemplate      = $this->getTpl($template_name, true);
         $statics        = array(
             "NAV_LIST_ID"           => (($level > 0) ? "sub".$nav_name : $nav_name ),
             "NAV_LIST_CLASSNAMES"   => $nav_name." ".$template_name." ".(($level > 0) ? "sub".$nav_name : "" ),
         );
         $dynamics       = array();
         $html           = "";
         if ( !empty( $this->getConfig()->cfg['templates'][$plugin_name.'_'.$nav_name] ) ) {
             $oTemplate->content = $this->getConfig()->cfg['templates'][$plugin_name.'_'.$nav_name];
         }
         foreach ((array)$navitems as $key => $navitem) {
             //echo "<pre>".print_r($navitem, true)."</pre>";
             $aTplItem = array(
                 "NAV_ITEM_ID"           => "" .$navitem_name."_".$key. "",
                 "NAV_ITEM_CLASSNAMES"   => $navitem_name. " " .$navitem_name."_".$key. "",
                 "NAV_ITEM_CONTENT"      => ""
             );
             if ( !empty($navitem["hrefstr"]) && isset($navitem["frames"]) && is_array($navitem["frames"]) ) {
                 if (count($navitem["frames"]) == 3) {
                     $sItem = sprintf(
                         $navitem["hrefstr"],
                         $navitem["classname"],
                         'left_bottom',
                         $sess->url("main.php?area=$plugin_name&frame=2".$navitem["frames"]['left_bottom'].""),
                         'right_top',
                         $sess->url("main.php?area=$plugin_name&frame=3".$navitem["frames"]['right_top'].""),
                         'right_bottom',
                         $sess->url("main.php?area=$plugin_name&frame=4".$navitem["frames"]['right_bottom'].""),
                         i18n($navitem["label"])
                     );
                     $aTplItem["NAV_ITEM_CONTENT"] .= $sItem;
                 }
                 if (count($navitem["frames"]) == 2) {
                     $sItem = sprintf(
                         $navitem["hrefstr"],
                         $navitem["classname"],
                         'right_top',
                         $sess->url("main.php?area=$plugin_name&frame=3".$navitem["frames"]['right_top'].""),
                         'right_bottom',
                         $sess->url("main.php?area=$plugin_name&frame=4".$navitem["frames"]['right_bottom'].""),
                         i18n($navitem["label"])
                     );
                     $aTplItem["NAV_ITEM_CONTENT"] .= $sItem;
                 }
             } else if ( !empty($navitem["hrefstr"]) && isset($navitem["parameters"]) && is_array($navitem["parameters"]) ) {
                     $sItem = vsprintf(
                         $navitem["hrefstr"],
                         $navitem["parameters"]
                     );
                     $aTplItem["NAV_ITEM_CONTENT"] .= $sItem;
             } else if ( !empty($navitem["hrefstr"]) ) {
                     $aTplItem["NAV_ITEM_CONTENT"] .= $navitem["hrefstr"];
             }
             if ( isset($navitem["subitems"]) && is_array($navitem["subitems"]) ) {
                 $aTplItem["NAV_ITEM_CONTENT"] .= $this->generateNavigationList(
                     $navitem["subitems"],
                     $nav_name,
                     $navitem_name,
                     $level+1
                 );
             }
             array_push($dynamics, $aTplItem);
         }
         $vars = (object)array("static" => $statics, "dynamic" => $dynamics);
         $this->setTplVars($template_name, $vars);
         $oTemplate      = $this->getTpl($template_name);
         $html .= $oTemplate->template->generate($oTemplate->content, true);
         return ($html);
     }
getAuth () inherited
return Contenido authorization object
Returns
stdClass|array
Definition at line 458 of file Abstract.php.
References Contenido_Object_Abstract\getConfig().
Referenced by Contenido_Object_Abstract\getAuthId().
{
         return (object)$this->getConfig()->auth->auth;
     }
getAuthId () inherited
return Contenido authorized user id
Returns
string
Definition at line 466 of file Abstract.php.
References Contenido_Object_Abstract\getAuth().
Referenced by Contenido_Object_Abstract\isAuthNobody().
{
         return $this->getAuth()->uid;
     }
getCfg () inherited
return Contenido configuration
Returns
stdClass|array
Definition at line 442 of file Abstract.php.
References Contenido_Object_Abstract\getConfig().
Referenced by Contenido_Plugin_GUI_Form\generateForm(), Contenido_Plugin_GUI_Form\generateFormToolsActions(), Contenido_Plugin_GUI_Table\generateTable(), Contenido_Plugin_GUI_Table\generateTableToolsActions(), page_close(), and page_open().
{
         return (object)$this->getConfig()->cfg;
     }
getCfgClient () inherited
return Contenido client configuration
Returns
stdClass|array
Definition at line 450 of file Abstract.php.
References Contenido_Object_Abstract\getConfig().
{
         return (object)$this->getConfig()->cfgClient;
     }
getConfig () inherited
return configuration settings array
Returns
stdClass|array
Definition at line 253 of file Abstract.php.
References Contenido_Object_Abstract\$_config.
Referenced by generateNavigationList(), Contenido_Object_Abstract\getAuth(), Contenido_Object_Abstract\getCfg(), Contenido_Object_Abstract\getCfgClient(), getFrameTemplate(), Contenido_Object_Abstract\isDebug(), and Contenido_Plugin_GUI_Form\validateFormElements().
{
         return (object)$this->_config;
     }
getDb ($db = null) inherited
get (current) instance of DB_Contenido
Parameters
DB_Contenido $db
Returns
DB_Contenido
Definition at line 357 of file Abstract.php.
Referenced by Contenido_Plugin_GUI_Form\__init(), Contenido_Plugin_GUI_Table\__init(), Contenido_Plugin_GUI_Table\_buildEqualLikeWhere(), Contenido_Plugin_GUI_Form\_buildEqualLikeWhere(), Contenido_Plugin_GUI_Form\_buildQuery(), Contenido_Plugin_GUI_Table\_buildTableQuery(), Contenido_Plugin_GUI_Form\_getDbFormColumns(), Contenido_Plugin_GUI_Table\_getDbTableColumns(), Contenido_Plugin_GUI_Table\_loadDbData(), Contenido_Plugin_GUI_Form\_loadDbData(), Contenido_Plugin_GUI_Form\_setForm(), and Contenido_Plugin_GUI_Table\_setTable().
{
         if ( $this->_db instanceof DB_Contenido ) {
             return ($this->_db);
         }
         if ($db instanceof DB_Contenido) {
             $this->_db = $db;
         } else {
             $this->_db = new DB_Contenido;
         }
         return ($this->_db);
     }
getFrame ($tplName, $reset = FALSE)
get frame specific template object
Parameters
string $tplName
booloean $reset
Returns
stdClass|NULL
Definition at line 63 of file GUI.php.
References getFrameTemplate().
{
         if ( in_array($tplName, $this->_frames) ) {
             return $this->getFrameTemplate( 'frame_'.$tplName, $reset );
         }
         return NULL;
     }
getFrameTemplate ($tplName, $reset = FALSE)
create plugin specific template object
Parameters
string $tplName
booloean $reset
Returns
stdClass
Definition at line 77 of file GUI.php.
References Contenido_Object_Abstract\_con(), Contenido_Object_Abstract\getConfig(), and Contenido_Object_Abstract\getTpl().
Referenced by getFrame().
{
         $oTemplate  = $this->getTpl($tplName, $reset);
         if ( !empty( $this->getConfig()->cfg['templates'][$this->_con('plugin_name').'_'.$tplName] ) ) {
             $oTemplate->content = $this->getConfig()->cfg['templates'][$this->_con('plugin_name').'_'.$tplName];
         }
         return $oTemplate;
     }
static getInstance ($options = array()) static
get singelton instance object
Parameters
array | stdClass $config
Returns
Contenido_Plugin_GUI
Definition at line 49 of file GUI.php.
{
         if ( self::$_instance === NULL ) {
             self::$_instance = new self( $options );
         }
         return self::$_instance;
     }
getOptions () inherited
get object options array
Returns
array|stdClass
Definition at line 374 of file Abstract.php.
References Contenido_Object_Abstract\$_options.
Referenced by Contenido_Object_Abstract\setOptions().
{
         return (array)$this->_options;
     }
getTpl ($tplName = NULL, $reset = FALSE) inherited
generate and get template objects
Parameters
string $tplName
boolean $reset
Returns
Template
Definition at line 275 of file Abstract.php.
Referenced by Contenido_Plugin_GUI_Form\generateForm(), Contenido_Plugin_GUI_Form\generateFormAction(), Contenido_Plugin_GUI_Form\generateFormElementAction(), Contenido_Plugin_GUI_Form\generateFormElements(), Contenido_Plugin_GUI_Form\generateFormJS(), Contenido_Plugin_GUI_Form\generateFormTools(), generateNavigationList(), Contenido_Plugin_GUI_Table\generateTable(), Contenido_Plugin_GUI_Table\generateTableAction(), Contenido_Plugin_GUI_Table\generateTableJS(), Contenido_Plugin_GUI_Table\generateTableTools(), getFrameTemplate(), page_close(), page_open(), Contenido_Object_Abstract\setTpl(), and Contenido_Object_Abstract\setTplVars().
{
         if ( empty($tplName) ) {
             $tplName = 'default';
         }
         if ( ( !isset($this->_tpls[$tplName]) || !isset($this->_tpls[$tplName]->template) || !($this->_tpls[$tplName]->template instanceof Template) ) || $reset) {
             $oTemplate = new Template();
             $oTemplate->reset();
             $this->_tpls[$tplName] = (object)array(
                 "name"      =>  $tplName,
                 "template"  =>  $oTemplate,
                 "content"   =>  '',
                 "static"    =>  array(),
                 "dynamic"   =>  array(),
             );
         }
         if ($reset) {
             $this->_tpls[$tplName]->template->reset();
         }
         return $this->_tpls[$tplName];
     }
isAuthNobody () inherited
determine if current Contenido user is not an authorized user
Returns
boolean
Definition at line 474 of file Abstract.php.
References Contenido_Object_Abstract\getAuthId().
{
         return $this->getAuthId() == "nobody";
     }
isDebug () inherited
determine if debug mode is set to true
Returns
boolean
Definition at line 482 of file Abstract.php.
References Contenido_Object_Abstract\getConfig().
{
         return $this->getConfig()->debug === true;
     }
static messageBox ($level, $message, $bReturn = true, $style = 0) static
New message style without tables - please use this.
Definition at line 354 of file GUI.php.
References $cfg.
{
         global $cfg, $auth;
         if ( ($level == 'debug') && ($auth->auth["perm"] != 'sysadmin') && ($auth->auth["perm"] != 'admin') ) {
             return '';
         }
         $mid = uniqid();
         switch ($level) {
             case "error":
                 $head = i18n('Error');
                 $head_class = 'alertbox_error';
                 $frameColor = $cfg["color"]["notify_error"];
                 $imgPath = $cfg["path"]["contenido_fullhtml"].$cfg["path"]["images"]."icon_fatalerror.gif";
             break;
             case "warning":
                 $head = i18n('Warning');
                 $head_class = 'alertbox_warning';
                 $bgColor = $cfg["color"]["notify_warning"];
                 $imgPath = $cfg["path"]["contenido_fullhtml"].$cfg["path"]["images"]."icon_warning.gif";
             break;
             case "info":
                 $head = i18n('Info');
                 $head_class = 'alertbox_info';
                 $message = '<span style="color:#435d06">'.$message.'</span>';
                 $bgColor = $cfg["color"]["notify_info"];
                 $imgPath = $cfg["path"]["contenido_fullhtml"].$cfg["path"]["images"]."but_ok.gif";
             break;
             case "debug":
                 $head = i18n('Debug') . " <span style=\"font-weight: normal;\">(" .date("Y-m-d H:i:s"). ")</span>";
                 $head_class = 'alertbox_debug';
                 $message = '<span style="color:#435d06"><pre>'.$message.'</pre></span>';
                 $bgColor = $cfg["color"]["notify_warning"];
                 $imgPath = $cfg["path"]["contenido_fullhtml"].$cfg["path"]["images"]."icon_construction.gif";
             break;
             case "help":
                 $head = i18n('Help');
                 $head_class = 'alertbox_help';
                 $message = '<span style="color:#435d06">'.$message.'</span>';
                 $bgColor = $cfg["color"]["notify"];
                 $imgPath = $cfg["path"]["contenido_fullhtml"].$cfg["path"]["images"]."but_help.gif";
             break;
             default:
                 $head = i18n('Notification');
                 $head_class = 'alertbox_notification';
                 $message = '<span style="color:#435d06">'.$message.'</span>';
                 $bgColor = $cfg["color"]["notify"];
                 $imgPath = $cfg["path"]["contenido_fullhtml"].$cfg["path"]["images"]."but_ok.gif";
             break;
         }
         if ($style == 1) {
             // Box on login page
             $messageBox =
                 '<div class="alertbox '.$head_class.'_color" id="contenido_'.$level.'_'.$mid.'" style="border-top:0px;">' .
                     '<h1 class="alertbox_head ' . $head_class . '">' . $head . '</h1>' .
                     '<div class="alertbox_message">' . $message . '</div>' .
                 '</div>';
         } else {
             // Simple box
             $messageBox =
                 '<div class="alertbox_line '.$head_class.'_color" id="contenido_'.$level.'_'.$mid.'">' .
                     '<h1 class=" alertbox_head ' . $head_class . ' '.$head_class.'_color">' . $head . '</h1>' .
                     '<div class="alertbox_message '.$head_class.'_color">' . $message . '</div>' .
                 '</div>';
         }
         if ($bReturn) {
             return $messageBox;
         }
         echo $messageBox;
     }
page_close ($html = "")
generate page closing HTML depending on configuarion in plugin's config file
Parameters
array $param
array $param
Definition at line 203 of file GUI.php.
References Contenido_Object_Abstract\_con(), Contenido_Object_Abstract\getCfg(), Contenido_Object_Abstract\getTpl(), and Contenido_Object_Abstract\setTplVars().
{
         $plugin_name    = $this->_con("plugin_name");
         $sTplName       = "plugin_page";
         $oTemplate      = $this->getTpl($sTplName, TRUE);
         $html           = $this->getCfg()->templates[$plugin_name."_pageprintlink"];
         if ( empty($html) ) {
             $config = (object)array("static" => array("FOOTER_HTML" => ""));
         } else  {
             $config = (object)array("static" => array("FOOTER_HTML" => $html));
         }
         $this->setTplVars($sTplName, $config);
         $sHTML = $oTemplate->template->generate(
             $this->getCfg()->templates[$plugin_name."_footer"],
             TRUE
         );
         return ( $sHTML );
     }
page_open ($param)
generate page opening HTML depending on configuarion in plugin's config file
Parameters
array $param
string HTML
Definition at line 91 of file GUI.php.
References Contenido_Object_Abstract\_con(), Contenido_Object_Abstract\getCfg(), Contenido_Object_Abstract\getTpl(), and Contenido_Object_Abstract\setTplVars().
{
         $plugin_name    = $this->_con("plugin_name");
         $sTplName       = "plugin_page";
         $oTemplate      = $this->getTpl($sTplName, TRUE);
         //$sPagePrintLink   = $this->getCfg()->templates[$plugin_name."_pageprintlink"];
         $config = (object)array("static"    => array(), "dynamic"   => array());
         if ( !isset($param["page_title"]) || empty($param["page_title"]) ) {
             $config->static["PLUGIN_PAGE_TITLE"]    = "";
         } else  {
             $config->static["PLUGIN_PAGE_TITLE"]    = $param["page_title"];
         }
         if (    !isset($param["page_header_html"]) || empty($param["page_header_html"]) ) {
             $config->static["HEADER_HTML"]  = "";
         } else  {
             $config->static["HEADER_HTML"]  = $param["page_header_html"];
         }
         if (    !isset($param["body_onload"]) || empty($param["body_onload"])   ) {
             $config->static["BODY_ONLOAD"]  = "";
         } else  {
             $config->static["BODY_ONLOAD"]  = $param["body_onload"];
         }
         //echo "<pre>".print_r($param["js"], TRUE)."</pre>";
         //echo "<pre>".print_r($param["css"], TRUE)."</pre>";
         $js = "";
         foreach ((array)$param["js"] as $key => $jsScriptFile) {
             $checkFile = substr( $jsScriptFile, 0, (strpos($jsScriptFile, "?") !== false) ? strpos($jsScriptFile, "?") : strlen($jsScriptFile));
             //echo "<pre>".print_r($this->getCfg()->plugins[$plugin_name].$jsScriptFile, TRUE)."</pre>";
             if ( is_readable($this->getCfg()->path['contenido'].$checkFile) ) {
                 // is it a contenido JS file?
                 $js .= sprintf(
                     '<script id="%s" type="text/javascript" src="%s"></script>',
                     $key,
                     $jsScriptFile
                 );
             } else if ( is_readable($this->getCfg()->plugins[$plugin_name].$checkFile) ) {
                 // is it a plugin JS file?
                 $js .= sprintf(
                     '<script id="%s" type="text/javascript" src="%s"></script>',
                     $key,
                     $this->getCfg()->plugins[$plugin_name."_path"].$jsScriptFile
                 );
             } else if ( (strpos($jsScriptFile, "http") !== FALSE) || (strpos($jsScriptFile, "/") !== FALSE)) {
                 // is it an external JS file?
                 $js .= sprintf(
                     '<script id="%s" type="text/javascript" src="%s"></script>',
                     $key,
                     $jsScriptFile
                 );
             } else if ( !empty($jsScriptFile) ) {
                 // is it a JS source code?
                 $js .= sprintf(
                     '<script id="%s" type="text/javascript">%s</script>',
                     $key,
                     $jsScriptFile
                 );
             }
         }
         $config->static["JS_PLUGIN"]        = $js;
         $config->static["JS_CONTENIDO"]     = "";
         $css = "";
         foreach ((array)$param["css"] as $key => $cssSourceFile) {
             $checkFile = substr( $cssSourceFile, 0, (strpos($cssSourceFile, "?") !== false) ? strpos($cssSourceFile, "?") : strlen($cssSourceFile));
             if ( is_readable($this->getCfg()->path['contenido'].$checkFile) ) {
                 // is it a contenido css file?
                 $css .= sprintf(
                     '<link id="%s" rel="stylesheet" type="text/css" href="%s" />',
                     $key,
                     $cssSourceFile
                 );
             } else if ( is_readable($this->getCfg()->plugins[$plugin_name].$checkFile) ) {
                 // is it a plugin css file?
                 $css .= sprintf(
                     '<link id="%s" rel="stylesheet" type="text/css" href="%s" />',
                     $key,
                     $this->getCfg()->plugins[$plugin_name."_path"].$cssSourceFile
                 );
             } else if ( (strpos($cssSourceFile, "http") !== FALSE) || (strpos($cssSourceFile, "/") !== FALSE)) {
                 // is it an external css file?
                 $css .= sprintf(
                     '<link id="%s" rel="stylesheet" type="text/css" href="%s" />',
                     $key,
                     $cssSourceFile
                 );
             } else if ( !empty($cssSourceFile) ) {
                 // is it a css source code?
                 $css .= sprintf(
                     '<style id="%s">%s</style>',
                     $key,
                     $cssSourceFile
                 );
             }
         }
         $config->static["CSS_PLUGIN"]       = $css;
         $config->static["CSS_CONTENIDO"]    = "";
         $this->setTplVars($sTplName, $config);
         $sHTML = $oTemplate->template->generate(
             $this->getCfg()->templates[$plugin_name."_header"],
             TRUE
         );
         return ( $sHTML );
     }
setOptions ($options) inherited
set object options array
Parameters
array | stdClass $options
Returns
Contenido_Object_Abstract
Definition at line 384 of file Abstract.php.
References Contenido_Object_Abstract\getOptions().
Referenced by Contenido_Object_Abstract\__init().
{
         $aOptions = $this->getOptions();
         $this->_options = array_merge_recursive($aOptions, (array)$options);
         return ($this);
     }
setTplVars ($tplName, $config, $reset = FALSE) inherited
set template variables (static and dynamic) array
Parameters
string $tplName
array | stdClass $config
boolean $reset
Returns
Template
Definition at line 328 of file Abstract.php.
References Contenido_Object_Abstract\getTpl().
Referenced by Contenido_Plugin_GUI_Form\generateFormAction(), Contenido_Plugin_GUI_Form\generateFormJS(), generateNavigationList(), Contenido_Plugin_GUI_Table\generateTableAction(), Contenido_Plugin_GUI_Table\generateTableJS(), page_close(), page_open(), and Contenido_Object_Abstract\setTpl().
{
         if ( empty($tplName) ) {
             $tplName = 'default';
         }
         if ( is_array($config) ) { $config = (object)$config; }
         $oTemplate = $this->getTpl( $tplName, $reset );
         if ( is_array($config->static) || is_object($config->static) ) {
             foreach ((array)$config->static as $needle => $replacement) {
                 $oTemplate->template->set("s", $needle, $replacement);
             }
         }
         if ( is_array($config->dynamic) || is_object($config->dynamic) ) {
             foreach ((array)$config->dynamic as $idx => $vars) {
                 $oTemplate->template->set("d", "BLOCKINDEX", $replacement);
                 foreach ((array)$vars as $needle => $replacement) {
                     $oTemplate->template->set("d", $needle, $replacement);
                 }
                 $oTemplate->template->next();
             }
         }
         return ($oTemplate->template);
     }
static submitImage ($inputName, $imgSrc, $inputId = "", $inputClass = "", $value = 1, $bReturn = true, $style = 0) static
create image <input> tag
Definition at line 302 of file GUI.php.
{
         $sHTML = "";
         $sHTML .= sprintf(
             '<input type="%s" id="%s" class="%s" name="%s" src="%s" value="%s" />',
             'image',
             $inputId,
             $inputClass,
             $inputName,
             $imgSrc,
             $value
         );
         if ($bReturn) {
             return $sHTML;
         }
         echo $sHTML;
     }
Member Data Documentation
$_frames private
Initial value:
= array(
        "left_top",
        "left_bottom",
        "right_top",
        "right_bottom"
    )
Definition at line 19 of file GUI.php.
$_instance = null static private
Definition at line 30 of file GUI.php.
$_tpls inherited
Initial value:
= array(
    )
Definition at line 56 of file Abstract.php.
The documentation for this class was generated from the following file:
/Users/bba/resources/php/contenido/Plugin_and_Extension_API__PEA/branches/4.8/classes/Contenido/Plugin/GUI.php