Contenido PEA: Contenido_Object_Base Class Reference
Contenido_Object_Base Class Reference
Public Member Functions
__construct ($options=array())
_con ($varname, $varvalue=NULL)
return/set a given contenido global parameter -> it is NOT recommended to set/override a global contenido parameter!
_getAllParams ($asObject=false)
get all '$_REQUEST' parameters
_html ($text, $domain=NULL, $quote_style=null, $charset=null, $double_encode=null, $mode=0)
get translated string converting special characters to html entities
_setting ($type, $name=null, $default="")
get Contenido effective CMS setting(s)
_text ($text, $domain=NULL)
get translated string
getAuth ()
return Contenido authorization object
getAuthId ()
return Contenido authorized user id
getCfg ()
return Contenido configuration
getCfgClient ()
return Contenido client configuration
getConfig ()
return configuration settings array
getDb ($db=null)
get (current) instance of DB_Contenido
getOptions ()
get object options array
getTpl ($tplName=NULL, $reset=FALSE)
generate and get template objects
isAuthNobody ()
determine if current Contenido user is not an authorized user
isDebug ()
determine if debug mode is set to true
setOptions ($options)
set object options array
setTplVars ($tplName, $config, $reset=FALSE)
set template variables (static and dynamic) array
Static Public Member Functions
static getInstance ($options=array())
get singelton instance object
Public Attributes
$_tpls
Protected Member Functions
__init ($params=null)
init (Contenido) object global parameters
Detailed Description
Definition at line 7 of file Base.php.
Constructor & Destructor Documentation
__construct ($options = array())
Definition at line 9 of file Base.php.
{
         parent::__construct($options);
         return ($this);
     }
Member Function Documentation
__init ($params = null) protected inherited
init (Contenido) object global parameters
Parameters
mixed $params
Returns
Contenido_Object_Abstract
Definition at line 115 of file Abstract.php.
References Contenido_Object_Abstract\__initOptions(), Contenido_Object_Abstract\getConVars(), Contenido_Object_Abstract\setConfig(), and Contenido_Object_Abstract\setOptions().
Referenced by Contenido_Object_Abstract\__construct().
{
         // basic object setup
         $oGlobals = (object)$this->getConVars( true );
         $this->setConfig( $oGlobals );
         $this->_config->tmplPath    =   getEffectiveSetting('global', 'templatepath', 'templates/');
         $this->_config->debug       =   (getEffectiveSetting('global', 'debug', 'false') == 'false') ? false : true;
         if ($this->_config->db instanceof DB_Contenido) {
             $this->_db =& $this->_config->db;
         }
         $this->setOptions($params);
         if (method_exists($this, "__initOptions")) {
             $this->__initOptions( $params );
         }
         return ($this);
     }
_con ($varname, $varvalue = NULL) inherited
return/set a given contenido global parameter -> it is NOT recommended to set/override a global contenido parameter!
Parameters
string $varname
mixed $varvalue
Returns
mixed
Definition at line 238 of file Abstract.php.
References Contenido_Object_Abstract\__setConVar(), and Contenido_Object_Abstract\getConVars().
Referenced by Contenido_Plugin_GUI_Form\__init(), Contenido_Plugin_GUI_Table\__init(), Contenido_Object_Abstract\_text(), Contenido_Plugin_GUI_Form\generateForm(), Contenido_Plugin_GUI_Form\generateFormAction(), Contenido_Plugin_GUI_Form\generateFormElementAction(), Contenido_Plugin_GUI_Form\generateFormToolsActions(), Contenido_Plugin_GUI\generateNavigationList(), Contenido_Plugin_GUI_Table\generateTable(), Contenido_Plugin_GUI_Table\generateTableAction(), Contenido_Plugin_GUI_Table\generateTableToolsActions(), Contenido_Plugin_GUI\getFrameTemplate(), Contenido_Plugin_GUI\page_close(), and Contenido_Plugin_GUI\page_open().
{
         $aConVars = $this->getConVars();
         if ( $varvalue === NULL ) {
             return ((isset($aConVars[$varname])) ? $aConVars[$varname] : NULL);
         } else {
             $this->__setConVar($varname, $varvalue);
             return $this->_con($varname);
         }
     }
_getAllParams ($asObject = false) inherited
get all '$_REQUEST' parameters
Returns
array|stdClass
Definition at line 395 of file Abstract.php.
Referenced by Contenido_Plugin_GUI_Form\__init(), Contenido_Plugin_GUI_Table\__init(), Contenido_Plugin_GUI_Table\_parseToolsParams(), and Contenido_Plugin_GUI_Form\_parseToolsParams().
{
         return ($asObject) ? (object)$_REQUEST : (array)$_REQUEST;
     }
_html ($text, $domain = NULL, $quote_style = null, $charset = null, $double_encode = null, $mode = 0) inherited
get translated string converting special characters to html entities
string $text string $domain integer $quote_style [optional] Like htmlspecialchars, the optional second quote_style parameter lets you define what will be done with 'single' and "double" quotes. It takes on one of three constants with the default being ENT_COMPAT:
quote_style constants
Constant Name
Description
ENT_COMPAT
Will convert double-quotes and leave single-quotes alone.
ENT_QUOTES
Will convert both double and single quotes.
ENT_NOQUOTES
Will leave both double and single quotes unconverted.
Parameters
string $charset [optional]
Like htmlspecialchars, it takes an optional third argument charset which defines character set used in conversion. Presently, the ISO-8859-1 character set is used as the default.
&reference.strings.charsets;
Parameters
boolean $double_encode [optional]
When double_encode is turned off PHP will not encode existing html entities. The default is to convert everything.
Parameters
integer $mode [optional]
0 = using htmlentities() (default), 1 = using htmlspecialchars()
Returns
string
Definition at line 187 of file Abstract.php.
{
         return ($mode == 1) ? htmlspecialchars( i18n($text, $domain), $quote_style, $charsetl, $double_encode ) : htmlentities( i18n($text, $domain), $quote_style, $charsetl, $double_encode );
     }
_setting ($type, $name = null, $default = "") inherited
get Contenido effective CMS setting(s)
Parameters
string $type
string $name
string $default
Returns
string|array
Definition at line 223 of file Abstract.php.
{
         if ( empty($name) ) {
             return getEffectiveSettingsByType($type);
         }
         return getEffectiveSetting($type, $name, $default);
     }
_text ($text, $domain = NULL) inherited
get translated string
Parameters
string $text
string $domain
Returns
string
Definition at line 198 of file Abstract.php.
References Contenido_Object_Abstract\_con().
{
         $_mi18n = $this->_con("MI18N");
         $_string = $text;
         if ( is_array($_mi18n) && isset($_mi18n[$text]) ) {
             $_string = (string)$_mi18n[$text];
         } else
         if ( is_array($_mi18n) && is_array($_mi18n[$domain]) && isset($_mi18n[$domain][$text]) ) {
             $_string = (string)$_mi18n[$domain][$text];
         } else
         if ( ($this->_con("cnumber") !== NULL) && ( $this->_con("mi18nTranslator") !== NULL ) ) {
             $_string =  mi18n($text, $domain);
         } else {
             $_string = i18n($text, $domain);
         }
         return $_string;
     }
getAuth () inherited
return Contenido authorization object
Returns
stdClass|array
Definition at line 458 of file Abstract.php.
References Contenido_Object_Abstract\getConfig().
Referenced by Contenido_Object_Abstract\getAuthId().
{
         return (object)$this->getConfig()->auth->auth;
     }
getAuthId () inherited
return Contenido authorized user id
Returns
string
Definition at line 466 of file Abstract.php.
References Contenido_Object_Abstract\getAuth().
Referenced by Contenido_Object_Abstract\isAuthNobody().
{
         return $this->getAuth()->uid;
     }
getCfg () inherited
return Contenido configuration
Returns
stdClass|array
Definition at line 442 of file Abstract.php.
References Contenido_Object_Abstract\getConfig().
Referenced by Contenido_Plugin_GUI_Form\generateForm(), Contenido_Plugin_GUI_Form\generateFormToolsActions(), Contenido_Plugin_GUI_Table\generateTable(), Contenido_Plugin_GUI_Table\generateTableToolsActions(), Contenido_Plugin_GUI\page_close(), and Contenido_Plugin_GUI\page_open().
{
         return (object)$this->getConfig()->cfg;
     }
getCfgClient () inherited
return Contenido client configuration
Returns
stdClass|array
Definition at line 450 of file Abstract.php.
References Contenido_Object_Abstract\getConfig().
{
         return (object)$this->getConfig()->cfgClient;
     }
getConfig () inherited
return configuration settings array
Returns
stdClass|array
Definition at line 253 of file Abstract.php.
References Contenido_Object_Abstract\$_config.
Referenced by Contenido_Plugin_GUI\generateNavigationList(), Contenido_Object_Abstract\getAuth(), Contenido_Object_Abstract\getCfg(), Contenido_Object_Abstract\getCfgClient(), Contenido_Plugin_GUI\getFrameTemplate(), Contenido_Object_Abstract\isDebug(), and Contenido_Plugin_GUI_Form\validateFormElements().
{
         return (object)$this->_config;
     }
getDb ($db = null) inherited
get (current) instance of DB_Contenido
Parameters
DB_Contenido $db
Returns
DB_Contenido
Definition at line 357 of file Abstract.php.
Referenced by Contenido_Plugin_GUI_Form\__init(), Contenido_Plugin_GUI_Table\__init(), Contenido_Plugin_GUI_Table\_buildEqualLikeWhere(), Contenido_Plugin_GUI_Form\_buildEqualLikeWhere(), Contenido_Plugin_GUI_Form\_buildQuery(), Contenido_Plugin_GUI_Table\_buildTableQuery(), Contenido_Plugin_GUI_Form\_getDbFormColumns(), Contenido_Plugin_GUI_Table\_getDbTableColumns(), Contenido_Plugin_GUI_Table\_loadDbData(), Contenido_Plugin_GUI_Form\_loadDbData(), Contenido_Plugin_GUI_Form\_setForm(), and Contenido_Plugin_GUI_Table\_setTable().
{
         if ( $this->_db instanceof DB_Contenido ) {
             return ($this->_db);
         }
         if ($db instanceof DB_Contenido) {
             $this->_db = $db;
         } else {
             $this->_db = new DB_Contenido;
         }
         return ($this->_db);
     }
static getInstance ($options = array()) static inherited
get singelton instance object
Parameters
array | stdClass $config
Returns
Contenido_Object_Abstract
Definition at line 102 of file Abstract.php.
{
         if ( self::$_instance === NULL ) {
             self::$_instance = new self( $options );
         }
         return self::$_instance;
     }
getOptions () inherited
get object options array
Returns
array|stdClass
Definition at line 374 of file Abstract.php.
References Contenido_Object_Abstract\$_options.
Referenced by Contenido_Object_Abstract\setOptions().
{
         return (array)$this->_options;
     }
getTpl ($tplName = NULL, $reset = FALSE) inherited
generate and get template objects
Parameters
string $tplName
boolean $reset
Returns
Template
Definition at line 275 of file Abstract.php.
Referenced by Contenido_Plugin_GUI_Form\generateForm(), Contenido_Plugin_GUI_Form\generateFormAction(), Contenido_Plugin_GUI_Form\generateFormElementAction(), Contenido_Plugin_GUI_Form\generateFormElements(), Contenido_Plugin_GUI_Form\generateFormJS(), Contenido_Plugin_GUI_Form\generateFormTools(), Contenido_Plugin_GUI\generateNavigationList(), Contenido_Plugin_GUI_Table\generateTable(), Contenido_Plugin_GUI_Table\generateTableAction(), Contenido_Plugin_GUI_Table\generateTableJS(), Contenido_Plugin_GUI_Table\generateTableTools(), Contenido_Plugin_GUI\getFrameTemplate(), Contenido_Plugin_GUI\page_close(), Contenido_Plugin_GUI\page_open(), Contenido_Object_Abstract\setTpl(), and Contenido_Object_Abstract\setTplVars().
{
         if ( empty($tplName) ) {
             $tplName = 'default';
         }
         if ( ( !isset($this->_tpls[$tplName]) || !isset($this->_tpls[$tplName]->template) || !($this->_tpls[$tplName]->template instanceof Template) ) || $reset) {
             $oTemplate = new Template();
             $oTemplate->reset();
             $this->_tpls[$tplName] = (object)array(
                 "name"      =>  $tplName,
                 "template"  =>  $oTemplate,
                 "content"   =>  '',
                 "static"    =>  array(),
                 "dynamic"   =>  array(),
             );
         }
         if ($reset) {
             $this->_tpls[$tplName]->template->reset();
         }
         return $this->_tpls[$tplName];
     }
isAuthNobody () inherited
determine if current Contenido user is not an authorized user
Returns
boolean
Definition at line 474 of file Abstract.php.
References Contenido_Object_Abstract\getAuthId().
{
         return $this->getAuthId() == "nobody";
     }
isDebug () inherited
determine if debug mode is set to true
Returns
boolean
Definition at line 482 of file Abstract.php.
References Contenido_Object_Abstract\getConfig().
{
         return $this->getConfig()->debug === true;
     }
setOptions ($options) inherited
set object options array
Parameters
array | stdClass $options
Returns
Contenido_Object_Abstract
Definition at line 384 of file Abstract.php.
References Contenido_Object_Abstract\getOptions().
Referenced by Contenido_Object_Abstract\__init().
{
         $aOptions = $this->getOptions();
         $this->_options = array_merge_recursive($aOptions, (array)$options);
         return ($this);
     }
setTplVars ($tplName, $config, $reset = FALSE) inherited
set template variables (static and dynamic) array
Parameters
string $tplName
array | stdClass $config
boolean $reset
Returns
Template
Definition at line 328 of file Abstract.php.
References Contenido_Object_Abstract\getTpl().
Referenced by Contenido_Plugin_GUI_Form\generateFormAction(), Contenido_Plugin_GUI_Form\generateFormJS(), Contenido_Plugin_GUI\generateNavigationList(), Contenido_Plugin_GUI_Table\generateTableAction(), Contenido_Plugin_GUI_Table\generateTableJS(), Contenido_Plugin_GUI\page_close(), Contenido_Plugin_GUI\page_open(), and Contenido_Object_Abstract\setTpl().
{
         if ( empty($tplName) ) {
             $tplName = 'default';
         }
         if ( is_array($config) ) { $config = (object)$config; }
         $oTemplate = $this->getTpl( $tplName, $reset );
         if ( is_array($config->static) || is_object($config->static) ) {
             foreach ((array)$config->static as $needle => $replacement) {
                 $oTemplate->template->set("s", $needle, $replacement);
             }
         }
         if ( is_array($config->dynamic) || is_object($config->dynamic) ) {
             foreach ((array)$config->dynamic as $idx => $vars) {
                 $oTemplate->template->set("d", "BLOCKINDEX", $replacement);
                 foreach ((array)$vars as $needle => $replacement) {
                     $oTemplate->template->set("d", $needle, $replacement);
                 }
                 $oTemplate->template->next();
             }
         }
         return ($oTemplate->template);
     }
Member Data Documentation
$_tpls inherited
Initial value:
= array(
    )
Definition at line 56 of file Abstract.php.
The documentation for this class was generated from the following file:
/Users/bba/resources/php/contenido/Plugin_and_Extension_API__PEA/branches/4.8/classes/Contenido/Object/Base.php