Contenido PEA: Contenido_Plugin_GUI_Form Class Reference
Contenido_Plugin_GUI_Form Class Reference
Public Member Functions
__construct ($options=array())
__construct ($options=array())
__init ($options=array())
initialize default form configurations and object options
__init ($options=array())
initialize default form configurations and object options
_con ($varname, $varvalue=NULL)
return/set a given contenido global parameter -> it is NOT recommended to set/override a global contenido parameter!
_getAllParams ($asObject=false)
get all '$_REQUEST' parameters
_getForm ()
_getForm ()
_getFormDataError ()
_getFormDataError ()
_getMaxPages ()
detect maximum number of pages from elements configuration, also sets page parameter if not already set
_getMaxPages ()
detect maximum number of pages from elements configuration, also sets page parameter if not already set
_html ($text, $domain=NULL, $quote_style=null, $charset=null, $double_encode=null, $mode=0)
get translated string converting special characters to html entities
_setForm ($_oForm)
_setForm ($_oForm)
_setting ($type, $name=null, $default="")
get Contenido effective CMS setting(s)
_text ($text, $domain=NULL)
get translated string
addNotification ($mNotifications)
configForm ()
overridable method to initialize user's form configurations and object options
configForm ()
overridable method to initialize user's form configurations and object options
generate ($bReturn=TRUE)
generate ($bReturn=TRUE)
generateForm ($bReturn=TRUE)
generateForm ($bReturn=TRUE)
generateFormAction ($oAction, $bReturn=TRUE)
generateFormAction ($oAction, $bReturn=TRUE)
generateFormBottomPanel ($bReturn=TRUE)
generateFormBottomPanel ($bReturn=TRUE)
generateFormElementAction ($oAction, $bReturn=TRUE)
generateFormElements ($aElements=array(), $parent=NULL, $level=0, $bReturn=TRUE)
generateFormElements ($aElements=NULL, $parent=NULL, $level=0, $bReturn=TRUE)
generateFormJS ($sJSTemplate="", $bReturn=TRUE)
generateFormJS ($sJSTemplate="", $bReturn=TRUE)
generateFormTools ($sTemplate="", $bReturn=TRUE)
generateFormTools ($sTemplate="", $bReturn=TRUE)
generateFormToolsActions ($bReturn=TRUE)
generateFormToolsActions ($bReturn=TRUE)
generateFormToolsNotification ($sMessage="", $bReturn=TRUE)
generateFormToolsNotification ($sMessage="", $bReturn=TRUE)
generateFormToolsPagination ($sPageStart="", $sRowsPerPage=15, $bReturn=TRUE)
generateFormToolsPagination ($sPageStart="", $sRowsPerPage=15, $bReturn=TRUE)
generateFormTopPanel ($bReturn=TRUE)
generateFormTopPanel ($bReturn=TRUE)
getAuth ()
return Contenido authorization object
getAuthId ()
return Contenido authorized user id
getCfg ()
return Contenido configuration
getCfgClient ()
return Contenido client configuration
getConfig ()
return configuration settings array
getDb ($db=null)
get (current) instance of DB_Contenido
getElements ()
getElements ()
getFooter ()
getFooter ()
getFormActions ($asObject=FALSE)
getFormActions ($asObject=FALSE)
getFormConfig ($asObject=FALSE)
getFormConfig ($asObject=FALSE)
getFormName ()
getFormName ()
getFormTemplates ($asObject=FALSE)
getFormTemplates ($asObject=FALSE)
getFormTools ($asObject=FALSE)
getFormTools ($asObject=FALSE)
getFormToolsURL ()
getFormToolsURL ()
getNoRenderActions ()
getNoRenderActions ()
getNotifications ($sMode="")
getOptions ()
get object options array
getQuery ()
getQuery ()
getRowActions ($asObject=FALSE)
getRowActions ($asObject=FALSE)
getSession ()
get session
getSession ()
get session
getTpl ($tplName=NULL, $reset=FALSE)
generate and get template objects
getValues ($field=NULL)
get current form values, for given field(set) or all
isAuthNobody ()
determine if current Contenido user is not an authorized user
isDebug ()
determine if debug mode is set to true
resetNotifications ()
setElementError (&$element=NULL, $aErrorData=array())
set error messages to element properties
setElements ($_aElements=array())
setElements ($_aElements=array())
setErrors ($aErrorData=array())
set error messages to element properties
setFooter ($_aFooterCells=array())
setFooter ($_aFooterCells=array())
setFormActions ($_oFormActions)
setFormActions ($_oFormActions)
setFormConfig ($_oFormConfig)
setFormConfig ($_oFormConfig)
setFormDataError ($_oFormDataError)
setFormDataError ($_oFormDataError)
setFormName ($_sFormName)
setFormName ($_sFormName)
setFormTemplates ($_oFormTools)
setFormTemplates ($_oFormTools)
setFormTools ($_oFormTools)
setFormTools ($_oFormTools)
setNoRenderActions ($aNoRenderActions)
setNoRenderActions ($aNoRenderActions)
setOptions ($options)
set object options array
setQuery ($_sQuery)
setQuery ($_sQuery)
setRowActions ($_oRowActions)
setRowActions ($_oRowActions)
setTplVars ($tplName, $config, $reset=FALSE)
set template variables (static and dynamic) array
setValues ($aData=array(), $bForce=FALSE)
set current form values
validateData ($aData=array(), $bAddNotification=true)
validate form value data array retruns TRUE or array with error messages
validateFormElements ($aElements=NULL, $aData=NULL, $parent=NULL, $level=0, $bReturn=TRUE)
Static Public Member Functions
static getInstance ($options=array())
get singelton instance object
Public Attributes
$_aElements = array()
$_oDB = null
form db object container
$_oFormConfig
$_oFormDataError = NULL
form data error container object
$_oFormNotifications = array()
$_oFormSession = NULL
form session container
$_oFormTools
$_sFormHashId = NULL
$_sFormId = NULL
form object container id
$_sFormIdPrefix = 'form_'
form object container id prefix string
$_sQuery = ""
db form SQL query string
$_tpls
$aEncTypes
$aNoRenderActions
$types = array("text", "password", "button", "file", "radio", "checkbox", "textarea", "select", "hidden")
Protected Member Functions
_buildEqualLikeWhere ($aFields, $searchData="", $conjunction="OR")
_buildEqualLikeWhere ($aFields, $searchData="", $conjunction="OR")
_buildQuery ()
apply tavle tools filter/sort parameter
_buildQuery ()
apply tavle tools filter/sort parameter
_getDbFormColumns ($full=FALSE, $prependFormName=FALSE)
retrieve db form's column definitions
_getDbFormColumns ($full=FALSE, $prependFormName=FALSE)
retrieve db form's column definitions
_loadDbData ()
_loadDbData ()
_parseToolsParams ($aParams=NULL)
parse request's form tools parameters
_parseToolsParams ($aParams=NULL)
parse request's form tools parameters
_setFormHashId ($sFormHashId="")
create or set panel hash id
_setFormHashId ($sFormHashId="")
create or set panel hash id
_setFormId ($sFormId="")
set form's element id
_setFormId ($sFormId="")
set form's element id
_setFormSession ($sFormHashId="", $bReset=TRUE)
create panel session object
_setFormSession ($sFormHashId="", $bReset=TRUE)
create panel session object
getHash ()
get panel hash id
getHash ()
get panel hash id
getId ()
get panel's element id
getId ()
get panel's element id
Protected Attributes
$_sFormName = ""
db form name string
Detailed Description
Definition at line 14 of file Form.php.
Constructor & Destructor Documentation
__construct ($options = array())
Definition at line 259 of file Form.php.
References __init().
{
         parent::__construct($options);
         $this->__init($options);
         return ($this);
     }
__construct ($options = array())
Definition at line 231 of file Form.save.php.
References __init().
{
         parent::__construct($options);
         $this->__init($options);
         return ($this);
     }
Member Function Documentation
__init ($options = array())
initialize default form configurations and object options
See Also
Contenido_Object::init()
Definition at line 188 of file Form.save.php.
References Contenido_Object_Abstract\_con(), Contenido_Object_Abstract\_getAllParams(), _parseToolsParams(), _setFormHashId(), configForm(), Contenido_Object_Abstract\getDb(), getFormConfig(), getFormTools(), getHash(), getId(), getSession(), setElements(), setFormActions(), setFormConfig(), setFormName(), setFormTemplates(), and setFormTools().
{
         parent::__init();
         $aRequest                       = $this->_getAllParams();
         $this->_oForm                   = $this->getDb();
         if ( !isset($aRequest["PHPSESSID"]) || empty($aRequest["PHPSESSID"]) ) {
             unset( $aRequest["PHPSESSID"] );
         }
         if ( !isset($aRequest["hash"]) || empty($aRequest["hash"]) ) {
             $aRequest["hash"]           = $this->getHash();
         } else {
             $this->_setFormHashId($aRequest["hash"]);
         }
         $this->_oFormConfig["hash"] = $aRequest["hash"]; // $this->getHash();
         $this->_oFormConfig["id"]       = $this->getId();
         $aNonFormToolsParams = $aRequest;
         foreach ((array)$this->getFormTools() as $key => $value) {
             if (array_key_exists( $key, $aRequest) ) {
                 unset($aNonFormToolsParams[$key]);
             }
         }
         $this->_oFormConfig["url"]      = $this->_con('sess')->url( 'main.php?'.http_build_query($aNonFormToolsParams) );
         $defaults = $this->getFormConfig();
         //$mergedOptions = array_merge_recursive( $defaults, $options );
         $mergedOptions = array_merge( $defaults, $options );
         $this->setFormConfig( $mergedOptions );
         $this->setFormTools( $mergedOptions["oFormTools"] );
         $this->setElements( $mergedOptions["oElements"] );
         $this->setFormTemplates($mergedOptions["oTemplates"]);
         $this->setFormActions($mergedOptions["oFormActions"]);
         $this->_parseToolsParams();
         if (isset($options["dbFormName"])) { $this->setFormName( trim($options["dbFormName"]) ); }
         $this->getSession();
         $this->configForm();
     }
__init ($options = array())
initialize default form configurations and object options
See Also
Contenido_Object::init()
Definition at line 216 of file Form.php.
References Contenido_Object_Abstract\_con(), Contenido_Object_Abstract\_getAllParams(), _parseToolsParams(), _setFormHashId(), configForm(), Contenido_Object_Abstract\getDb(), getFormConfig(), getFormTools(), getHash(), getId(), getSession(), setElements(), setFormActions(), setFormConfig(), setFormName(), setFormTemplates(), and setFormTools().
Referenced by __construct().
{
         parent::__init();
         $aRequest                       = $this->_getAllParams();
         $this->_oForm                   = $this->getDb();
         if ( !isset($aRequest["PHPSESSID"]) || empty($aRequest["PHPSESSID"]) ) {
             unset( $aRequest["PHPSESSID"] );
         }
         if ( !isset($aRequest["hash"]) || empty($aRequest["hash"]) ) {
             $aRequest["hash"]           = $this->getHash();
         } else {
             $this->_setFormHashId($aRequest["hash"]);
         }
         $this->_oFormConfig["hash"] = $aRequest["hash"]; // $this->getHash();
         $this->_oFormConfig["id"]       = $this->getId();
         $aNonFormToolsParams = $aRequest;
         foreach ((array)$this->getFormTools() as $key => $value) {
             if (array_key_exists( $key, $aRequest) ) {
                 unset($aNonFormToolsParams[$key]);
             }
         }
         $this->_oFormConfig["url"]      = $this->_con('sess')->url( 'main.php?'.http_build_query($aNonFormToolsParams) );
         $defaults = $this->getFormConfig();
         //$mergedOptions = array_merge_recursive( $defaults, $options );
         $mergedOptions = array_merge( $defaults, $options );
         $this->setFormConfig( $mergedOptions );
         $this->setFormTools( $mergedOptions["oFormTools"] );
         $this->setElements( $mergedOptions["elements"] );
         $this->setFormTemplates($mergedOptions["oTemplates"]);
         $this->setFormActions($mergedOptions["oFormActions"]);
         $this->_parseToolsParams();
         if (isset($options["dbFormName"])) { $this->setFormName( trim($options["dbFormName"]) ); }
         $this->getSession();
         $this->configForm();
     }
_buildEqualLikeWhere ($aFields, $searchData = "", $conjunction = "OR") protected
Definition at line 550 of file Form.save.php.
References Contenido_Object_Abstract\getDb().
{
         $searchData = trim($searchData);
         if ( empty($searchData) ) {
             return "";
         }
         $oDB            = $this->getDb();
         $aWheres        = array();
         $conjunction    = ($conjunction == "OR") ? "OR" : "AND";
         foreach ((array)$aFields as $key => $aField) {
             if ( !empty($aField["Collation"]) || ($aField["Type"] == 'timestamp') ) {
                 $op = "LIKE";
             } else {
                 $op = "=";
             }
             array_push(
                 $aWheres,
                 ("`".$aField["Field"]."`") .
                     (" ".$op." ") .
                 ("'".(($op == "LIKE") ? "%" : "").Contenido_Security::escapeDB($searchData, $oDB).(($op == "LIKE") ? "%" : "")."'")
             );
         }
         $glue = " ) ".$conjunction." ( ";
         $sWhere =  "( ".implode($glue, $aWheres)." )" . " " ;
         return $sWhere;
     }
_buildEqualLikeWhere ($aFields, $searchData = "", $conjunction = "OR") protected
Definition at line 750 of file Form.php.
References Contenido_Object_Abstract\getDb().
Referenced by _buildQuery().
{
         $searchData = trim($searchData);
         if ( empty($searchData) ) {
             return "";
         }
         $oDB            = $this->getDb();
         $aWheres        = array();
         $conjunction    = ($conjunction == "OR") ? "OR" : "AND";
         foreach ((array)$aFields as $key => $aField) {
             if ( !empty($aField["Collation"]) || ($aField["Type"] == 'timestamp') ) {
                 $op = "LIKE";
             } else {
                 $op = "=";
             }
             array_push(
                 $aWheres,
                 ("`".$aField["Field"]."`") .
                     (" ".$op." ") .
                 ("'".(($op == "LIKE") ? "%" : "").Contenido_Security::escapeDB($searchData, $oDB).(($op == "LIKE") ? "%" : "")."'")
             );
         }
         $glue = " ) ".$conjunction." ( ";
         $sWhere =  "( ".implode($glue, $aWheres)." )" . " " ;
         return $sWhere;
     }
_buildQuery () protected
apply tavle tools filter/sort parameter
Returns
Contenido_Plugin_GUI_Form
Definition at line 580 of file Form.save.php.
References _buildEqualLikeWhere(), _getDbFormColumns(), _parseToolsParams(), Contenido_Object_Abstract\getDb(), getFormName(), getFormTools(), and setQuery().
{
         $this->_parseToolsParams();
         $sFormName  = $this->getFormName();
         $sQuery     = "";
         if (!empty($sFormName)) {
             $oDB        = $this->getDb();
             $sQuery     = "SELECT * FROM `".Contenido_Security::escapeDB($sFormName, $oDB)."` ";
             $oTools     = $this->getFormTools(TRUE);
             $aFields    = $this->_getDbFormColumns(TRUE);
             if ( !empty($oTools->searchData) && empty($oTools->filterData) ) {
                 $oTools->filterCol = '*'; $oTools->filterData = trim($oTools->searchData);
             }
             if ( !empty($oTools->filterCol) && !empty($oTools->filterData) && array_key_exists($oTools->filterCol, $aFields) ) {
                 if ( ($oTools->filterCol != '*') ) {
                     if ( !empty($aFields[$oTools->filterCol]["Collation"]) || ($aFields[$oTools->filterCol]["Type"] == 'timestamp') ) {
                         $op = "LIKE";
                     } else {
                         $op = "=";
                     }
                     $sQuery     .= "WHERE" ." (".
                                         ("`".Contenido_Security::escapeDB($oTools->filterCol, $oDB)."`") ."".
                                    (" ".$op." ").
                                         ("'"."%".Contenido_Security::escapeDB($oTools->filterData, $oDB)."%"."'") .") " ;
                 } else {
                 }
             } else if ( ($oTools->filterCol == '*') && !empty($oTools->filterData) ) {
                     $sQuery     .= "WHERE" ." (". $this->_buildEqualLikeWhere($aFields, $oTools->filterData) . ") ";
             } else {
                 $sQuery     .= "WHERE" ." " ."1" ." ";
             }
             if ( ($oTools->onlyActive == 'true') ) {
                 $sQuery     .= "AND (`active`='1') ";
             }
             if ( !empty($oTools->orderField) && !empty($oTools->sortOrder) ) {
                 $sQuery     .= "ORDER BY ".
                                     ("`".Contenido_Security::escapeDB($oTools->orderField, $oDB)."`") . " " .
                                     (($oTools->sortOrder == 'asc') ? "ASC" : "DESC") . " ";
             }
             if ( !empty($oTools->page) && !empty($oTools->pageCount) && ($oTools->pageCount != 'all') ) {
                 $sCountQuery = str_replace("SELECT *", "SELECT count(`active`) AS `numRows`", $sQuery);
                 $oDB->query($sCountQuery);
                 while ( $oDB->next_record() ) {
                     $iRows = $oDB->f('numRows');
                 }
                 $oTools->pages = (int)($iRows / $oTools->pageCount) + ( (($iRows % $oTools->pageCount) > 0) ? 1 : 0);
                 $lStart = ( (int)$oTools->page - 1 ) * (int)$oTools->pageCount;
                 if ($oTools->page > $oTools->pageCount) {
                     $lStart = 0;
                 }
                 $sQuery     .= "LIMIT " . $lStart . ", " . (int)$oTools->pageCount;
             }
         }
         $this->setQuery($sQuery);
         return $this;
     }
_buildQuery () protected
apply tavle tools filter/sort parameter
Returns
Contenido_Plugin_GUI_Form
Definition at line 780 of file Form.php.
References _buildEqualLikeWhere(), _getDbFormColumns(), _parseToolsParams(), Contenido_Object_Abstract\getDb(), getFormName(), getFormTools(), and setQuery().
Referenced by getQuery().
{
         $this->_parseToolsParams();
         $sFormName  = $this->getFormName();
         $sQuery     = "";
         if (!empty($sFormName)) {
             $oDB        = $this->getDb();
             $sQuery     = "SELECT * FROM `".Contenido_Security::escapeDB($sFormName, $oDB)."` ";
             $oTools     = $this->getFormTools(TRUE);
             $aFields    = $this->_getDbFormColumns(TRUE);
             if ( !empty($oTools->searchData) && empty($oTools->filterData) ) {
                 $oTools->filterCol = '*'; $oTools->filterData = trim($oTools->searchData);
             }
             if ( !empty($oTools->filterCol) && !empty($oTools->filterData) && array_key_exists($oTools->filterCol, $aFields) ) {
                 if ( ($oTools->filterCol != '*') ) {
                     if ( !empty($aFields[$oTools->filterCol]["Collation"]) || ($aFields[$oTools->filterCol]["Type"] == 'timestamp') ) {
                         $op = "LIKE";
                     } else {
                         $op = "=";
                     }
                     $sQuery     .= "WHERE" ." (".
                                         ("`".Contenido_Security::escapeDB($oTools->filterCol, $oDB)."`") ."".
                                    (" ".$op." ").
                                         ("'"."%".Contenido_Security::escapeDB($oTools->filterData, $oDB)."%"."'") .") " ;
                 } else {
                 }
             } else if ( ($oTools->filterCol == '*') && !empty($oTools->filterData) ) {
                     $sQuery     .= "WHERE" ." (". $this->_buildEqualLikeWhere($aFields, $oTools->filterData) . ") ";
             } else {
                 $sQuery     .= "WHERE" ." " ."1" ." ";
             }
             if ( ($oTools->onlyActive == 'true') ) {
                 $sQuery     .= "AND (`active`='1') ";
             }
             if ( !empty($oTools->orderField) && !empty($oTools->sortOrder) ) {
                 $sQuery     .= "ORDER BY ".
                                     ("`".Contenido_Security::escapeDB($oTools->orderField, $oDB)."`") . " " .
                                     (($oTools->sortOrder == 'asc') ? "ASC" : "DESC") . " ";
             }
             if ( !empty($oTools->page) && !empty($oTools->pageCount) && ($oTools->pageCount != 'all') ) {
                 $sCountQuery = str_replace("SELECT *", "SELECT count(`active`) AS `numRows`", $sQuery);
                 $oDB->query($sCountQuery);
                 while ( $oDB->next_record() ) {
                     $iRows = $oDB->f('numRows');
                 }
                 $oTools->pages = (int)($iRows / $oTools->pageCount) + ( (($iRows % $oTools->pageCount) > 0) ? 1 : 0);
                 $lStart = ( (int)$oTools->page - 1 ) * (int)$oTools->pageCount;
                 if ($oTools->page > $oTools->pageCount) {
                     $lStart = 0;
                 }
                 $sQuery     .= "LIMIT " . $lStart . ", " . (int)$oTools->pageCount;
             }
         }
         $this->setQuery($sQuery);
         return $this;
     }
_con ($varname, $varvalue = NULL) inherited
return/set a given contenido global parameter -> it is NOT recommended to set/override a global contenido parameter!
Parameters
string $varname
mixed $varvalue
Returns
mixed
Definition at line 238 of file Abstract.php.
References Contenido_Object_Abstract\__setConVar(), and Contenido_Object_Abstract\getConVars().
Referenced by __init(), Contenido_Plugin_GUI_Table\__init(), Contenido_Object_Abstract\_text(), generateForm(), generateFormAction(), generateFormElementAction(), generateFormToolsActions(), Contenido_Plugin_GUI\generateNavigationList(), Contenido_Plugin_GUI_Table\generateTable(), Contenido_Plugin_GUI_Table\generateTableAction(), Contenido_Plugin_GUI_Table\generateTableToolsActions(), Contenido_Plugin_GUI\getFrameTemplate(), Contenido_Plugin_GUI\page_close(), and Contenido_Plugin_GUI\page_open().
{
         $aConVars = $this->getConVars();
         if ( $varvalue === NULL ) {
             return ((isset($aConVars[$varname])) ? $aConVars[$varname] : NULL);
         } else {
             $this->__setConVar($varname, $varvalue);
             return $this->_con($varname);
         }
     }
_getAllParams ($asObject = false) inherited
get all '$_REQUEST' parameters
Returns
array|stdClass
Definition at line 395 of file Abstract.php.
Referenced by __init(), Contenido_Plugin_GUI_Table\__init(), Contenido_Plugin_GUI_Table\_parseToolsParams(), and _parseToolsParams().
{
         return ($asObject) ? (object)$_REQUEST : (array)$_REQUEST;
     }
_getDbFormColumns ($full = FALSE, $prependFormName = FALSE) protected
retrieve db form's column definitions
Returns
Contenido_Plugin_GUI_Form
Definition at line 522 of file Form.save.php.
References Contenido_Object_Abstract\getDb(), and getFormName().
{
         $sFormName  = $this->getFormName();
         $aFields    = array();
         if (!empty($sFormName)) {
             $oDB = $this->getDb();
             $sQuery = "SHOW FULL COLUMNS FROM `".Contenido_Security::escapeDB($sFormName, $oDB)."`;";
             $oDB->query($sQuery);
             while ($oDB->next_record()) {
                 if ( $full ) {
                     $aFields[$oDB->f('Field')] = array(
                         "Field"         => (($prependFormName) ? $sFormName."." : "" ) .$oDB->f('Field'),
                         "Type"          => $oDB->f('Type'),
                         "Collation"     => $oDB->f('Collation'),
                         "Null"          => ($oDB->f('Null') == 'NO') ? FALSE : !!$oDB->f('Null'),
                         "Key"           => $oDB->f('Key'),
                         "Default"       => $oDB->f('Default'),
                         "Extra"         => $oDB->f('Extra'),
                         "Privileges"    => $oDB->f('Privileges'),
                         "Comment"       => $oDB->f('Comment'),
                     );
                 } else {
                     array_push($aFields, $oDB->f('Field'));
                 }
             }
         }
         return $aFields;
     }
_getDbFormColumns ($full = FALSE, $prependFormName = FALSE) protected
retrieve db form's column definitions
Returns
Contenido_Plugin_GUI_Form
Definition at line 722 of file Form.php.
References Contenido_Object_Abstract\getDb(), and getFormName().
Referenced by _buildQuery().
{
         $sFormName  = $this->getFormName();
         $aFields    = array();
         if (!empty($sFormName)) {
             $oDB = $this->getDb();
             $sQuery = "SHOW FULL COLUMNS FROM `".Contenido_Security::escapeDB($sFormName, $oDB)."`;";
             $oDB->query($sQuery);
             while ($oDB->next_record()) {
                 if ( $full ) {
                     $aFields[$oDB->f('Field')] = array(
                         "Field"         => (($prependFormName) ? $sFormName."." : "" ) .$oDB->f('Field'),
                         "Type"          => $oDB->f('Type'),
                         "Collation"     => $oDB->f('Collation'),
                         "Null"          => ($oDB->f('Null') == 'NO') ? FALSE : !!$oDB->f('Null'),
                         "Key"           => $oDB->f('Key'),
                         "Default"       => $oDB->f('Default'),
                         "Extra"         => $oDB->f('Extra'),
                         "Privileges"    => $oDB->f('Privileges'),
                         "Comment"       => $oDB->f('Comment'),
                     );
                 } else {
                     array_push($aFields, $oDB->f('Field'));
                 }
             }
         }
         return $aFields;
     }
_getForm ()
Returns
DB_Contenido $_oForm
Definition at line 845 of file Form.save.php.
References _setForm().
{
         if ( !($this->_oForm instanceof DB_Contenido) ) {
             $this->_setForm();
         }
         return $this->_oForm;
     }
_getForm ()
Returns
DB_Contenido $_oForm
Definition at line 1045 of file Form.php.
References _setForm().
{
         if ( !($this->_oForm instanceof DB_Contenido) ) {
             $this->_setForm();
         }
         return $this->_oForm;
     }
_getFormDataError ()
Returns
Exception $_oFormDataError
Definition at line 865 of file Form.save.php.
References $_oFormDataError.
{
         return $this->_oFormDataError;
     }
_getFormDataError ()
Returns
Exception $_oFormDataError
Definition at line 1065 of file Form.php.
References $_oFormDataError.
{
         return $this->_oFormDataError;
     }
_getMaxPages ()
detect maximum number of pages from elements configuration, also sets page parameter if not already set
Returns
INTEGER
Definition at line 1013 of file Form.save.php.
References getElements().
{
         $max = 1;
         foreach ($this->getElements() as $key => $element) {
             if (isset($element["page"])) {
                 if ($element["page"] > $max) {
                     $max = (int)$element["page"];
                 }
             } else {
                 $element["page"] = $max;
             }
         }
         return $max;
     }
_getMaxPages ()
detect maximum number of pages from elements configuration, also sets page parameter if not already set
Returns
INTEGER
Definition at line 1213 of file Form.php.
References getElements().
{
         $max = 1;
         foreach ($this->getElements() as $key => $element) {
             if (isset($element["page"])) {
                 if ($element["page"] > $max) {
                     $max = (int)$element["page"];
                 }
             } else {
                 $element["page"] = $max;
             }
         }
         return $max;
     }
_html ($text, $domain = NULL, $quote_style = null, $charset = null, $double_encode = null, $mode = 0) inherited
get translated string converting special characters to html entities
string $text string $domain integer $quote_style [optional] Like htmlspecialchars, the optional second quote_style parameter lets you define what will be done with 'single' and "double" quotes. It takes on one of three constants with the default being ENT_COMPAT:
quote_style constants
Constant Name
Description
ENT_COMPAT
Will convert double-quotes and leave single-quotes alone.
ENT_QUOTES
Will convert both double and single quotes.
ENT_NOQUOTES
Will leave both double and single quotes unconverted.
Parameters
string $charset [optional]
Like htmlspecialchars, it takes an optional third argument charset which defines character set used in conversion. Presently, the ISO-8859-1 character set is used as the default.
&reference.strings.charsets;
Parameters
boolean $double_encode [optional]
When double_encode is turned off PHP will not encode existing html entities. The default is to convert everything.
Parameters
integer $mode [optional]
0 = using htmlentities() (default), 1 = using htmlspecialchars()
Returns
string
Definition at line 187 of file Abstract.php.
{
         return ($mode == 1) ? htmlspecialchars( i18n($text, $domain), $quote_style, $charsetl, $double_encode ) : htmlentities( i18n($text, $domain), $quote_style, $charsetl, $double_encode );
     }
_loadDbData () protected
Returns
ARRAY $aHTMLFormElements
Definition at line 802 of file Form.save.php.
References Contenido_Object_Abstract\getDb(), and getQuery().
{
         $aHTMLFormElements          = array();
         $oDB            = $this->getDb();
         $sSQLGetRows    = $this->getQuery();
         if ($sSQLGetRows) {
             $oDB->query($sSQLGetRows);
             while ( $oDB->next_record() ) {
                 if ( $asObject ) {
                     array_push($aHTMLFormElements, (object)$oDB->Record);
                 } else {
                     array_push($aHTMLFormElements, $oDB->Record);
                 }
             }
         }
         return ($aHTMLFormElements);
     }
_loadDbData () protected
Returns
ARRAY $aHTMLFormElements
Definition at line 1002 of file Form.php.
References Contenido_Object_Abstract\getDb(), and getQuery().
{
         $aHTMLFormElements          = array();
         $oDB            = $this->getDb();
         $sSQLGetRows    = $this->getQuery();
         if ($sSQLGetRows) {
             $oDB->query($sSQLGetRows);
             while ( $oDB->next_record() ) {
                 if ( $asObject ) {
                     array_push($aHTMLFormElements, (object)$oDB->Record);
                 } else {
                     array_push($aHTMLFormElements, $oDB->Record);
                 }
             }
         }
         return ($aHTMLFormElements);
     }
_parseToolsParams ($aParams = NULL) protected
parse request's form tools parameters
Parameters
ARRAY $aParams
Returns
Contenido_Plugin_GUI_Form
Definition at line 644 of file Form.save.php.
References Contenido_Object_Abstract\_getAllParams(), getFormTools(), and setFormTools().
{
         $aParams    = ($aParams) ? $aParams : $this->_getAllParams();
         $aTools     = (array)$this->getFormTools();
         foreach ($aTools as $key => $value) {
             if ( array_key_exists($key, $aParams) && !empty($aParams[$key]) ) {
                 $aTools[$key] = trim($aParams[$key]);
             } else if ( array_key_exists($key, $aParams) ) {
                 $aTools[$key] = NULL;
             }
         }
         $this->setFormTools((object)$aTools);
         return $this;
     }
_parseToolsParams ($aParams = NULL) protected
parse request's form tools parameters
Parameters
ARRAY $aParams
Returns
Contenido_Plugin_GUI_Form
Definition at line 844 of file Form.php.
References Contenido_Object_Abstract\_getAllParams(), getFormTools(), and setFormTools().
Referenced by __init(), and _buildQuery().
{
         $aParams    = ($aParams) ? $aParams : $this->_getAllParams();
         $aTools     = (array)$this->getFormTools();
         foreach ($aTools as $key => $value) {
             if ( array_key_exists($key, $aParams) && !empty($aParams[$key]) ) {
                 $aTools[$key] = trim($aParams[$key]);
             } else if ( array_key_exists($key, $aParams) ) {
                 $aTools[$key] = NULL;
             }
         }
         $this->setFormTools((object)$aTools);
         return $this;
     }
_setForm ($_oForm)
Parameters
DB_Contenido $_oForm
Returns
Contenido_Plugin_GUI_Form
Definition at line 856 of file Form.save.php.
References _setFormSession(), and Contenido_Object_Abstract\getDb().
{
         $this->_oForm = $this->getDb();
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
_setForm ($_oForm)
Parameters
DB_Contenido $_oForm
Returns
Contenido_Plugin_GUI_Form
Definition at line 1056 of file Form.php.
References _setFormSession(), and Contenido_Object_Abstract\getDb().
Referenced by _getForm().
{
         $this->_oForm = $this->getDb();
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
_setFormHashId ($sFormHashId = "") protected
create or set panel hash id
Parameters
STRING $sFormHashId
Returns
self
Definition at line 699 of file Form.save.php.
References $_sFormHashId.
{
         if ( empty($sFormHashId) && empty($this->_sFormHashId) ) {
             // create new panel hash id
             $sHash = md5( uniqid(NULL, FALSE)."_".uniqid(NULL, TRUE) );
         } else if ( empty($sFormHashId) && !empty($this->_sFormHashId) ) {
             // apply previously set hash id
             $sHash = $this->_sFormHashId;
         } else {
             // set given hash id
             $sHash = $sFormHashId;
         }
         $this->_sFormHashId = $sHash;
         $this->_oFormConfig["hash"]  = $this->_sFormHashId;
         //$this->getSession();
         return $this;
     }
_setFormHashId ($sFormHashId = "") protected
create or set panel hash id
Parameters
STRING $sFormHashId
Returns
self
Definition at line 899 of file Form.php.
References $_sFormHashId.
Referenced by __init(), and getHash().
{
         if ( empty($sFormHashId) && empty($this->_sFormHashId) ) {
             // create new panel hash id
             $sHash = md5( uniqid(NULL, FALSE)."_".uniqid(NULL, TRUE) );
         } else if ( empty($sFormHashId) && !empty($this->_sFormHashId) ) {
             // apply previously set hash id
             $sHash = $this->_sFormHashId;
         } else {
             // set given hash id
             $sHash = $sFormHashId;
         }
         $this->_sFormHashId = $sHash;
         $this->_oFormConfig["hash"]  = $this->_sFormHashId;
         //$this->getSession();
         return $this;
     }
_setFormId ($sFormId = "") protected
set form's element id
Parameters
STRING $sFormId
Returns
Contenido_Plugin_GUI_Form
Definition at line 674 of file Form.save.php.
{
         if (empty($sFormId)) {
             $sFormId = uniqid($this->_sFormIdPrefix, TRUE);
         }
         $this->_sFormId = str_replace(".", "_", $sFormId);
         return $this;
     }
_setFormId ($sFormId = "") protected
set form's element id
Parameters
STRING $sFormId
Returns
Contenido_Plugin_GUI_Form
Definition at line 874 of file Form.php.
Referenced by getId().
{
         if (empty($sFormId)) {
             $sFormId = uniqid($this->_sFormIdPrefix, TRUE);
         }
         $this->_sFormId = str_replace(".", "_", $sFormId);
         return $this;
     }
_setFormSession ($sFormHashId = "", $bReset = TRUE) protected
create panel session object
Parameters
STRING $sFormHashId
BOOLEAN $bReset
Returns
void
Definition at line 733 of file Form.save.php.
References $_oFormSession, getFormConfig(), getFormTools(), getHash(), and getId().
{
         if (empty($sFormHashId)) {
             $sFormHashId = $this->getHash();
         }
         if ( (($this->_oFormSession === NULL) ) || $bReset) {
             $sNamespace = $this->_sFormIdPrefix . $sFormHashId;
             if ( !isset($_SESSION[$sNamespace]) ) {
                 $_SESSION[$sNamespace] = array();
             }
             $this->_oFormSession = $_SESSION[$sNamespace]; //new Zend_Session_Namespace($sNamespace);
             // $this->_oFormSession->setExpirationSeconds(300, 'accept_request');
             if ( !$this->_oFormSession["initialized"] ) {
                 $this->_oFormSession["sId"]             = $this->getId();
                 $this->_oFormSession["iRequestCount"]       = 0;
                 $this->_oFormSession["accept_request"]      = TRUE;
                 $this->_oFormSession["initialized"]     = TRUE;
             }
             if (!$bReset) {
                 //$this->_oFormSession["iRequestCount"]++;
             }
         }
         $this->_oFormSession["iRequestCount"]++;
         $this->_oFormSession["aFormConfig"]     = $this->getFormConfig();
         $this->_oFormSession["aFormTools"]      = $this->getFormTools();
         $_SESSION[$sNamespace] = $this->_oFormSession;
         return $this;
     }
_setFormSession ($sFormHashId = "", $bReset = TRUE) protected
create panel session object
Parameters
STRING $sFormHashId
BOOLEAN $bReset
Returns
void
Definition at line 933 of file Form.php.
References $_oFormSession, getFormConfig(), getFormTools(), getHash(), and getId().
Referenced by _setForm(), getSession(), setElements(), setFooter(), setFormActions(), setFormConfig(), setFormDataError(), setFormName(), setFormTemplates(), setFormTools(), setNoRenderActions(), setQuery(), and setRowActions().
{
         if (empty($sFormHashId)) {
             $sFormHashId = $this->getHash();
         }
         if ( (($this->_oFormSession === NULL) ) || $bReset) {
             $sNamespace = $this->_sFormIdPrefix . $sFormHashId;
             if ( !isset($_SESSION[$sNamespace]) ) {
                 $_SESSION[$sNamespace] = array();
             }
             $this->_oFormSession = $_SESSION[$sNamespace]; //new Zend_Session_Namespace($sNamespace);
             // $this->_oFormSession->setExpirationSeconds(300, 'accept_request');
             if ( !$this->_oFormSession["initialized"] ) {
                 $this->_oFormSession["sId"]             = $this->getId();
                 $this->_oFormSession["iRequestCount"]       = 0;
                 $this->_oFormSession["accept_request"]      = TRUE;
                 $this->_oFormSession["initialized"]     = TRUE;
             }
             if (!$bReset) {
                 //$this->_oFormSession["iRequestCount"]++;
             }
         }
         $this->_oFormSession["iRequestCount"]++;
         $this->_oFormSession["aFormConfig"]     = $this->getFormConfig();
         $this->_oFormSession["aFormTools"]      = $this->getFormTools();
         $_SESSION[$sNamespace] = $this->_oFormSession;
         return $this;
     }
_setting ($type, $name = null, $default = "") inherited
get Contenido effective CMS setting(s)
Parameters
string $type
string $name
string $default
Returns
string|array
Definition at line 223 of file Abstract.php.
{
         if ( empty($name) ) {
             return getEffectiveSettingsByType($type);
         }
         return getEffectiveSetting($type, $name, $default);
     }
_text ($text, $domain = NULL) inherited
get translated string
Parameters
string $text
string $domain
Returns
string
Definition at line 198 of file Abstract.php.
References Contenido_Object_Abstract\_con().
{
         $_mi18n = $this->_con("MI18N");
         $_string = $text;
         if ( is_array($_mi18n) && isset($_mi18n[$text]) ) {
             $_string = (string)$_mi18n[$text];
         } else
         if ( is_array($_mi18n) && is_array($_mi18n[$domain]) && isset($_mi18n[$domain][$text]) ) {
             $_string = (string)$_mi18n[$domain][$text];
         } else
         if ( ($this->_con("cnumber") !== NULL) && ( $this->_con("mi18nTranslator") !== NULL ) ) {
             $_string =  mi18n($text, $domain);
         } else {
             $_string = i18n($text, $domain);
         }
         return $_string;
     }
addNotification ($mNotifications)
Parameters
field_type $_notifications
Definition at line 1245 of file Form.php.
{
         if (is_array($mNotifications)) {
             $this->_oFormNotifications = array_merge((array)$this->_oFormNotifications, $mNotifications);
         } else if (!empty($mNotifications)) {
             $this->_oFormNotifications = array_merge((array)$this->_oFormNotifications, array($mNotifications));
         }
     }
configForm ()
overridable method to initialize user's form configurations and object options
Definition at line 181 of file Form.save.php.
{
     }
configForm ()
overridable method to initialize user's form configurations and object options
Definition at line 209 of file Form.php.
Referenced by __init().
{
     }
generate ($bReturn = TRUE)
Definition at line 500 of file Form.save.php.
References generateForm(), generateFormBottomPanel(), generateFormJS(), generateFormTopPanel(), and getFormConfig().
{
         $options = (object)$this->getFormConfig();
         $sHTML =
             (($options->showTopPanel) ? $this->generateFormTopPanel() : "").
             $this->generateForm() .
             (($options->showBottomPanel) ? $this->generateFormBottomPanel() : "") .
             (($options->generateJS) ? $this->generateFormJS($this->getFormConfig(TRUE)->oTemplates["javascript"]) : "");
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generate ($bReturn = TRUE)
Definition at line 700 of file Form.php.
References generateForm(), generateFormBottomPanel(), generateFormJS(), generateFormTopPanel(), and getFormConfig().
{
         $options = (object)$this->getFormConfig();
         $sHTML =
             (($options->showTopPanel) ? $this->generateFormTopPanel() : "").
             $this->generateForm() .
             (($options->showBottomPanel) ? $this->generateFormBottomPanel() : "") .
             (($options->generateJS) ? $this->generateFormJS($this->getFormConfig(TRUE)->oTemplates["javascript"]) : "");
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateForm ($bReturn = TRUE)
Definition at line 237 of file Form.save.php.
References $cfg, Contenido_Object_Abstract\_con(), generateFormAction(), Contenido_Object_Abstract\getCfg(), getElements(), getFooter(), getFormConfig(), getRowActions(), and Contenido_Object_Abstract\getTpl().
{
         $sHTML              = "";
         $aElements          = array();
         $aHTMLFormElements  = $this->getElements();
         $oTpl               = $this->getTpl('baseform', TRUE);
         $cfg                = $this->getCfg();
         _debug($aHTMLFormElements);
         $sHTMLFormHeader = "";
         $sHTMLFormFooter = "";
         $sHTMLFormColumnGroup = "";
         if ($this->getFormConfig(TRUE)->showHeaderRow) {
             $sHTMLFormFooter    =  +"";
         }
         if ($this->getFormConfig(TRUE)->showFooterRow) {
             $sHTMLFormFooter    = $this->getFooter();
         }
         $oTpl->template->set('s', 'php_session_id',         $this->_con('sess')->id);
         $oTpl->template->set('s', 'URLBASE',                $this->getCfg()->path['contenido_fullhtml']);
         $oTpl->template->set('s', 'NOTIFICATION',           $sPageOutput);
         $oTpl->template->set('s', 'BROWSE',                 $sPageOutput);
         $oTpl->template->set('s', 'CLICK_ROW_NOTIFICATION', $sPageOutput);
         $oTpl->template->set('s', 'HEADERS',                $sHTMLFormHeader);
         $oTpl->template->set('s', 'FOOTERS',                $sHTMLFormFooter);
         $oTpl->template->set('s', 'COLUMNGROUP',            "<columns>".$sHTMLFormColumnGroup."</columns>");
         foreach ($aHTMLFormElements as $iRow => $sRow) {
             $sActions = "";
             $sFormTitle = $aHTMLFormElements[$iRow]["name"];
             $aActions = $this->getRowActions();
             foreach ($aActions as $key => $aAction) {
                 if ( !isset($aAction["static"]) ) { $aAction["static"] = array(); }
                 $aAction["static"]["ACTIONNAME"] = $key;
                 $aAction["static"]["ACTIONCLASS"] = "con_formaction" . (($aHTMLFormElements[$iRow]["active"] != 1) ? " inactive" : "") ;
                 $aAction["static"]["ROWID"] = $aHTMLFormElements[$iRow]["id"];
                 $aAction["static"]["IDX"] = $iRow;
                 /*if ($aHTMLFormElements[$iRow]["active"] == 1) {
                     $sActions .= "<a class=\"deactivate\" href=\"#deactivate\"><img src=\"images/online.gif\" border=\"0\" alt=\"[deactivate -".$sFormTitle."-]\" title=\"deactivate\" /></a> ";
                 } else {
                     $sActions .= "<a class=\"activate\" href=\"#activate\"><img src=\"images/offline.gif\" border=\"0\" alt=\"[activate -".$sFormTitle."-]\" title=\"activate\" /></a> ";
                 }*/
                 $sActions .= $this->generateFormAction($aAction);
             }
             //$sActions .= "<input type=\"hidden\" name=\"rowid[]\" value=\"".$aForms[$iRow]["id"]."\" />";
             $sRow = str_replace("!ACTIONS_".$aHTMLFormElements[$iRow]["id"]."!", $sActions, $sRow);
             $oTpl->template->set('d', 'ROWID', "row_".$aHTMLFormElements[$iRow]["id"]);
             $oTpl->template->set('d', 'CELLS', $sRow);
             if (($iRow % 2) == 0) {
                 $oTpl->template->set('d', 'CSS_CLASS', 'even');
             } else {
                 $oTpl->template->set('d', 'CSS_CLASS', 'odd');
             }
             $oTpl->template->next();
         }
         $sHTML .= $oTpl->template->generate( $this->getFormConfig(TRUE)->oTemplates["base"], TRUE );
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateForm ($bReturn = TRUE)
Definition at line 265 of file Form.php.
References $cfg, Contenido_Object_Abstract\_con(), generateFormAction(), generateFormElements(), Contenido_Object_Abstract\getCfg(), getElements(), getFooter(), getFormConfig(), getFormName(), getId(), getNotifications(), and Contenido_Object_Abstract\getTpl().
Referenced by generate().
{
         $sHTML              = "";
         $aElements          = array();
         $aHTMLFormElements  = $this->getElements();
         $oTpl               = $this->getTpl('baseform', TRUE);
         $cfg                = $this->getCfg();
         $sHTMLFormHeader = "";
         $sHTMLFormFooter = "";
         $sHTMLFormColumnGroup = "";
         if ($this->getFormConfig(TRUE)->showHeaderRow) {
             $sHTMLFormHeader    =  "";
         }
         if ($this->getFormConfig(TRUE)->showFooterRow) {
             $sHTMLFormFooter    =   $this->getFooter();
         }
         $oTpl->template->set('s', 'php_session_id',         $this->_con('sess')->id);
         $oTpl->template->set('s', 'CONTENIDO_URL_BASE',     $this->getCfg()->path['contenido_fullhtml']);
         $oTpl->template->set('s', 'NOTIFICATION',           $sPageOutput);
         $oTpl->template->set('s', 'BROWSE',                 $sPageOutput);
         $oTpl->template->set('s', 'FORM_ID',                $this->getId());
         $oTpl->template->set('s', 'FORM_NAME',              $this->getFormName());
         $oTpl->template->set('s', 'FORM_CLASSES',           $this->getFormConfig(TRUE)->classnames);
         $oTpl->template->set('s', 'FORM_URL',               $this->getFormConfig(TRUE)->action);
         $oTpl->template->set('s', 'FORM_METHOD',            strtoupper($this->getFormConfig(TRUE)->method) );
         $oTpl->template->set('s', 'FORM_ENCTYPE',           ( isset($this->aEncTypes[strtoupper($this->getFormConfig(TRUE)->enctype)]) ) ? $this->aEncTypes[strtoupper($this->getFormConfig(TRUE)->enctype)] : $this->aEncTypes['DATA'] );
         $oTpl->template->set('s', 'FORM_TARGET',            $this->getFormConfig(TRUE)->target);
         $oTpl->template->set('s', 'FORM_NOTIFICATIONS',     implode("", (array)$this->getNotifications()) );
         $oTpl->template->set('s', 'FORM_HEADER',            $sHTMLFormHeader);
         $oTpl->template->set('s', 'FORM_FOOTER',            $sHTMLFormFooter);
         $oTpl->template->set('s', 'FORM_ACTIONS',           $this->generateFormAction($oAction));
         $oTpl->template->set('s', 'FORM_ELEMENTS',          $this->generateFormElements($aHTMLFormElements));
 //          "form"          => '{FORM_NOTIFICATIONS}<form id="{FORM_ID}" name="{FORM_NAME}" class="{FORM_CLASSES}" action="{FORM_URL}" method="{FORM_METHOD}" enctype="{FORM_ENCTYPE}" target="{FORM_TARGET}">{FORM_ELEMENTS}{FORM_ACTIONS}</form>{FORM_NOTIFICATIONS}',
         /* foreach ($aHTMLFormElements as $iRow => $sRow) {
             $sActions = "";
             $sFormTitle = $aHTMLFormElements[$iRow]["name"];
             $aActions = $this->getRowActions();
             foreach ($aActions as $key => $aAction) {
                 if ( !isset($aAction["static"]) ) { $aAction["static"] = array(); }
                 $aAction["static"]["ACTIONNAME"] = $key;
                 $aAction["static"]["ACTIONCLASS"] = "con_formaction" . (($aHTMLFormElements[$iRow]["active"] != 1) ? " inactive" : "") ;
                 $aAction["static"]["ROWID"] = $aHTMLFormElements[$iRow]["id"];
                 $aAction["static"]["IDX"] = $iRow;
                 / *if ($aHTMLFormElements[$iRow]["active"] == 1) {
                     $sActions .= "<a class=\"deactivate\" href=\"#deactivate\"><img src=\"images/online.gif\" border=\"0\" alt=\"[deactivate -".$sFormTitle."-]\" title=\"deactivate\" /></a> ";
                 } else {
                     $sActions .= "<a class=\"activate\" href=\"#activate\"><img src=\"images/offline.gif\" border=\"0\" alt=\"[activate -".$sFormTitle."-]\" title=\"activate\" /></a> ";
                 }* /
                 $sActions .= $this->generateFormAction($aAction);
             }
             //$sActions .= "<input type=\"hidden\" name=\"rowid[]\" value=\"".$aForms[$iRow]["id"]."\" />";
             $sRow = str_replace("!ACTIONS_".$aHTMLFormElements[$iRow]["id"]."!", $sActions, $sRow);
             $oTpl->template->set('d', 'ROWID', "row_".$aHTMLFormElements[$iRow]["id"]);
             $oTpl->template->set('d', 'CELLS', $sRow);
             if (($iRow % 2) == 0) {
                 $oTpl->template->set('d', 'CSS_CLASS', 'even');
             } else {
                 $oTpl->template->set('d', 'CSS_CLASS', 'odd');
             }
             $oTpl->template->next();
         } */
         $sHTML .= $oTpl->template->generate( $this->getFormConfig(TRUE)->oTemplates["form"], TRUE );
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateFormAction ($oAction, $bReturn = TRUE)
Definition at line 338 of file Form.save.php.
References $action, $area, Contenido_Object_Abstract\_con(), Contenido_Object_Abstract\getTpl(), and Contenido_Object_Abstract\setTplVars().
{
         if (is_array($oAction)) { $oAction = (object)$oAction; }
         $sHTML  = "";
         if ( !empty($oAction->template) ) {
             $accessGranted  = true;
             $area           = $this->_con('area');
             $action         = $this->_con('action');
             $plugin_name    = $this->_con('plugin_name');
             if ( defined('CON_FRAMEWORK') && !empty($plugin_name) && !empty($area) && !empty($action) ) {
                 // if we are in a plugin context, check for access permission...
                 $accessGranted = $this->_con('perm')->have_perm_area_action($area, $action);
             }
             $oActionTpl = $this->getTpl('rowaction', TRUE);
             $this->setTplVars('rowaction', $oAction);
             if ( !$accessGranted && !empty($oAction->_template) ) {
                 $sHTML .= $oActionTpl->template->generate($oAction->_template, TRUE);
             } else {
                 $sHTML .= $oActionTpl->template->generate($oAction->template, TRUE);
             }
         }
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateFormAction ($oAction, $bReturn = TRUE)
Definition at line 537 of file Form.php.
References $action, $area, Contenido_Object_Abstract\_con(), Contenido_Object_Abstract\getTpl(), and Contenido_Object_Abstract\setTplVars().
Referenced by generateForm().
{
         if (is_array($oAction)) { $oAction = (object)$oAction; }
         $sHTML  = "";
         if ( !empty($oAction->template) ) {
             $accessGranted  = true;
             $area           = $this->_con('area');
             $action         = $this->_con('action');
             $plugin_name    = $this->_con('plugin_name');
             if ( defined('CON_FRAMEWORK') && !empty($plugin_name) && !empty($area) && !empty($action) ) {
                 // if we are in a plugin context, check for access permission...
                 $accessGranted = $this->_con('perm')->have_perm_area_action($area, $action);
             }
             $oActionTpl = $this->getTpl('rowaction', TRUE);
             $this->setTplVars('rowaction', $oAction);
             if ( !$accessGranted && !empty($oAction->_template) ) {
                 $sHTML .= $oActionTpl->template->generate($oAction->_template, TRUE);
             } else {
                 $sHTML .= $oActionTpl->template->generate($oAction->template, TRUE);
             }
         }
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateFormBottomPanel ($bReturn = TRUE)
Definition at line 475 of file Form.save.php.
References generateFormTools(), and getFormConfig().
{
         $sHTML  = "";
         $sHTML .= $this->generateFormTools( $this->getFormConfig(TRUE)->oTemplates["bottom"] );
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateFormBottomPanel ($bReturn = TRUE)
Definition at line 674 of file Form.php.
References generateFormTools(), and getFormConfig().
Referenced by generate().
{
         $sHTML  = "";
         $sHTML .= $this->generateFormTools( $this->getFormConfig(TRUE)->oTemplates["bottom"] );
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateFormElementAction ($oAction, $bReturn = TRUE)
Definition at line 503 of file Form.php.
References $action, $area, Contenido_Object_Abstract\_con(), getFormConfig(), and Contenido_Object_Abstract\getTpl().
{
         if (is_array($oAction)) { $oAction = (object)$oAction; }
         $sHTML  = "";
         if ( !empty( $this->getFormConfig(TRUE)->oTemplates["elementaction"] ) ) {
             $accessGranted  = true;
             $area           = $this->_con('area');
             $action         = $this->_con('action');
             $plugin_name    = $this->_con('plugin_name');
             if ( defined('CON_FRAMEWORK') && !empty($plugin_name) && !empty($area) && !empty($action) ) {
                 // if we are in a plugin context, check for access permission...
                 $accessGranted = $this->_con('perm')->have_perm_area_action($area, $action);
             }
             $oActionTpl = $this->getTpl('elementaction', TRUE);
             $oActionTpl->template->set('s', 'FORM_ELEMENTACTION_CLASSES', "formElementAction ".$oAction->classnames);
             $oActionTpl->template->set('s', 'FORM_ELEMENTACTION_LABEL', $oAction->label);
             $oActionTpl->template->set('s', 'FORM_ELEMENTACTION_ID', "formAction_".$oAction->name."_".$oAction->element->fieldid);
             $aActionTrigger = array(
                 '<a href="#" title="'.$oAction->label.'">', '</a>'
             );
             $oActionTpl->template->set('s', 'FORM_ELEMENTACTION_CONTROL', implode("", $aActionTrigger));
             if ( !$accessGranted && !empty($oAction->_template) ) {
                 $sHTML .= $oActionTpl->template->generate($this->getFormConfig(TRUE)->oTemplates["elementaction"], TRUE);
             } else {
                 $sHTML .= $oActionTpl->template->generate($this->getFormConfig(TRUE)->oTemplates["elementaction"], TRUE);
             }
         }
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateFormElements ($aElements = array(), $parent = NULL, $level = 0, $bReturn = TRUE)
Definition at line 305 of file Form.save.php.
References generateFormElements(), and getFormConfig().
{
         $sHTML = "";
         foreach ($aElements as $key => $element) {
             $element = (object)$element;
             if ( ($element->type == 'fieldset') && (is_array($element->elements)) ) {
                 $sHTML .= $this->getFormConfig(TRUE)->oTemplates["fieldset"];
                 $sHTML .= $this->generateFormElements($element->elements, $element, ++$level, $bReturn);
             } else {
                 switch ($element->type) {
                     case 'date'     : break;
                     case 'digit'    : break;
                     case 'email'    : break;
                     case 'range'    : break;
                     case 'file'     : break;
                     case 'hidden'   : break;
                     case 'inList'   : break;
                     case 'url'      : break;
                     case 'oneWord'  : break;
                     default: /* text */ break;
                 }
                 $sHTML .= $this->getFormConfig(TRUE)->oTemplates["element"];
             }
         }
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateFormElements ($aElements = NULL, $parent = NULL, $level = 0, $bReturn = TRUE)
Definition at line 346 of file Form.php.
References getFormConfig(), and Contenido_Object_Abstract\getTpl().
Referenced by generateForm(), and generateFormElements().
{
         $sHTML = "";
         if ( !is_array($aElements) ) {
             return "";
         }
         foreach ($aElements as $key => $element) {
             if ( is_array($element) ) { $element = (object)$element; }
             if ( ($element->type == 'fieldset') && (is_array($element->elements)) ) {
                 // generate fieldset mark-up
                 $element->fieldID = ( ($parent != NULL) ? $parent->fieldID . '_' : $this->getId() . '_' ). 'fieldset_'.$level.'_'.$key;
                 $sElementsHTML = $this->generateFormElements($element->elements, $element, 1+$level, $bReturn);
                 $oTpl = $this->getTpl('fieldset_'.$level.'_'.$key, TRUE);
                 $oTpl->template->set('s', 'FORM_FIELDSET_CLASSES'   , "formFieldset ".$element->class);
                 $oTpl->template->set('s', 'FORM_FIELDSET_ELEMENTS'  , $sElementsHTML);
                 $oTpl->template->set('s', 'FORM_FIELDSET_CAPTION'   , $element->label);
                 $sHTML .= $oTpl->template->generate( $this->getFormConfig(TRUE)->oTemplates["fieldset"], TRUE );
             } else {
                 // generate singe form control mark-up
                 $sInputHTML     =   "";
                 $bRequired      =   ($element->required === true);
                 $bError         =   ($element->error != false);
                 $sClassnames    =
                     "formInput".
                     " ".$element->field."".
                     (($bRequired) ? " required" : "").
                     (($bError) ? " error" : "").
                     (($element->classnames) ? " ".$element->classnames : "");
                 $sAttributes = "";
                 if ( is_array($element->attr) ) {
                     foreach ($element->attr as $key => $value) {
                         $sAttributes .= " ".($key)."=\"".($value)."\"";
                     }
                 }
                 $element->fieldID =  ( ($parent != NULL) ? $parent->fieldID . '_' : $this->getId() . '_' ). 'element_'.$element->field.'_'.$level.'_'.$key;
                 switch ($element->type) {
                     case "select":
                         $sInputHTML = "<select ".
                             "id=\"".$element->fieldID."\" ".
                             "name=\"".$element->field."\" ".
                             "class=\"".$sClassnames."\" ".
                             "size=\"".(((int)$element->size > 0) ? (int)$element->size : 1)."\" ".
                         ">".
                             "!_SELECTOPTIONS_".$element->field."_!".
                         "</select>";
                         $sSelectOptions = "";
                         if ( is_array($element->options) ) {
                             foreach ($element->options as $key => $oOption) {
                                 $sSelectOptions .= "<option ".
                                     "value=\"".$oOption["value"]."\" ".
                                         ( ( !is_array($element->value) && ($oOption["value"] == $element->value) ) ? "selected=\"selected\" " : "" ).
                                         ( ( is_array($element->value) && in_array($oOption["value"], $element->value) ) ? "selected=\"selected\" " : "" ).
                                 ">".
                                     "".$oOption["text"]."".
                                 "</option>";
                             }
                         }
                         $sInputHTML = str_replace("!_SELECTOPTIONS_".$element->field."_!", $sSelectOptions, $sInputHTML);
                     break;
                     case "radio":
                     case "checkbox":
                         $sInputHTML = "<ul class=\"".$element->type."list\">";
                         if ( is_array($element->options) ) {
                             foreach ($element->options as $key => $oOption) {
                                 $sInputHTML .= "<li>".
                                     "<label>".
                                         "<input ".
                                             "id=\"".$element->fieldID."_".$key."\" ".
                                             "type=\"".$element->type."\" ".
                                             "name=\"".$element->field."\" ".
                                             "class=\"".$sClassnames."\" ".
                                             "value=\"".$oOption["value"]."\" ".
                                                 ( ( !is_array($element->value) && ($oOption["value"] == $element->value) ) ? "checked=\"checked\" " : "" ).
                                                 ( ( is_array($element->value) && in_array($oOption["value"], $element->value) ) ? "checked=\"checked\" " : "" ).
                                             (!empty($sAttributes) ? $sAttributes : "").
                                         "/>".
                                         "".$oOption["text"]."".
                                     "</label>".
                                 "</li>";
                             }
                         } else {
                             $sInputHTML = "";
                         }
                         if ( !empty($sInputHTML) ) {
                             $sInputHTML .= "</ul>";
                         }
                     break;
                     case "textarea":
                         $sInputHTML = "<textarea ".
                             "id=\"".$element->fieldID."\" ".
                             "name=\"".$element->field."\" ".
                             "class=\"".$sClassnames."\" ".
                             (((int)$element->rows > 0) ? "rows=\"".((int)$element->rows)."\" " : "").
                             (((int)$element->cols > 0) ? "cols=\"".((int)$element->cols)."\" " : "").
                             (!empty($sAttributes) ? $sAttributes : "").
                             ">".
                             $element->value.
                         "</textarea>";
                     break;
                     default:
                         if ( !in_array( strtolower($element->type), (array)$this->types ) ) {
                             $sType = "text";
                         } else  {
                             $sType = strtolower($element->type);
                         }
                         $sInputHTML = "<input ".
                             "id=\"".$element->fieldID."\" ".
                             "type=\"".$sType."\" ".
                             "name=\"".$element->field."\" ".
                             "class=\"".$sClassnames."\" ".
                             "value=\"".$element->value."\" ".
                             (((int)$element->size > 0) ? "size=\"".((int)$element->size)."\" " : "").
                             (!empty($sAttributes) ? $sAttributes : "").
                             "/>";
                     break;
                 }
                 if ( isset($element->setHTML) && !empty($element->setHTML) ) {
                     $sInputHTML = trim($element->setHTML, " \n\t\r");
                 }
                 $sElementActions = "";
                 if ( isset($element->actions) && is_array($element->actions) ) {
                     foreach ($element->actions as $key => $oAction) {
                         $oAction["element"] = $element;
                         $sElementActions .= "".$this->generateFormElementAction($oAction);
                     }
                 }
                 $oTpl = $this->getTpl('element_'.$element->field.'_'.$level.'_'.$key, TRUE);
                 $oTpl->template->set('s', 'FORM_ELEMENT_ID'                 , $element->fieldID);
                 $oTpl->template->set('s', 'FORM_ELEMENT_LABEL'              , $element->title);
                 $oTpl->template->set('s', 'FORM_ELEMENT_LABEL_CLASSES'      , "formLabel");
                 $oTpl->template->set('s', 'FORM_ELEMENT_CONTROL'            , $sInputHTML);
                 $oTpl->template->set('s', 'FORM_ELEMENT_ACTIONS'            , $sElementActions);
                 $oTpl->template->set('s', 'FORM_ELEMENT_ACTIONS_CLASSES'    , "formElementActions");
                 $sHTML .= $oTpl->template->generate( $this->getFormConfig(TRUE)->oTemplates["element"], TRUE );
             }
         }
         /*
         "oTemplates"        => array(                       // path to form templates
             "form"          => '{FORM_NOTIFICATIONS}<form id="{FORM_ID}" name="{FORM_NAME}" class="{FORM_CLASSES}" action="{FORM_URL}" method="{FORM_METHOD}" enctype="{FORM_ENCTYPE}" target="{FORM_TARGET}">{FORM_ELEMENTS}{FORM_ACTIONS}</form>{FORM_NOTIFICATIONS}',
             "fieldset"      => '<fieldset class="{FORM_FIELDSET_CLASSES}"><legend>{FORM_FIELDSET_CAPTION}<legend>{FORM_FIELDSET_ELEMENTS}</fieldset>',
             "element"       => '<label class="{FORM_ELEMENT_LABEL_CLASSES}" for="{FORM_ELEMENT_ID}"><span class="label">{FORM_ELEMENT_LABEL}</span>{FORM_ELEMENT_CONTROL}</label><span class="{FORM_ELEMENT_ACTIONS_CLASSES}">{FORM_ELEMENT_ACTIONS}</span>',
             "elementaction" => '<span class="{FORM_ELEMENTACTION_CLASSES}" for="{FORM_ELEMENTACTION_ID}"><span class="label">{FORM_ELEMENTACTION_LABEL}</span><span class="control">{FORM_ELEMENTACTION_CONTROL}</span></span>',
             "actions"       => '<li><span class="{FORM_ACTIONS_CLASSES}">{FORM_RESET}{FORM_SUBMIT}</span></li>',
             "notifications" => '{FORM_PROCESS_ERRORS}{FORM_PROCESS_NOTIFICATIONS}',
             "javascript"    => '<script type="text/javascript">var oForm = new Contenido_Plugin_Form(FORM_CONFIG_JSON);</script>',
         ),
         */
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateFormJS ($sJSTemplate = "", $bReturn = TRUE)
Definition at line 485 of file Form.save.php.
References getFormConfig(), Contenido_Object_Abstract\getTpl(), and Contenido_Object_Abstract\setTplVars().
{
         $this->getTpl("formJS", TRUE);
         $this->setTplVars("formJS", array(
             "static" => array(
                 "TABLE_CONFIG_JSON" => json_encode($this->getFormConfig(TRUE)),
             )
         ));
         $sJS = $this->getTpl("formJS")->template->generate($sJSTemplate, TRUE);
         if ($bReturn) {
             return ($sJS);
         }
         echo ($sJS);
         return ($this);
     }
generateFormJS ($sJSTemplate = "", $bReturn = TRUE)
Definition at line 684 of file Form.php.
References getFormConfig(), getId(), Contenido_Object_Abstract\getTpl(), and Contenido_Object_Abstract\setTplVars().
Referenced by generate().
{
         $this->getTpl("formJS", TRUE);
         $this->setTplVars("formJS", array(
             "static" => array(
                 "FORM_ID" => ($this->getId()),
                 "FORM_CONFIG_JSON" => json_encode($this->getFormConfig(TRUE)),
             )
         ));
         $sJS = $this->getTpl("formJS")->template->generate($sJSTemplate, TRUE);
         if ($bReturn) {
             return ($sJS);
         }
         echo ($sJS);
         return ($this);
     }
generateFormTools ($sTemplate = "", $bReturn = TRUE)
Definition at line 366 of file Form.save.php.
References generateFormToolsActions(), generateFormToolsPagination(), getFormConfig(), getFormTools(), and Contenido_Object_Abstract\getTpl().
{
         $sHTML  = "";
         if ( !empty($sTemplate) ) {
             $config     = $this->getFormConfig(TRUE);
             $tools      = $this->getFormTools(TRUE);
             $oToolTpl   = $this->getTpl('formtools', TRUE);
             $seperator  = " || ";
             $sPaginationOutput  = (!$config->pagination)    ? null : $this->generateFormToolsPagination($tools->page, $tools->pageCount);
             $sFormActions       = (!$config->formActions)   ? null : $this->generateFormToolsActions();
             $oToolTpl->template->set('s', 'FORM_TOOLS_CLASSNAMES',      "formTools");
             $oToolTpl->template->set('s', 'FORM_TOOLS_PAGINATION',      trim(implode($seperator, array(
                 $sPaginationOutput, $sRowsPerPageOutput,
             )) , " |"));
             $oToolTpl->template->set('s', 'FORM_TOOLS_ACTIONS',     $sFormActions);
             $oToolTpl->template->set('s', 'FORM_NOTIFICATIONS',             ""); //$sToolNotificationOutput);
             $sHTML .= $oToolTpl->template->generate( $sTemplate,    true );
         }
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateFormTools ($sTemplate = "", $bReturn = TRUE)
Definition at line 565 of file Form.php.
References generateFormToolsActions(), generateFormToolsPagination(), getFormConfig(), getFormTools(), and Contenido_Object_Abstract\getTpl().
Referenced by generateFormBottomPanel(), and generateFormTopPanel().
{
         $sHTML  = "";
         if ( !empty($sTemplate) ) {
             $config     = $this->getFormConfig(TRUE);
             $tools      = $this->getFormTools(TRUE);
             $oToolTpl   = $this->getTpl('formtools', TRUE);
             $seperator  = " || ";
             $sPaginationOutput  = (!$config->pagination)    ? null : $this->generateFormToolsPagination($tools->page, $tools->pageCount);
             $sFormActions       = (!$config->formActions)   ? null : $this->generateFormToolsActions();
             $oToolTpl->template->set('s', 'FORM_TOOLS_CLASSNAMES',      "formTools");
             $oToolTpl->template->set('s', 'FORM_TOOLS_PAGINATION',      trim(implode($seperator, array(
                 $sPaginationOutput, $sRowsPerPageOutput,
             )) , " |"));
             $oToolTpl->template->set('s', 'FORM_TOOLS_ACTIONS',     $sFormActions);
             $oToolTpl->template->set('s', 'FORM_NOTIFICATIONS',             ""); //$sToolNotificationOutput);
             $sHTML .= $oToolTpl->template->generate( $sTemplate,    true );
         }
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateFormToolsActions ($bReturn = TRUE)
Definition at line 430 of file Form.save.php.
References Contenido_Object_Abstract\_con(), and Contenido_Object_Abstract\getCfg().
{
         $sHTML  = "";
         $sFormActions                   = '<ul class="formActionList">'.
             ( ( $this->_con('perm')->have_perm_area_action($this->_con('plugin_name'), "createform") ) ? '<li class="formActionItem">'. sprintf(
                 $this->getCfg()->templates[$this->_con('plugin_name').'_multilink_3Frames'],
                 "con_link_icon createfunction",
                 "left_bottom",
                 $this->_con('sess')->url("main.php?". "area=".$this->_con('plugin_name') ."&". "frame="."2" ."&". "actionarea="."forms" ."&". "action="."createform"),
                 "right_top",
                 $this->_con('sess')->url("main.php?". "area=".$this->_con('plugin_name') ."&". "frame="."3" ."&". "actionarea="."forms" ."&". "action="."createform"),
                 "right_bottom",
                 $this->_con('sess')->url("main.php?". "area=".$this->_con('plugin_name') ."&". "frame="."4" ."&". "actionarea="."forms" ."&". "action="."createform"),
                 i18n("create new form")
             ) ."</li>" : "" ) .
         /*( ( $perm->have_perm_area_action($plugin_name, "reportoverview") ) ? '<li class="formActionItem">'. sprintf(
                 $cfg['templates'][$plugin_name.'_multilink_3Frames'],
                 "con_link_icon openoverview",
                 "left_bottom",
                 $sess->url("main.php?". "area=".$oPlugin->_con('plugin_name') ."&". "frame="."2" ."&". "actionarea="."reports" ."&". "action="."reportoverview"),
                 "right_top",
                 $sess->url("main.php?". "area=".$oPlugin->_con('plugin_name') ."&". "frame="."3" ."&". "actionarea="."reports" ."&". "action="."reportoverview"),
                 "right_bottom",
                 $sess->url("main.php?". "area=".$oPlugin->_con('plugin_name') ."&". "frame="."4" ."&". "actionarea="."reports" ."&". "action="."reportoverview"),
                 i18n("form reports")
             ) ."</li>" : "" ) .*/
         "</ul>";
         $sHTML .= $sFormActions;
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateFormToolsActions ($bReturn = TRUE)
Definition at line 629 of file Form.php.
References Contenido_Object_Abstract\_con(), and Contenido_Object_Abstract\getCfg().
Referenced by generateFormTools().
{
         $sHTML  = "";
         $sFormActions                   = '<ul class="formActionList">'.
             ( ( $this->_con('perm')->have_perm_area_action($this->_con('plugin_name'), "createform") ) ? '<li class="formActionItem">'. sprintf(
                 $this->getCfg()->templates[$this->_con('plugin_name').'_multilink_3Frames'],
                 "con_link_icon createfunction",
                 "left_bottom",
                 $this->_con('sess')->url("main.php?". "area=".$this->_con('plugin_name') ."&". "frame="."2" ."&". "actionarea="."forms" ."&". "action="."createform"),
                 "right_top",
                 $this->_con('sess')->url("main.php?". "area=".$this->_con('plugin_name') ."&". "frame="."3" ."&". "actionarea="."forms" ."&". "action="."createform"),
                 "right_bottom",
                 $this->_con('sess')->url("main.php?". "area=".$this->_con('plugin_name') ."&". "frame="."4" ."&". "actionarea="."forms" ."&". "action="."createform"),
                 i18n("create new form")
             ) ."</li>" : "" ) .
         /*( ( $perm->have_perm_area_action($plugin_name, "reportoverview") ) ? '<li class="formActionItem">'. sprintf(
                 $cfg['templates'][$plugin_name.'_multilink_3Frames'],
                 "con_link_icon openoverview",
                 "left_bottom",
                 $sess->url("main.php?". "area=".$oPlugin->_con('plugin_name') ."&". "frame="."2" ."&". "actionarea="."reports" ."&". "action="."reportoverview"),
                 "right_top",
                 $sess->url("main.php?". "area=".$oPlugin->_con('plugin_name') ."&". "frame="."3" ."&". "actionarea="."reports" ."&". "action="."reportoverview"),
                 "right_bottom",
                 $sess->url("main.php?". "area=".$oPlugin->_con('plugin_name') ."&". "frame="."4" ."&". "actionarea="."reports" ."&". "action="."reportoverview"),
                 i18n("form reports")
             ) ."</li>" : "" ) .*/
         "</ul>";
         $sHTML .= $sFormActions;
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateFormToolsNotification ($sMessage = "", $bReturn = TRUE)
Definition at line 416 of file Form.save.php.
{
         $sHTML  = "";
         if ( !empty($sTemplate) ) {
             $sToolNotificationOutput        = '';
             //...
             $sHTML .= $sToolNotificationOutput;
         }
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateFormToolsNotification ($sMessage = "", $bReturn = TRUE)
Definition at line 615 of file Form.php.
{
         $sHTML  = "";
         if ( !empty($sTemplate) ) {
             $sToolNotificationOutput        = '';
             //...
             $sHTML .= $sToolNotificationOutput;
         }
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateFormToolsPagination ($sPageStart = "", $sRowsPerPage = 15, $bReturn = TRUE)
Definition at line 392 of file Form.save.php.
{
         $sHTML  = "";
         $iRows  = count($this->getRows(TRUE));
         $sPageBrowserOutput = i18n("go to page").' '. '<span class="input">'.
             '<select id="ePageStart" name="page" class="text_medium text_right" onchange="/*artSort(this)*/">';
             if ( !is_numeric($sRowsPerPage) ) {
                 $pages = 1;
             } else {
                 $pages = (int)(($iRows) / (int)$sRowsPerPage)    +   ( ( ($iRows % (int)$sRowsPerPage) > 0) ? 1 : 0 );
             }
             for ($i = 1; $i <= $pages; $i++) {
                 $sPageBrowserOutput .= '<option value="'.($i).'"'.
                     ( ($sPageStart == ($i-1)) ? ' selected="selected"' : '' ) .
                 '>'.$i.'</option>';
             }
         $sPageBrowserOutput .= '</select> '; // . Contenido_Plugin_GUI::submitImage('browse', 'images/submit.gif');
         $sHTML .= $sPageBrowserOutput;
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateFormToolsPagination ($sPageStart = "", $sRowsPerPage = 15, $bReturn = TRUE)
Definition at line 591 of file Form.php.
Referenced by generateFormTools().
{
         $sHTML  = "";
         $iRows  = count($this->getRows(TRUE));
         $sPageBrowserOutput = i18n("go to page").' '. '<span class="input">'.
             '<select id="ePageStart" name="page" class="text_medium text_right" onchange="/*artSort(this)*/">';
             if ( !is_numeric($sRowsPerPage) ) {
                 $pages = 1;
             } else {
                 $pages = (int)(($iRows) / (int)$sRowsPerPage)    +   ( ( ($iRows % (int)$sRowsPerPage) > 0) ? 1 : 0 );
             }
             for ($i = 1; $i <= $pages; $i++) {
                 $sPageBrowserOutput .= '<option value="'.($i).'"'.
                     ( ($sPageStart == ($i-1)) ? ' selected="selected"' : '' ) .
                 '>'.$i.'</option>';
             }
         $sPageBrowserOutput .= '</select> '; // . Contenido_Plugin_GUI::submitImage('browse', 'images/submit.gif');
         $sHTML .= $sPageBrowserOutput;
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateFormTopPanel ($bReturn = TRUE)
Definition at line 465 of file Form.save.php.
References generateFormTools(), and getFormConfig().
{
         $sHTML  = "";
         $sHTML .= $this->generateFormTools( $this->getFormConfig(TRUE)->oTemplates["top"] );
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
generateFormTopPanel ($bReturn = TRUE)
Definition at line 664 of file Form.php.
References generateFormTools(), and getFormConfig().
Referenced by generate().
{
         $sHTML  = "";
         $sHTML .= $this->generateFormTools( $this->getFormConfig(TRUE)->oTemplates["top"] );
         if ($bReturn) {
             return ($sHTML);
         }
         echo ($sHTML);
         return ($this);
     }
getAuth () inherited
return Contenido authorization object
Returns
stdClass|array
Definition at line 458 of file Abstract.php.
References Contenido_Object_Abstract\getConfig().
Referenced by Contenido_Object_Abstract\getAuthId().
{
         return (object)$this->getConfig()->auth->auth;
     }
getAuthId () inherited
return Contenido authorized user id
Returns
string
Definition at line 466 of file Abstract.php.
References Contenido_Object_Abstract\getAuth().
Referenced by Contenido_Object_Abstract\isAuthNobody().
{
         return $this->getAuth()->uid;
     }
getCfg () inherited
return Contenido configuration
Returns
stdClass|array
Definition at line 442 of file Abstract.php.
References Contenido_Object_Abstract\getConfig().
Referenced by generateForm(), generateFormToolsActions(), Contenido_Plugin_GUI_Table\generateTable(), Contenido_Plugin_GUI_Table\generateTableToolsActions(), Contenido_Plugin_GUI\page_close(), and Contenido_Plugin_GUI\page_open().
{
         return (object)$this->getConfig()->cfg;
     }
getCfgClient () inherited
return Contenido client configuration
Returns
stdClass|array
Definition at line 450 of file Abstract.php.
References Contenido_Object_Abstract\getConfig().
{
         return (object)$this->getConfig()->cfgClient;
     }
getConfig () inherited
return configuration settings array
Returns
stdClass|array
Definition at line 253 of file Abstract.php.
References Contenido_Object_Abstract\$_config.
Referenced by Contenido_Plugin_GUI\generateNavigationList(), Contenido_Object_Abstract\getAuth(), Contenido_Object_Abstract\getCfg(), Contenido_Object_Abstract\getCfgClient(), Contenido_Plugin_GUI\getFrameTemplate(), Contenido_Object_Abstract\isDebug(), and validateFormElements().
{
         return (object)$this->_config;
     }
getDb ($db = null) inherited
get (current) instance of DB_Contenido
Parameters
DB_Contenido $db
Returns
DB_Contenido
Definition at line 357 of file Abstract.php.
Referenced by __init(), Contenido_Plugin_GUI_Table\__init(), Contenido_Plugin_GUI_Table\_buildEqualLikeWhere(), _buildEqualLikeWhere(), _buildQuery(), Contenido_Plugin_GUI_Table\_buildTableQuery(), _getDbFormColumns(), Contenido_Plugin_GUI_Table\_getDbTableColumns(), Contenido_Plugin_GUI_Table\_loadDbData(), _loadDbData(), _setForm(), and Contenido_Plugin_GUI_Table\_setTable().
{
         if ( $this->_db instanceof DB_Contenido ) {
             return ($this->_db);
         }
         if ($db instanceof DB_Contenido) {
             $this->_db = $db;
         } else {
             $this->_db = new DB_Contenido;
         }
         return ($this->_db);
     }
getElements ()
Returns
ARRAY $_aElements
Definition at line 766 of file Form.save.php.
References $_aElements.
{
         return (array)$this->_aElements;
     }
getElements ()
Returns
ARRAY $_aElements
Definition at line 966 of file Form.php.
References $_aElements.
Referenced by _getMaxPages(), and generateForm().
{
         return (array)$this->_aElements;
     }
getFooter ()
Returns
ARRAY $_aFooterCells
Definition at line 784 of file Form.save.php.
{
         return (array)$this->_aFooterCells;
     }
getFooter ()
Returns
ARRAY $_aFooterCells
Definition at line 984 of file Form.php.
Referenced by generateForm().
{
         return (array)$this->_aFooterCells;
     }
getFormActions ($asObject = FALSE)
Returns
OBJECT $_oFormConfig["oRowActions"]
Definition at line 916 of file Form.save.php.
{
         return ($asObject) ? (object)$this->_oFormConfig["oFormActions"] : (array)$this->_oFormConfig["oFormActions"] ;
     }
getFormActions ($asObject = FALSE)
Returns
OBJECT $_oFormConfig["oRowActions"]
Definition at line 1116 of file Form.php.
{
         return ($asObject) ? (object)$this->_oFormConfig["oFormActions"] : (array)$this->_oFormConfig["oFormActions"] ;
     }
getFormConfig ($asObject = FALSE)
Returns
ARRAY $_oFormConfig
Definition at line 899 of file Form.save.php.
References $_oFormConfig.
{
         return ($asObject) ? (object)$this->_oFormConfig : (array)$this->_oFormConfig;
     }
getFormConfig ($asObject = FALSE)
Returns
ARRAY $_oFormConfig
Definition at line 1099 of file Form.php.
References $_oFormConfig.
Referenced by __init(), _setFormSession(), generate(), generateForm(), generateFormBottomPanel(), generateFormElementAction(), generateFormElements(), generateFormJS(), generateFormTools(), generateFormTopPanel(), and getFormToolsURL().
{
         return ($asObject) ? (object)$this->_oFormConfig : (array)$this->_oFormConfig;
     }
getFormName ()
Returns
the $_sFormName
Definition at line 882 of file Form.save.php.
References $_sFormName.
{
         return $this->_sFormName;
     }
getFormName ()
Returns
the $_sFormName
Definition at line 1082 of file Form.php.
References $_sFormName.
Referenced by _buildQuery(), _getDbFormColumns(), generateForm(), and getQuery().
{
         return $this->_sFormName;
     }
getFormTemplates ($asObject = FALSE)
Returns
OBJECT $_oFormTools
Definition at line 933 of file Form.save.php.
{
         return ($asObject) ? (object)$this->_oFormConfig["oTemplates"] : (array)$this->_oFormConfig["oTemplates"];
     }
getFormTemplates ($asObject = FALSE)
Returns
OBJECT $_oFormTools
Definition at line 1133 of file Form.php.
{
         return ($asObject) ? (object)$this->_oFormConfig["oTemplates"] : (array)$this->_oFormConfig["oTemplates"];
     }
getFormTools ($asObject = FALSE)
Returns
OBJECT $_oFormTools
Definition at line 950 of file Form.save.php.
References $_oFormTools.
{
         return ($asObject) ? (object)$this->_oFormTools : (array)$this->_oFormTools;
     }
getFormTools ($asObject = FALSE)
Returns
OBJECT $_oFormTools
Definition at line 1150 of file Form.php.
References $_oFormTools.
Referenced by __init(), _buildQuery(), _parseToolsParams(), _setFormSession(), and generateFormTools().
{
         return ($asObject) ? (object)$this->_oFormTools : (array)$this->_oFormTools;
     }
getFormToolsURL ()
Returns
STRING $_oFormToolsURL
Definition at line 968 of file Form.save.php.
References $cfg, and getFormConfig().
{
         $cfg = $this->getFormConfig();
         return $cfg["url"];
     }
getFormToolsURL ()
Returns
STRING $_oFormToolsURL
Definition at line 1168 of file Form.php.
References $cfg, and getFormConfig().
{
         $cfg = $this->getFormConfig();
         return $cfg["url"];
     }
getHash () protected
get panel hash id
Returns
STRING
Definition at line 686 of file Form.save.php.
References $_sFormHashId, and _setFormHashId().
{
         if (empty($this->_sFormHashId)) {
             $this->_setFormHashId();
         }
         return $this->_sFormHashId;
     }
getHash () protected
get panel hash id
Returns
STRING
Definition at line 886 of file Form.php.
References $_sFormHashId, and _setFormHashId().
Referenced by __init(), and _setFormSession().
{
         if (empty($this->_sFormHashId)) {
             $this->_setFormHashId();
         }
         return $this->_sFormHashId;
     }
getId () protected
get panel's element id
Returns
STRING
Definition at line 662 of file Form.save.php.
References $_sFormId, and _setFormId().
{
         if (empty($this->_sFormId)) {
             $this->_setFormId();
         }
         return $this->_sFormId;
     }
getId () protected
get panel's element id
Returns
STRING
Definition at line 862 of file Form.php.
References $_sFormId, and _setFormId().
Referenced by __init(), _setFormSession(), generateForm(), and generateFormJS().
{
         if (empty($this->_sFormId)) {
             $this->_setFormId();
         }
         return $this->_sFormId;
     }
static getInstance ($options = array()) static inherited
get singelton instance object
Parameters
array | stdClass $config
Returns
Contenido_Object_Abstract
Definition at line 102 of file Abstract.php.
{
         if ( self::$_instance === NULL ) {
             self::$_instance = new self( $options );
         }
         return self::$_instance;
     }
getNoRenderActions ()
Returns
ARRAY $aNoRenderActions
Definition at line 976 of file Form.save.php.
References $aNoRenderActions.
{
         return $this->aNoRenderActions;
     }
getNoRenderActions ()
Returns
ARRAY $aNoRenderActions
Definition at line 1176 of file Form.php.
References $aNoRenderActions.
{
         return $this->aNoRenderActions;
     }
getNotifications ($sMode = "")
Returns
the $_oFormNotifications
Definition at line 1230 of file Form.php.
References $_oFormNotifications.
Referenced by generateForm().
{
         switch ($sMode) {
             case 1 :
                 return (array)$this->_oFormNotifications;
             break;
             default:
                 return implode("", (array)$this->_oFormNotifications);
             break;
         }
     }
getOptions () inherited
get object options array
Returns
array|stdClass
Definition at line 374 of file Abstract.php.
References Contenido_Object_Abstract\$_options.
Referenced by Contenido_Object_Abstract\setOptions().
{
         return (array)$this->_options;
     }
getQuery ()
Returns
STRING $_sQuery
Definition at line 822 of file Form.save.php.
References $_sQuery, _buildQuery(), and getFormName().
{
         $formName = trim($this->getFormName());
         if ( !empty( $formName ) ) {
             $this->_buildQuery();
         } else {
             return (FALSE);
         }
         return $this->_sQuery;
     }
getQuery ()
Returns
STRING $_sQuery
Definition at line 1022 of file Form.php.
References $_sQuery, _buildQuery(), and getFormName().
Referenced by _loadDbData().
{
         $formName = trim($this->getFormName());
         if ( !empty( $formName ) ) {
             $this->_buildQuery();
         } else {
             return (FALSE);
         }
         return $this->_sQuery;
     }
getRowActions ($asObject = FALSE)
Returns
OBJECT $_oFormConfig["oRowActions"]
Definition at line 993 of file Form.save.php.
{
         return ($asObject) ? (object)$this->_oFormConfig["oRowActions"] : (array)$this->_oFormConfig["oRowActions"];
     }
getRowActions ($asObject = FALSE)
Returns
OBJECT $_oFormConfig["oRowActions"]
Definition at line 1193 of file Form.php.
Referenced by generateForm().
{
         return ($asObject) ? (object)$this->_oFormConfig["oRowActions"] : (array)$this->_oFormConfig["oRowActions"];
     }
getSession ()
get session
Returns
Zend_Session_Namespace
Definition at line 720 of file Form.save.php.
References $_oFormSession, and _setFormSession().
{
         if ($this->_oFormSession === NULL) {
             $this->_setFormSession(NULL, FALSE);
         }
         return $this->_oFormSession;
     }
getSession ()
get session
Returns
Zend_Session_Namespace
Definition at line 920 of file Form.php.
References $_oFormSession, and _setFormSession().
Referenced by __init().
{
         if ($this->_oFormSession === NULL) {
             $this->_setFormSession(NULL, FALSE);
         }
         return $this->_oFormSession;
     }
getTpl ($tplName = NULL, $reset = FALSE) inherited
generate and get template objects
Parameters
string $tplName
boolean $reset
Returns
Template
Definition at line 275 of file Abstract.php.
Referenced by generateForm(), generateFormAction(), generateFormElementAction(), generateFormElements(), generateFormJS(), generateFormTools(), Contenido_Plugin_GUI\generateNavigationList(), Contenido_Plugin_GUI_Table\generateTable(), Contenido_Plugin_GUI_Table\generateTableAction(), Contenido_Plugin_GUI_Table\generateTableJS(), Contenido_Plugin_GUI_Table\generateTableTools(), Contenido_Plugin_GUI\getFrameTemplate(), Contenido_Plugin_GUI\page_close(), Contenido_Plugin_GUI\page_open(), Contenido_Object_Abstract\setTpl(), and Contenido_Object_Abstract\setTplVars().
{
         if ( empty($tplName) ) {
             $tplName = 'default';
         }
         if ( ( !isset($this->_tpls[$tplName]) || !isset($this->_tpls[$tplName]->template) || !($this->_tpls[$tplName]->template instanceof Template) ) || $reset) {
             $oTemplate = new Template();
             $oTemplate->reset();
             $this->_tpls[$tplName] = (object)array(
                 "name"      =>  $tplName,
                 "template"  =>  $oTemplate,
                 "content"   =>  '',
                 "static"    =>  array(),
                 "dynamic"   =>  array(),
             );
         }
         if ($reset) {
             $this->_tpls[$tplName]->template->reset();
         }
         return $this->_tpls[$tplName];
     }
getValues ($field = NULL)
get current form values, for given field(set) or all
Parameters
STRING $field
Definition at line 1275 of file Form.php.
{
         return ($this);
     }
isAuthNobody () inherited
determine if current Contenido user is not an authorized user
Returns
boolean
Definition at line 474 of file Abstract.php.
References Contenido_Object_Abstract\getAuthId().
{
         return $this->getAuthId() == "nobody";
     }
isDebug () inherited
determine if debug mode is set to true
Returns
boolean
Definition at line 482 of file Abstract.php.
References Contenido_Object_Abstract\getConfig().
{
         return $this->getConfig()->debug === true;
     }
resetNotifications ()
Parameters
field_type $_notifications
Definition at line 1256 of file Form.php.
{
         $this->_oFormNotifications = array();
     }
setElementError (& $element = NULL, $aErrorData = array())
set error messages to element properties
Parameters
ARRAY $aErrorData
Definition at line 1293 of file Form.php.
{
         return ($this);
     }
setElements ($_aElements = array())
Parameters
ARRAY $_aElements
Returns
Contenido_Plugin_GUI_Form
Definition at line 774 of file Form.save.php.
References $_aElements, and _setFormSession().
{
         $this->_aElements = $_aElements;
         $this->_oFormConfig["oElements"] =& $this->_aElements;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setElements ($_aElements = array())
Parameters
ARRAY $_aElements
Returns
Contenido_Plugin_GUI_Form
Definition at line 974 of file Form.php.
References $_aElements, and _setFormSession().
Referenced by __init().
{
         $this->_aElements = $_aElements;
         $this->_oFormConfig["elements"] =& $this->_aElements;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setErrors ($aErrorData = array())
set error messages to element properties
Parameters
ARRAY $aErrorData
Definition at line 1284 of file Form.php.
{
         return ($this);
     }
setFooter ($_aFooterCells = array())
Parameters
ARRAY $_aFooterCells
Returns
Contenido_Plugin_GUI_Form
Definition at line 792 of file Form.save.php.
References _setFormSession().
{
         $this->_aFooterCells = $_aFooterCells;
         $this->_oFormConfig["oFooterCells"] =& $this->_aFooterCells;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setFooter ($_aFooterCells = array())
Parameters
ARRAY $_aFooterCells
Returns
Contenido_Plugin_GUI_Form
Definition at line 992 of file Form.php.
References _setFormSession().
{
         $this->_aFooterCells = $_aFooterCells;
         $this->_oFormConfig["oFooterCells"] =& $this->_aFooterCells;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setFormActions ($_oFormActions)
Parameters
ARRAY $_oFormActions
Returns
Contenido_Plugin_GUI_Form
Definition at line 924 of file Form.save.php.
References _setFormSession().
{
         $this->_oFormConfig["oFormActions"] = $_oFormActions;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setFormActions ($_oFormActions)
Parameters
ARRAY $_oFormActions
Returns
Contenido_Plugin_GUI_Form
Definition at line 1124 of file Form.php.
References _setFormSession().
Referenced by __init().
{
         $this->_oFormConfig["oFormActions"] = $_oFormActions;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setFormConfig ($_oFormConfig)
Parameters
ARRAY $_oFormConfig
Returns
Contenido_Plugin_GUI_Form
Definition at line 907 of file Form.save.php.
References $_oFormConfig, and _setFormSession().
{
         $this->_oFormConfig = $_oFormConfig;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setFormConfig ($_oFormConfig)
Parameters
ARRAY $_oFormConfig
Returns
Contenido_Plugin_GUI_Form
Definition at line 1107 of file Form.php.
References $_oFormConfig, and _setFormSession().
Referenced by __init().
{
         $this->_oFormConfig = $_oFormConfig;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setFormDataError ($_oFormDataError)
Parameters
Exception $_oFormDataError
Returns
Contenido_Plugin_GUI_Form
Definition at line 873 of file Form.save.php.
References $_oFormDataError, and _setFormSession().
{
         $this->_oFormDataError = $_oFormDataError;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setFormDataError ($_oFormDataError)
Parameters
Exception $_oFormDataError
Returns
Contenido_Plugin_GUI_Form
Definition at line 1073 of file Form.php.
References $_oFormDataError, and _setFormSession().
{
         $this->_oFormDataError = $_oFormDataError;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setFormName ($_sFormName)
Parameters
STRING $_sFormName
Returns
Contenido_Plugin_GUI_Form
Definition at line 890 of file Form.save.php.
References $_sFormName, and _setFormSession().
{
         $this->_sFormName = $_sFormName;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setFormName ($_sFormName)
Parameters
STRING $_sFormName
Returns
Contenido_Plugin_GUI_Form
Definition at line 1090 of file Form.php.
References $_sFormName, and _setFormSession().
Referenced by __init().
{
         $this->_sFormName = $_sFormName;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setFormTemplates ($_oFormTools)
Parameters
ARRAY $_oFormTools
Returns
Contenido_Plugin_GUI_Form
Definition at line 941 of file Form.save.php.
References $_oFormTools, and _setFormSession().
{
         $this->_oFormConfig["oTemplates"] = $_oFormTools;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setFormTemplates ($_oFormTools)
Parameters
ARRAY $_oFormTools
Returns
Contenido_Plugin_GUI_Form
Definition at line 1141 of file Form.php.
References $_oFormTools, and _setFormSession().
Referenced by __init().
{
         $this->_oFormConfig["oTemplates"] = $_oFormTools;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setFormTools ($_oFormTools)
Parameters
ARRAY $_oFormTools
Returns
Contenido_Plugin_GUI_Form
Definition at line 958 of file Form.save.php.
References $_oFormTools, and _setFormSession().
{
         $this->_oFormTools = $_oFormTools;
         $this->_oFormConfig["oFormTools"] =& $this->_oFormTools;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setFormTools ($_oFormTools)
Parameters
ARRAY $_oFormTools
Returns
Contenido_Plugin_GUI_Form
Definition at line 1158 of file Form.php.
References $_oFormTools, and _setFormSession().
Referenced by __init(), and _parseToolsParams().
{
         $this->_oFormTools = $_oFormTools;
         $this->_oFormConfig["oFormTools"] =& $this->_oFormTools;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setNoRenderActions ($aNoRenderActions)
Parameters
ARRAY $aNoRenderActions
Returns
Contenido_Plugin_GUI_Form
Definition at line 984 of file Form.save.php.
References $aNoRenderActions, and _setFormSession().
{
         $this->aNoRenderActions = $aNoRenderActions;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setNoRenderActions ($aNoRenderActions)
Parameters
ARRAY $aNoRenderActions
Returns
Contenido_Plugin_GUI_Form
Definition at line 1184 of file Form.php.
References $aNoRenderActions, and _setFormSession().
{
         $this->aNoRenderActions = $aNoRenderActions;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setOptions ($options) inherited
set object options array
Parameters
array | stdClass $options
Returns
Contenido_Object_Abstract
Definition at line 384 of file Abstract.php.
References Contenido_Object_Abstract\getOptions().
Referenced by Contenido_Object_Abstract\__init().
{
         $aOptions = $this->getOptions();
         $this->_options = array_merge_recursive($aOptions, (array)$options);
         return ($this);
     }
setQuery ($_sQuery)
Parameters
STRING $_sQuery
Returns
Contenido_Plugin_GUI_Form
Definition at line 836 of file Form.save.php.
References $_sQuery, and _setFormSession().
{
         $this->_sQuery = $_sQuery;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setQuery ($_sQuery)
Parameters
STRING $_sQuery
Returns
Contenido_Plugin_GUI_Form
Definition at line 1036 of file Form.php.
References $_sQuery, and _setFormSession().
Referenced by _buildQuery().
{
         $this->_sQuery = $_sQuery;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setRowActions ($_oRowActions)
Parameters
ARRAY $_oRowActions
Returns
Contenido_Plugin_GUI_Form
Definition at line 1001 of file Form.save.php.
References _setFormSession().
{
         $this->_oFormConfig["oRowActions"] = $_oRowActions;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setRowActions ($_oRowActions)
Parameters
ARRAY $_oRowActions
Returns
Contenido_Plugin_GUI_Form
Definition at line 1201 of file Form.php.
References _setFormSession().
{
         $this->_oFormConfig["oRowActions"] = $_oRowActions;
         $this->_setFormSession(NULL, FALSE);
         return $this;
     }
setTplVars ($tplName, $config, $reset = FALSE) inherited
set template variables (static and dynamic) array
Parameters
string $tplName
array | stdClass $config
boolean $reset
Returns
Template
Definition at line 328 of file Abstract.php.
References Contenido_Object_Abstract\getTpl().
Referenced by generateFormAction(), generateFormJS(), Contenido_Plugin_GUI\generateNavigationList(), Contenido_Plugin_GUI_Table\generateTableAction(), Contenido_Plugin_GUI_Table\generateTableJS(), Contenido_Plugin_GUI\page_close(), Contenido_Plugin_GUI\page_open(), and Contenido_Object_Abstract\setTpl().
{
         if ( empty($tplName) ) {
             $tplName = 'default';
         }
         if ( is_array($config) ) { $config = (object)$config; }
         $oTemplate = $this->getTpl( $tplName, $reset );
         if ( is_array($config->static) || is_object($config->static) ) {
             foreach ((array)$config->static as $needle => $replacement) {
                 $oTemplate->template->set("s", $needle, $replacement);
             }
         }
         if ( is_array($config->dynamic) || is_object($config->dynamic) ) {
             foreach ((array)$config->dynamic as $idx => $vars) {
                 $oTemplate->template->set("d", "BLOCKINDEX", $replacement);
                 foreach ((array)$vars as $needle => $replacement) {
                     $oTemplate->template->set("d", $needle, $replacement);
                 }
                 $oTemplate->template->next();
             }
         }
         return ($oTemplate->template);
     }
setValues ($aData = array(), $bForce = FALSE)
set current form values
Parameters
ARRAY $aData
BOOLEAN $bForce
Definition at line 1266 of file Form.php.
{
         return ($this);
     }
validateData ($aData = array(), $bAddNotification = true)
validate form value data array retruns TRUE or array with error messages
Parameters
BOOLEAN | ARRAY $aData
BOOLEAN $bAddNotification
Definition at line 1304 of file Form.php.
{
         return (true);
     }
validateFormElements ($aElements = NULL, $aData = NULL, $parent = NULL, $level = 0, $bReturn = TRUE)
Definition at line 1308 of file Form.php.
References Contenido_Object_Abstract\getConfig().
{
         $aErrors = array();
         if ( !is_array($aElements) ) {
             return true;
         }
         foreach ($aElements as $key => $element) {
             if ( is_array($element) ) { $element = (object)$element; }
             if ( ($element->type == 'fieldset') && (is_array($element->elements)) ) {
                 // generate fieldset mark-up
                 $element->fieldID = ( ($parent != NULL) ? $parent->fieldID . '_' : $this->getId() . '_' ). 'fieldset_'.$level.'_'.$key;
                 $aSubErrors = $this->validateFormElements($element->elements, $aData[$element->name], $element, 1+$level, $bReturn);
                 if ($aSubErrors !== true) {
                     $aErrors[$element->name] = $aSubErrors;
                 }
             } else {
                 if ( $element->required && (!isset($aData[$element->name]) || empty($aData[$element->name])) ) {
                     $aErrors[$element->name] = sprintf(
                         $this->getConfig(TRUE)->oMessages["error_field_required"],
                         htmlentities($element->label)
                     );
                 }
                 if (false) {}
                 switch ($element->type) {
                     case "select":
                         $sInputHTML = "<select ".
                             "id=\"".$element->fieldID."\" ".
                             "name=\"".$element->field."\" ".
                             "class=\"".$sClassnames."\" ".
                             "size=\"".(((int)$element->size > 0) ? (int)$element->size : 1)."\" ".
                         ">".
                             "!_SELECTOPTIONS_".$element->field."_!".
                         "</select>";
                         $sSelectOptions = "";
                         if ( is_array($element->options) ) {
                             foreach ($element->options as $key => $oOption) {
                                 $sSelectOptions .= "<option ".
                                     "value=\"".$oOption["value"]."\" ".
                                         ( ( !is_array($element->value) && ($oOption["value"] == $element->value) ) ? "selected=\"selected\" " : "" ).
                                         ( ( is_array($element->value) && in_array($oOption["value"], $element->value) ) ? "selected=\"selected\" " : "" ).
                                 ">".
                                     "".$oOption["text"]."".
                                 "</option>";
                             }
                         }
                         $sInputHTML = str_replace("!_SELECTOPTIONS_".$element->field."_!", $sSelectOptions, $sInputHTML);
                     break;
                     case "radio":
                     case "checkbox":
                         $sInputHTML = "<ul class=\"".$element->type."list\">";
                         if ( is_array($element->options) ) {
                             foreach ($element->options as $key => $oOption) {
                                 $sInputHTML .= "<li>".
                                     "<label>".
                                         "<input ".
                                             "id=\"".$element->fieldID."_".$key."\" ".
                                             "type=\"".$element->type."\" ".
                                             "name=\"".$element->field."\" ".
                                             "class=\"".$sClassnames."\" ".
                                             "value=\"".$oOption["value"]."\" ".
                                                 ( ( !is_array($element->value) && ($oOption["value"] == $element->value) ) ? "checked=\"checked\" " : "" ).
                                                 ( ( is_array($element->value) && in_array($oOption["value"], $element->value) ) ? "checked=\"checked\" " : "" ).
                                             (!empty($sAttributes) ? $sAttributes : "").
                                         "/>".
                                         "".$oOption["text"]."".
                                     "</label>".
                                 "</li>";
                             }
                         } else {
                             $sInputHTML = "";
                         }
                         if ( !empty($sInputHTML) ) {
                             $sInputHTML .= "</ul>";
                         }
                     break;
                     case "textarea":
                         $sInputHTML = "<textarea ".
                             "id=\"".$element->fieldID."\" ".
                             "name=\"".$element->field."\" ".
                             "class=\"".$sClassnames."\" ".
                             (((int)$element->rows > 0) ? "rows=\"".((int)$element->rows)."\" " : "").
                             (((int)$element->cols > 0) ? "cols=\"".((int)$element->cols)."\" " : "").
                             (!empty($sAttributes) ? $sAttributes : "").
                             ">".
                             $element->value.
                         "</textarea>";
                     break;
                     default:
                         if ( !in_array( strtolower($element->type), (array)$this->types ) ) {
                             $sType = "text";
                         } else  {
                             $sType = strtolower($element->type);
                         }
                         $sInputHTML = "<input ".
                             "id=\"".$element->fieldID."\" ".
                             "type=\"".$sType."\" ".
                             "name=\"".$element->field."\" ".
                             "class=\"".$sClassnames."\" ".
                             "value=\"".$element->value."\" ".
                             (((int)$element->size > 0) ? "size=\"".((int)$element->size)."\" " : "").
                             (!empty($sAttributes) ? $sAttributes : "").
                             "/>";
                     break;
                 }
             }
         }
         if ( is_array($aErrors) && !empty($aErrors) ) {
             return ($aErrors);
         }
         return (true);
     }
Member Data Documentation
$_aElements = array()
Definition at line 38 of file Form.php.
Referenced by getElements(), and setElements().
DB_Contenido $_oDB = null
form db object container
Definition at line 56 of file Form.php.
$_oFormConfig
Definition at line 80 of file Form.php.
Referenced by getFormConfig(), and setFormConfig().
Exception $_oFormDataError = NULL
form data error container object
Definition at line 62 of file Form.php.
Referenced by _getFormDataError(), and setFormDataError().
$_oFormNotifications = array()
Returns
the $_notifications
Definition at line 67 of file Form.php.
Referenced by getNotifications().
ARRAY $_oFormSession = NULL
form session container
Definition at line 73 of file Form.php.
Referenced by _setFormSession(), and getSession().
$_oFormTools
Initial value:
= array(
        "page"              => 1,
        "pages"             => 1,
        "autocomplete"      => FALSE,
        "filterFields"      => FALSE,
    )
Definition at line 166 of file Form.php.
Referenced by getFormTools(), setFormTemplates(), and setFormTools().
$_sFormHashId = NULL
Definition at line 32 of file Form.php.
Referenced by _setFormHashId(), and getHash().
STRING $_sFormId = NULL
form object container id
Definition at line 20 of file Form.php.
Referenced by getId().
STRING $_sFormIdPrefix = 'form_'
form object container id prefix string
Definition at line 26 of file Form.php.
STRING $_sFormName = "" protected
db form name string
Definition at line 50 of file Form.php.
Referenced by getFormName(), and setFormName().
STRING $_sQuery = ""
db form SQL query string
Definition at line 44 of file Form.php.
Referenced by getQuery(), and setQuery().
$_tpls inherited
Initial value:
= array(
    )
Definition at line 56 of file Abstract.php.
$aEncTypes
Initial value:
= array(
        "URL"   => "application/x-www-form-urlencoded",
        "DATA"  => "multipart/form-data",
        "PLAIN" => "text/plain"
    )
Definition at line 183 of file Form.php.
$aNoRenderActions
Initial value:
= array(
        "reset",
        "update",
        "config",
        "prepare",
        "get",
        "put",
        "delete",
        "getsessionhash",
        "getsessiondata",
        "getformdata"
    )
Definition at line 193 of file Form.php.
Referenced by getNoRenderActions(), and setNoRenderActions().
$types = array("text", "password", "button", "file", "radio", "checkbox", "textarea", "select", "hidden")
Definition at line 177 of file Form.php.
The documentation for this class was generated from the following files:
/Users/bba/resources/php/contenido/Plugin_and_Extension_API__PEA/branches/4.8/classes/Contenido/Plugin/GUI/Form.php
/Users/bba/resources/php/contenido/Plugin_and_Extension_API__PEA/branches/4.8/classes/Contenido/Plugin/GUI/Form.save.php