Contenido PEA: /Users/bba/resources/php/contenido/Plugin_and_Extension_API__PEA/branches/4.8/classes/Contenido/Object/Abstract.php File Reference
Abstract.php File Reference
Classes
class Contenido_Object_Abstract
Variables
if(!defined('CON_FRAMEWORK'))
global $action
if(!defined('CON_FRAMEWORK'))
global $area
if(!defined('CON_FRAMEWORK'))
global $cfg
if(!defined('CON_FRAMEWORK'))
global $cfgClient
if(!defined('CON_FRAMEWORK'))
global $client
if(!defined('CON_FRAMEWORK'))
global $file
if(!defined('CON_FRAMEWORK'))
global $filename
if(!defined('CON_FRAMEWORK'))
global $frame
if(!defined('CON_FRAMEWORK'))
global $lang
if(!defined('CON_FRAMEWORK'))
global $perm
if(!defined('CON_FRAMEWORK'))
global $sess
if(!defined('CON_FRAMEWORK'))
global $tpl
Variable Documentation
if (!defined('CON_FRAMEWORK')) global $action
Definition at line 2 of file Abstract.php.
Referenced by Contenido_Plugin_GUI_Form\generateFormAction(), Contenido_Plugin_GUI_Form\generateFormElementAction(), and Contenido_Plugin_GUI_Table\generateTableAction().
if (!defined('CON_FRAMEWORK')) global $area
Definition at line 2 of file Abstract.php.
Referenced by Contenido_Plugin_GUI_Form\generateFormAction(), Contenido_Plugin_GUI_Form\generateFormElementAction(), and Contenido_Plugin_GUI_Table\generateTableAction().
if (!defined('CON_FRAMEWORK')) global $cfg
Definition at line 2 of file Abstract.php.
Referenced by Contenido_Plugin_GUI_Form\generateForm(), Contenido_Plugin_GUI_Table\generateTable(), Contenido_Plugin_GUI_Form\getFormToolsURL(), Contenido_Plugin_GUI_Table\getTableToolsURL(), and Contenido_Plugin_GUI\messageBox().
if (!defined('CON_FRAMEWORK')) global $cfgClient
Definition at line 2 of file Abstract.php.
if (!defined('CON_FRAMEWORK')) global $client
Definition at line 2 of file Abstract.php.
if (!defined('CON_FRAMEWORK')) global $file
Definition at line 2 of file Abstract.php.
if (!defined('CON_FRAMEWORK')) global $filename
Definition at line 2 of file Abstract.php.
if (!defined('CON_FRAMEWORK')) global $frame
Definition at line 2 of file Abstract.php.
if (!defined('CON_FRAMEWORK')) global $lang
Definition at line 2 of file Abstract.php.
if (!defined('CON_FRAMEWORK')) global $perm
Definition at line 2 of file Abstract.php.
if (!defined('CON_FRAMEWORK')) global $sess
Definition at line 2 of file Abstract.php.
Referenced by Contenido_Plugin_GUI\generateNavigationList().
if (!defined('CON_FRAMEWORK')) global $tpl
Definition at line 2 of file Abstract.php.